<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.555">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Trabajo 1">

<title>SOL3070 Análisis de Datos Categóricos</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="t_1_answers_files/libs/clipboard/clipboard.min.js"></script>
<script src="t_1_answers_files/libs/quarto-html/quarto.js"></script>
<script src="t_1_answers_files/libs/quarto-html/popper.min.js"></script>
<script src="t_1_answers_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="t_1_answers_files/libs/quarto-html/anchor.min.js"></script>
<link href="t_1_answers_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="t_1_answers_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="t_1_answers_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="t_1_answers_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="t_1_answers_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">SOL3070 Análisis de Datos Categóricos</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Trabajo 1 </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="información" class="level2">
<h2 class="anchored" data-anchor-id="información">Información</h2>
<ul>
<li><p>Ponderación: 25% de la nota final del curso.</p></li>
<li><p>Bonus: Responder la pregunta <em>bonus</em> NO es un requisito necesario para obtener puntaje completo. Responder incorrectamente la pregunta <em>bonus</em> no afectará negativamente la nota obtenida, pero responderla correctamente mejorará la nota obtenida en un máximo de 0.5 puntos (o en la cantidad necesaria para obtener nota máxima si la nota original fuera superior a 6.5)</p></li>
</ul>
</section>
<section id="introducción" class="level2">
<h2 class="anchored" data-anchor-id="introducción">Introducción</h2>
<p>En este trabajo usarán datos extraidos de 9.303 biografías de chilenos disponibles en Wikipedia (en hasta 160 lenguas). La información de este fue recopilada en el proyecto de investigación “Social Memory about Chileans in Wikipedia”, financiado por Wikimedia Research Fund. Si usas estos datos, por favor cita la siguiente publicación: Beytía, P., Rojas, C. &amp; Cruz, C. (2024). Social memory about people from a country. The case of notable Chileans in Wikipedia. Wiki Workshop 2024.​</p>
<p>Dado que contar con una biografía en Wikipedia es un indicador de prominencia social, utilizaremos esta subpoblación de individuos “notables” para modelar la probabilidad de que una persona destacada se dedique a la política, considerando como variables predictoras su género y año de nacimiento.</p>
<p>Los datos están disponibles en el repositorio del curso para ser descargados.</p>
</section>
<section id="datos" class="level2">
<h2 class="anchored" data-anchor-id="datos">Datos</h2>
<p>Visualización rápida de la base de datos:</p>
<div class="cell" data-warnings="false">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>path <span class="ot">&lt;-</span> <span class="st">"/Users/mauricio/Library/Mobile Documents/com~apple~CloudDocs/Teaching/ISUC/2024_2_categorical_data_analysis/hw_ans/t_1_answers"</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(path)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>wiki_chileans <span class="ot">&lt;-</span>  <span class="fu">read_csv</span>(<span class="st">"wiki_chileans.csv"</span>) <span class="sc">%&gt;%</span> <span class="fu">as_tibble</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: One or more parsing issues, call `problems()` on your data frame for details,
e.g.:
  dat &lt;- vroom(...)
  problems(dat)</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>wiki_chileans <span class="ot">&lt;-</span> wiki_chileans <span class="sc">%&gt;%</span> <span class="fu">select</span>(personLabel,genderLabel,occupationLabel,birthyear)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>wiki_chileans <span class="ot">&lt;-</span> wiki_chileans <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">person =</span> personLabel,</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">genero =</span> genderLabel,</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">politico =</span> <span class="fu">if_else</span>(<span class="fu">str_detect</span>(occupationLabel, <span class="st">"(pol[ií]tic[oa])"</span>), <span class="dv">1</span>, <span class="dv">0</span>),</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">agno_nacimiento =</span> birthyear) <span class="sc">%&gt;%</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(person,genero,politico,agno_nacimiento)  <span class="sc">%&gt;%</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(genero <span class="sc">!=</span> <span class="st">"género fluido"</span> <span class="sc">&amp;</span> genero <span class="sc">!=</span> <span class="st">"mujer transgénero"</span>)</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(wiki_chileans)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9,292 × 4
   person            genero   politico agno_nacimiento
   &lt;chr&gt;             &lt;chr&gt;       &lt;dbl&gt;           &lt;dbl&gt;
 1 Gabriela Mistral  femenino        0            1889
 2 Michelle Bachelet femenino        1            1951
 3 Isabel Allende    femenino        0            1942
 4 Violeta Parra     femenino        0            1917
 5 Nicole            femenino        0            1977
 6 Coté de Pablo     femenino        0            1979
 7 Camila Vallejo    femenino        1            1988
 8 Margot Honecker   femenino        1            1927
 9 Xiye Bastida      femenino        0            2002
10 Leonor Varela     femenino        0            1972
# ℹ 9,282 more rows</code></pre>
</div>
</div>
</section>
<section id="ejercicios" class="level2">
<h2 class="anchored" data-anchor-id="ejercicios">Ejercicios</h2>
<section id="i.-lpm" class="level3">
<h3 class="anchored" data-anchor-id="i.-lpm">I. LPM</h3>
<ol type="1">
<li>Calcula las probabilidades de que un hombre con biografìa en wikipedia sea político <span class="math inline">\((p_h)\)</span> y de que una mujer con biografìa en wikipedia sea política <span class="math inline">\((p_m)\)</span>. Calcula la diferencia entre ambas proporciones.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> wiki_chileans <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(genero) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">p=</span><span class="fu">mean</span>(politico)) <span class="sc">%&gt;%</span> <span class="fu">pull</span>()</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>p_m <span class="ot">=</span> p[<span class="dv">1</span>]</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>p_h <span class="ot">=</span> p[<span class="dv">2</span>]</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"La probilidad de ser político para un hombre con bio en wikipedia es:"</span>, <span class="fu">round</span>(p_h, <span class="dv">2</span>),<span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>La probilidad de ser político para un hombre con bio en wikipedia es: 0.31 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"La probilidad de ser político para una mujer con bio en wikipedia es:"</span>, <span class="fu">round</span>(p_m, <span class="dv">2</span>),<span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>La probilidad de ser político para una mujer con bio en wikipedia es: 0.19 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>diff_p <span class="ot">=</span> <span class="fu">round</span>(p_h <span class="sc">-</span> p_m, <span class="dv">2</span>)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Diferencia entre probilidad de ser político entre hombres y mujeres (con bio en wikipedia):"</span>, diff_p)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Diferencia entre probilidad de ser político entre hombres y mujeres (con bio en wikipedia): 0.12</code></pre>
</div>
</div>
<ol start="2" type="1">
<li>Usa un LPM para estimar la probabilidad de ser político en función del género. Escribe la ecuación de regresión correspondiente y presenta un <code>summary()</code> de los resultados. Explica el significado estadístico de cada coeficiente y su conexión con los resultados de la pregunta anterior.</li>
</ol>
<p>La ecuación de regresión es: <span class="math inline">\(\mathbb{P}(\text{politico | genero)} = \beta_{0} + \beta_{1}\text{genero}\)</span></p>
<p>Implementación en <code>R</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>lpm_1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(politico <span class="sc">~</span> <span class="fu">factor</span>(genero), <span class="at">data=</span>wiki_chileans)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lpm_1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = politico ~ factor(genero), data = wiki_chileans)

Residuals:
    Min      1Q  Median      3Q     Max 
-0.3103 -0.3103 -0.3103  0.6897  0.8107 

Coefficients:
                        Estimate Std. Error t value            Pr(&gt;|t|)    
(Intercept)              0.18925    0.01065   17.78 &lt;0.0000000000000002 ***
factor(genero)masculino  0.12104    0.01184   10.22 &lt;0.0000000000000002 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.4499 on 9290 degrees of freedom
Multiple R-squared:  0.01111,   Adjusted R-squared:  0.01101 
F-statistic: 104.4 on 1 and 9290 DF,  p-value: &lt; 0.00000000000000022</code></pre>
</div>
</div>
<p>Donde:</p>
<ul>
<li><p><span class="math inline">\(\beta_0\)</span> es el intercepto, que representa la probabilidad promedio de que una persona sea político cuando el género es “femenino” (grupo de referencia). El resultado obtenido indica que la probabilidad de que una mujer sea política es aproximadamente 18.9%.</p></li>
<li><p><span class="math inline">\(\beta_1\)</span> mide el cambio en la probabilidad de ser político cuando el individuo es “masculino” en comparación con el grupo de referencia. El resultado obtenido indica que, en promedio, los hombres tienen una probabilidad 12.1 puntos porcentuales mayor de ser políticos en comparación con las mujeres.</p></li>
<li><p>Por lo tanto, la probabilidad de que un hombre sea político se obtiene sumando los coeficientes del intercepto (<span class="math inline">\(\beta_0\)</span>) y del género masculino (<span class="math inline">\(\beta_1\)</span>): <span class="math inline">\(\mathbb{P}(\text{político | hombre}) = \beta_0 + \beta_1 = 0.18925 + 0.12104 = 0.31029\)</span>. Es decir, la probabilidad de que un hombre sea político es aproximadamente 31.0%.</p></li>
</ul>
<ol start="3" type="1">
<li>Usa un LPM para estimar la probabilidad de ser político en función del género, controlando por el año de nacimiento de los individuos. Escribe la ecuación de regresión correspondiente y presenta un <code>summary()</code> de los resultados. Explica el significado estadístico de cada coeficiente y provee una breve interpretación sustantiva.</li>
</ol>
<p>La ecuación de regresión es: <span class="math inline">\(\mathbb{P}(\text{politico | genero, agno)} = \beta_{0} + \beta_{1}\text{genero} + \beta_{2}\text{agno}\)</span></p>
<p>Implementación en <code>R</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>lpm_2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(politico <span class="sc">~</span> <span class="fu">factor</span>(genero) <span class="sc">+</span> agno_nacimiento , <span class="at">data=</span>wiki_chileans)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lpm_2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = politico ~ factor(genero) + agno_nacimiento, data = wiki_chileans)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.4715 -0.2683 -0.1543  0.3486  0.9604 

Coefficients:
                           Estimate  Std. Error t value             Pr(&gt;|t|)
(Intercept)              6.37212330  0.16343985  38.988 &lt; 0.0000000000000002
factor(genero)masculino  0.06090585  0.01114238   5.466         0.0000000472
agno_nacimiento         -0.00316628  0.00008355 -37.899 &lt; 0.0000000000000002
                           
(Intercept)             ***
factor(genero)masculino ***
agno_nacimiento         ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.4188 on 9283 degrees of freedom
  (6 observations deleted due to missingness)
Multiple R-squared:  0.1436,    Adjusted R-squared:  0.1434 
F-statistic: 778.5 on 2 and 9283 DF,  p-value: &lt; 0.00000000000000022</code></pre>
</div>
</div>
<p>Donde:</p>
<ul>
<li><p><span class="math inline">\(\beta_0=6.372\)</span> es el intercepto. Este valor es la probabilidad estimada de que una persona sea político en el caso hipotético de que el género sea femenino y el año de nacimiento sea cero (lo cual no es realista, pero representa un punto de referencia para el modelo).</p></li>
<li><p><span class="math inline">\(\beta_1=0.06091\)</span> mide el cambio en la probabilidad de ser político cuando el individuo es hombre, en comparación con el grupo de referencia (mujer). El coeficiente positivo indica que los hombres tienen, en promedio, una probabilidad 6.1 puntos porcentuales mayor de ser políticos en comparación con las mujeres, controlando por el año de nacimiento.</p></li>
<li><p><span class="math inline">\(\beta_2=-0.003166\)</span> mide el efecto del año de nacimiento sobre la probabilidad de ser político. Este coeficiente negativo sugiere que la probabilidad de ser político disminuye a medida que el año de nacimiento es más reciente. Cada aumento de un año en el año de nacimiento está asociado con una reducción la probabilidad de ser político en un 0.3166 puntos porcentuales.</p></li>
</ul>
<p>Los resultados sugieren que la probabilidad de que una persona notable se dedique a la política disminuye a medida que el año de nacimiento es más reciente. Aún así, el efecto parcial del género indica que en cada año dado los hombres notables tienen una mayor probabilidad de ser políticos en comparación con las mujeres notables.</p>
<ol start="4" type="1">
<li>De acuerdo al modelo estimado en la pregunta anterior, ¿cuál es el efecto marginal del “año de nacimiento” sobre la probabilidad esperada de ser político?</li>
</ol>
<p>El efecto marginal del “año de nacimiento” sobre la probabilidad esperada de ser político está dado por:</p>
<p><span class="math inline">\(\frac{\partial\mathbb{P}(\text{politico | genero, agno)} }{\partial \text{agno}} = \beta_{2} =\)</span> -0.0031663</p>
<ol start="5" type="1">
<li>En base al modelo usado en I.3., calcula las probabilidades esperadas de ser políticos para un hombre y una mujer que cuentan con una biografía en wikipedia y nacieron en 1973. Expresa formalmente las ecuaciones correspondiente a estas predicciones.</li>
</ol>
<p>Formalmente:</p>
<ul>
<li><span class="math inline">\(\mathbb{P}(\text{politico | genero='femenino', agno=1973)} = \beta_{0} + \beta_{2}*1973=\)</span></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>p_m1973_lpm <span class="ot">=</span> lpm_2<span class="sc">$</span>coefficients[<span class="dv">1</span>] <span class="sc">+</span> lpm_2<span class="sc">$</span>coefficients[<span class="dv">3</span>]<span class="sc">*</span><span class="dv">1973</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(p_m1973_lpm) <span class="ot">&lt;-</span> <span class="st">""</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(p_m1973_lpm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          
0.1250492 </code></pre>
</div>
</div>
<ul>
<li><span class="math inline">\(\mathbb{P}(\text{politico | genero='masculino', agno=1973)} = \beta_{0} + \beta_{1} + \beta_{2}*1973=\)</span></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>p_h1973_lpm <span class="ot">=</span> lpm_2<span class="sc">$</span>coefficients[<span class="dv">1</span>] <span class="sc">+</span> lpm_2<span class="sc">$</span>coefficients[<span class="dv">2</span>]  <span class="sc">+</span> lpm_2<span class="sc">$</span>coefficients[<span class="dv">3</span>]<span class="sc">*</span><span class="dv">1973</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(p_h1973_lpm) <span class="ot">&lt;-</span> <span class="st">""</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(p_h1973_lpm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         
0.185955 </code></pre>
</div>
</div>
<p>Implementación automática en <code>R</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>newx <span class="ot">&lt;-</span> wiki_chileans <span class="sc">%&gt;%</span> <span class="fu">data_grid</span>(<span class="at">genero=</span><span class="fu">c</span>(<span class="st">'femenino'</span>,<span class="st">'masculino'</span>),</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">agno_nacimiento=</span><span class="dv">1973</span>,<span class="at">.model=</span>lpm_2)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>newy <span class="ot">&lt;-</span> newx <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">pred_prob =</span> <span class="fu">predict</span>(lpm_2, <span class="at">newdata =</span> newx)) </span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(newy)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  genero    agno_nacimiento pred_prob
  &lt;chr&gt;               &lt;dbl&gt;     &lt;dbl&gt;
1 femenino             1973     0.125
2 masculino            1973     0.186</code></pre>
</div>
</div>
<ol start="6" type="1">
<li>Agrega una interacción entre <code>genero</code> y <code>agno_nacimiento</code> al modelo estimado en I.3. Escribe la ecuación de regresión y presenta un <code>summary()</code> de los resultados. Interpreta el efecto del año de nacimiento estimado en términos estadísticos y sustantivos.</li>
</ol>
<p>La ecuación de regresión es: <span class="math inline">\(\mathbb{P}(\text{politico | genero, agno)} = \beta_{0} + \beta_{1}\text{genero} + \beta_{2}\text{agno} + \beta_{3}\text{genero:agno}\)</span></p>
<p>Implementación en <code>R</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>lpm_3 <span class="ot">&lt;-</span> <span class="fu">lm</span>(politico <span class="sc">~</span> <span class="fu">factor</span>(genero)<span class="sc">*</span>agno_nacimiento , <span class="at">data=</span>wiki_chileans)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lpm_3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = politico ~ factor(genero) * agno_nacimiento, data = wiki_chileans)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.6192 -0.2415 -0.1665  0.3052  0.9263 

Coefficients:
                                          Estimate Std. Error t value
(Intercept)                             -0.5557115  0.5052994  -1.100
factor(genero)masculino                  7.7678573  0.5327049  14.582
agno_nacimiento                          0.0003816  0.0002587   1.475
factor(genero)masculino:agno_nacimiento -0.0039508  0.0002730 -14.471
                                                   Pr(&gt;|t|)    
(Intercept)                                           0.271    
factor(genero)masculino                 &lt;0.0000000000000002 ***
agno_nacimiento                                       0.140    
factor(genero)masculino:agno_nacimiento &lt;0.0000000000000002 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.4142 on 9282 degrees of freedom
  (6 observations deleted due to missingness)
Multiple R-squared:  0.1625,    Adjusted R-squared:  0.1623 
F-statistic: 600.4 on 3 and 9282 DF,  p-value: &lt; 0.00000000000000022</code></pre>
</div>
</div>
<p>Al añadir una interacción entre <code>genero</code> y <code>agno_nacimiento</code> permitimos que el efecto del año de nacimiento dependa de si el individuo es hombre o mujer (y viceversa). Es decir, no hay un único efecto del año de nacimiento si no dos. Para las mujeres con biografía en wikipedia la probabilidad esperada ser político viene dada por:</p>
<ul>
<li><span class="math inline">\(\mathbb{P}(\text{politico | genero='femenino', agno)} = \beta_{0} +  \beta_{2}\text{agno}\)</span></li>
</ul>
<p>Por tanto, el efecto de <code>agno_nacimiento</code> sobre la probabilidad de ser político es: <span class="math inline">\(\frac{\partial \mathbb{P}(\text{politico} \mid \text{genero='femenino', agno})}{\partial \text{agno}} = \beta_{2}=\)</span> 0.0003816</p>
<p>Por su parte, para las mujeres con biografía en wikipedia la probabilidad esperada ser político viene dada por:</p>
<ul>
<li><span class="math inline">\(\mathbb{P}(\text{politico | genero='masculino', agno)} = (\beta_{0} + \beta_{1}) + (\beta_{2} + \beta_{3})\text{agno}\)</span></li>
</ul>
<p>Por tanto: <span class="math inline">\(\frac{\partial \mathbb{P}(\text{politico} \mid \text{genero='masculino', agno})}{\partial \text{agno}} = \beta_{2} + \beta_{3}=\)</span> -0.0035692</p>
</section>
<section id="ii.-regresión-logística" class="level3">
<h3 class="anchored" data-anchor-id="ii.-regresión-logística">II. Regresión Logística</h3>
<ol type="1">
<li>Calcula la odds de que un hombre con biografìa en wikipedia sea político <span class="math inline">\((\text{odd}_h)\)</span> y de que una mujer con biografìa en wikipedia sea política <span class="math inline">\((\text{odd}_m)\)</span>. Calcula el ratio entre ambas odds (hombre vs mujer) e interpreta el odds ratio resultante.</li>
</ol>
<p>Implementación en <code>R</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>tabla <span class="ot">&lt;-</span> wiki_chileans <span class="sc">%&gt;%</span> <span class="fu">with</span>(<span class="fu">table</span>(genero,politico)) </span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>odd_m <span class="ot">=</span> tabla[<span class="dv">1</span>,<span class="dv">2</span>]<span class="sc">/</span>tabla[<span class="dv">1</span>,<span class="dv">1</span>]</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>odd_h <span class="ot">=</span> tabla[<span class="dv">2</span>,<span class="dv">2</span>]<span class="sc">/</span>tabla[<span class="dv">2</span>,<span class="dv">1</span>]</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Las odds de ser político para un hombre con bio en wikipedia es:"</span>, <span class="fu">round</span>(odd_h, <span class="dv">2</span>),<span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Las odds de ser político para un hombre con bio en wikipedia es: 0.45 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Las odds de ser político para una mujer con bio en wikipedia es:"</span>, <span class="fu">round</span>(odd_m, <span class="dv">2</span>),<span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Las odds de ser político para una mujer con bio en wikipedia es: 0.23 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>theta <span class="ot">=</span> <span class="fu">round</span>(odd_h<span class="sc">/</span>odd_m, <span class="dv">2</span>)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Odds ratio de ser político entre hombres y mujeres (con bio en wikipedia$) es:"</span>, theta)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Odds ratio de ser político entre hombres y mujeres (con bio en wikipedia$) es: 1.93</code></pre>
</div>
</div>
<p>El <em>odds ratio</em> de 1.93 indica que, entre personas con biografía en Wikipedia, los hombres tienen aproximadamente 1.93 veces las chances de ser políticos que las mujeres.</p>
<ol start="2" type="1">
<li>Usa una regresión logística para estimar la log-odds de ser político en función del género. Escribe la ecuación de regresión correspondiente y presenta un <code>summary()</code> de los resultados. Explica el significado estadístico de cada coeficiente y su conexión con los resultados de la pregunta anterior.</li>
</ol>
<p>La ecuación de regresión es: <span class="math inline">\(\ln\frac{\mathbb{P}(\text{politico | genero)}}{1-\mathbb{P}(\text{politico | genero)}} =  \beta_{0} + \beta_{1}\text{genero}\)</span></p>
<p>Implementación en <code>R</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>logit_1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(politico <span class="sc">~</span> <span class="fu">factor</span>(genero), <span class="at">family=</span> <span class="fu">binomial</span>(<span class="at">link=</span>logit), <span class="at">data=</span>wiki_chileans)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(logit_1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = politico ~ factor(genero), family = binomial(link = logit), 
    data = wiki_chileans)

Coefficients:
                        Estimate Std. Error z value            Pr(&gt;|z|)    
(Intercept)             -1.45489    0.06041  -24.08 &lt;0.0000000000000002 ***
factor(genero)masculino  0.65611    0.06536   10.04 &lt;0.0000000000000002 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 11140  on 9291  degrees of freedom
Residual deviance: 11030  on 9290  degrees of freedom
AIC: 11034

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p>Donde:</p>
<ul>
<li><p><span class="math inline">\(\beta_0=-1.45489\)</span> es el intercepto, que representa las <em>log-odds</em> de ser político para las mujeres (grupo de referencia).</p></li>
<li><p><span class="math inline">\(\beta_1=0.65611\)</span> es el coeficiente asociado al género masculino. Este valor indica que las <em>log-odds</em> de ser político para un hombre aumentan en 0.65611 en comparación con las mujeres.</p></li>
</ul>
<p>También podemos interpretar estos resultados en términos de las <em>odds</em> de ser político</p>
<ul>
<li><p>Para las mujeres (grupo de referencia), las <em>odds</em> de ser político son: <span class="math inline">\(\text{odd}_m = e^{\beta_0}\)</span></p></li>
<li><p>Para los hombres, las <em>odds</em> son: <span class="math inline">\(\text{odd}_h = e^{\beta_0 + \beta_1}\)</span></p></li>
</ul>
<p>Por tanto, el <em>odds ratio</em> entre hombres y mujeres se obtiene como:</p>
<p><span class="math display">\[\theta = \frac{\text{odd}_h}{\text{odd}_m} = \frac{e^{\beta_0 + \beta_1}}{e^{\beta_0}} = e^{\beta_1} = e^{0.65611} \approx 1.93\]</span></p>
<p>Por tanto, si el coeficiente <span class="math inline">\(\beta_1\)</span> captura el efecto del género masculino en las <em>log-odds</em> de ser político, exponenciando este coeficiente, obtenemos el <em>odds ratio</em>, que refleja la ventaja relativa de los hombres frente a las mujeres en cuanto a la probabilidad de ser político.</p>
<ol start="3" type="1">
<li>Usa una regresión para estimar las log-odds de ser político en función del género, controlando por el año de nacimiento de los individuos. Escribe la ecuación de regresión correspondiente y presenta un <code>summary()</code> de los resultados. Explica el significado estadístico de cada coeficiente y provee una breve interpretación sustantiva.</li>
</ol>
<p>La ecuación de regresión es: <span class="math inline">\(\mathbb{P}(\text{politico | genero, agno)} = \beta_{0} + \beta_{1}\text{genero} + \beta_{2}\text{agno}\)</span></p>
<p>Implementación en <code>R</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>logit_2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(politico <span class="sc">~</span> <span class="fu">factor</span>(genero) <span class="sc">+</span> agno_nacimiento, <span class="at">family=</span><span class="fu">binomial</span>(<span class="at">link=</span>logit), <span class="at">data=</span>wiki_chileans)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(logit_2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = politico ~ factor(genero) + agno_nacimiento, family = binomial(link = logit), 
    data = wiki_chileans)

Coefficients:
                          Estimate Std. Error z value             Pr(&gt;|z|)    
(Intercept)             28.9710802  0.9664043  29.978 &lt; 0.0000000000000002 ***
factor(genero)masculino  0.3660260  0.0688208   5.319          0.000000105 ***
agno_nacimiento         -0.0156276  0.0004964 -31.484 &lt; 0.0000000000000002 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 11136.4  on 9285  degrees of freedom
Residual deviance:  9839.2  on 9283  degrees of freedom
  (6 observations deleted due to missingness)
AIC: 9845.2

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<ul>
<li><p><span class="math inline">\(\beta_0=28.9711\)</span> es el intercepto, que representa las <em>log-odds</em> de ser político para las mujeres nacidas en el año 0 (aunque no es una situación realista, es el punto de referencia del modelo).</p></li>
<li><p><span class="math inline">\(\beta_1=0.3660\)</span> es el coeficiente que mide el efecto de ser hombre sobre las <em>log-odds</em> de ser político, controlando por el año de nacimiento. Este valor indica que, para cualquier año dado, las <em>log-odds</em> de ser político aumentan en 0.3660 si el individuo es hombre, en comparación con una mujer.</p></li>
<li><p><span class="math inline">\(\beta_2=-0.01563\)</span> es el coeficiente que mide el efecto del año de nacimiento sobre las <em>log-odds</em> de ser político. Este coeficiente negativo indica que a medida que el año de nacimiento aumenta (es decir, para individuos nacidos más recientemente), las <em>log-odds</em> de ser político disminuyen. Específicamente cada año adicional está asociado con una reducción las <em>log-odds</em> de ser político en aproximadamente 0.0156 – tanto para hombres como para mujeres.</p></li>
</ul>
<p>El coeficiente negativo del año de nacimiento sugiere una tendencia histórica, donde las personas personas notables de generaciones más antiguas tenían una mayor probabilidad de ser políticos, mientras que en generaciones más recientes las ocupaciones de personas notables de habrías diversificado.</p>
<ol start="4" type="1">
<li>De acuerdo al modelo estimado en la pregunta anterior, ¿cuál es la fórmula para el efecto marginal del “año de nacimiento” sobre la probabilidad esperada de ser político?</li>
</ol>
<p><span class="math inline">\(\frac{\partial\mathbb{P}(\text{politico | genero, agno)} }{\partial \text{agno}} = \beta_{2} \cdot \mathbb{P}(\text{politico | genero, agno)} \cdot (1 - \mathbb{P}(\text{politico | genero, agno)})\)</span></p>
<ol start="5" type="1">
<li>En base al modelo usado en II.3., calcula las probabilidades esperadas de ser políticos para un hombre y una mujer que cuentan con una biografía en wikipedia y nacieron en 1973. Expresa formalmente las ecuaciones correspondiente a estas predicciones.</li>
</ol>
<p>Formalmente:</p>
<ul>
<li><span class="math inline">\(\mathbb{P}(\text{politico | genero='femenino', agno=1973)} = \frac{1}{1 + e^{-(\beta_{0} + \beta_{2}*1973)}}=\)</span></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>p_m1973_logit <span class="ot">=</span>  <span class="dv">1</span><span class="sc">/</span>(<span class="dv">1</span> <span class="sc">+</span> <span class="fu">exp</span>(<span class="sc">-</span>(logit_2<span class="sc">$</span>coefficients[<span class="dv">1</span>] <span class="sc">+</span> logit_2<span class="sc">$</span>coefficients[<span class="dv">3</span>]<span class="sc">*</span><span class="dv">1973</span> )))</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(p_m1973_logit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept) 
  0.1344588 </code></pre>
</div>
</div>
<ul>
<li><span class="math inline">\(\mathbb{P}(\text{politico | genero='masculino', agno=1973)} =  \frac{1}{1 + e^{-(\beta_{0} + \beta_{1} + \beta_{2}*1973)}}=\)</span></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>p_h1973_logit <span class="ot">=</span> <span class="dv">1</span><span class="sc">/</span>(<span class="dv">1</span> <span class="sc">+</span> <span class="fu">exp</span>(<span class="sc">-</span>(logit_2<span class="sc">$</span>coefficients[<span class="dv">1</span>] <span class="sc">+</span> logit_2<span class="sc">$</span>coefficients[<span class="dv">2</span>] <span class="sc">+</span> logit_2<span class="sc">$</span>coefficients[<span class="dv">3</span>]<span class="sc">*</span><span class="dv">1973</span>)))</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(p_h1973_logit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(Intercept) 
  0.1830122 </code></pre>
</div>
</div>
<p>Implementación automática en <code>R</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>newx <span class="ot">&lt;-</span> wiki_chileans <span class="sc">%&gt;%</span> <span class="fu">data_grid</span>(<span class="at">genero=</span><span class="fu">c</span>(<span class="st">'femenino'</span>,<span class="st">'masculino'</span>),<span class="at">agno_nacimiento=</span><span class="dv">1973</span>,<span class="at">.model=</span>logit_2)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>newy <span class="ot">&lt;-</span> newx <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">pred_prob =</span> <span class="fu">predict</span>(logit_2, <span class="at">newdata =</span> newx, <span class="at">type=</span><span class="st">"response"</span>)) </span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(newy)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  genero    agno_nacimiento pred_prob
  &lt;chr&gt;               &lt;dbl&gt;     &lt;dbl&gt;
1 femenino             1973     0.134
2 masculino            1973     0.183</code></pre>
</div>
</div>
<ol start="6" type="1">
<li>De acuerdo al modelo estimado en II.3., ¿cual es el efecto marginal del año de nacimiento sobre la la probabilidades esperadas de ser políticos para un hombre y una mujer que cuentan con una biografía en wikipedia y nacieron en 1973. Expresa formalmente las ecuaciones correspondiente dichos efectos. Compara los resultados con la respuesta dada en I.4.</li>
</ol>
<p>Dado que <span class="math inline">\(\frac{\partial\mathbb{P}(\text{politico | genero, agno)} }{\partial \text{agno}} = \beta_{2} \cdot \mathbb{P}(\text{politico | genero, agno)} \cdot (1 - \mathbb{P}(\text{politico | genero, agno)})\)</span></p>
<p>Entonces, reemplazando con las probabilidades predichas calculadas en la pregunta anterior obtenemos que:</p>
<p><span class="math inline">\(\frac{\partial  \mathbb{P}(\text{politico | genero='femenino', agno=1973)} }{\partial \text{agno}}   = \beta_{2} \cdot \mathbb{P}(\text{politico | genero='femenino', agno=1973)}  \cdot (1 - \mathbb{P}(\text{politico | genero='femenino', agno=1973)})\)</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>dydx_m1973 <span class="ot">=</span> logit_2<span class="sc">$</span>coefficients[<span class="dv">3</span>]<span class="sc">*</span>p_m1973_logit<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>p_m1973_logit)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(dydx_m1973)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>agno_nacimiento 
   -0.001818729 </code></pre>
</div>
</div>
<p>y</p>
<p><span class="math inline">\(\frac{\partial  \mathbb{P}(\text{politico | genero='masculino', agno=1973)} }{\partial \text{agno}}   = \beta_{2} \cdot \mathbb{P}(\text{politico | genero='masculino', agno=1973)}  \cdot (1 - \mathbb{P}(\text{politico | genero='masculino', agno=1973)})\)</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>dydx_h1973 <span class="ot">=</span> logit_2<span class="sc">$</span>coefficients[<span class="dv">3</span>]<span class="sc">*</span>p_h1973_logit<span class="sc">*</span>(<span class="dv">1</span><span class="sc">-</span>p_h1973_logit)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(dydx_h1973)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>agno_nacimiento 
   -0.002336613 </code></pre>
</div>
</div>
<p>Implementación automática en <code>R</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>newx <span class="ot">&lt;-</span> wiki_chileans <span class="sc">%&gt;%</span> <span class="fu">data_grid</span>(<span class="at">genero=</span><span class="fu">c</span>(<span class="st">'femenino'</span>,<span class="st">'masculino'</span>),</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>                            <span class="at">agno_nacimiento=</span><span class="dv">1973</span>,<span class="at">.model=</span>logit_2)</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a><span class="fu">slopes</span>(logit_2, <span class="at">variables =</span> <span class="st">"agno_nacimiento"</span>, <span class="at">newdata =</span> newx)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
 Estimate Std. Error     z Pr(&gt;|z|)     S    2.5 %   97.5 %
 -0.00182  0.0000916 -19.8   &lt;0.001 288.9 -0.00200 -0.00164
 -0.00234  0.0000564 -41.4   &lt;0.001   Inf -0.00245 -0.00223

Term: agno_nacimiento
Type:  response 
Columns: rowid, term, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, predicted_lo, predicted_hi, predicted, genero, agno_nacimiento, politico </code></pre>
</div>
</div>
<p>A diferencia del LPM, en el modelo de regresión logística el efecto del año de nacimiento depende del valor de la misma variable y del valor de otras covariables. Esta característica regula que los efectos sean muy limitados cuando las probabilidades se acercan a cero o uno, mientras que pueden ser mayores lejos de dichos valores.</p>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="bonus" class="level2">
<h2 class="anchored" data-anchor-id="bonus">Bonus:</h2>
<ol type="1">
<li>Agrega una interacción entre <code>genero</code> y <code>agno_nacimiento</code> al modelo estimado en II.3 y presenta un <code>summary()</code> de los resultados.</li>
</ol>
<p>Implementación en <code>R</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>logit_3 <span class="ot">&lt;-</span> <span class="fu">glm</span>(politico <span class="sc">~</span> <span class="fu">factor</span>(genero)<span class="sc">*</span>agno_nacimiento, <span class="at">family=</span><span class="fu">binomial</span>(<span class="at">link=</span>logit), <span class="at">data=</span>wiki_chileans)</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(logit_3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = politico ~ factor(genero) * agno_nacimiento, family = binomial(link = logit), 
    data = wiki_chileans)

Coefficients:
                                         Estimate Std. Error z value
(Intercept)                             -6.638093   3.332294  -1.992
factor(genero)masculino                 40.455108   3.498909  11.562
agno_nacimiento                          0.002653   0.001704   1.557
factor(genero)masculino:agno_nacimiento -0.020607   0.001792 -11.500
                                                   Pr(&gt;|z|)    
(Intercept)                                          0.0464 *  
factor(genero)masculino                 &lt;0.0000000000000002 ***
agno_nacimiento                                      0.1195    
factor(genero)masculino:agno_nacimiento &lt;0.0000000000000002 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 11136.4  on 9285  degrees of freedom
Residual deviance:  9678.1  on 9282  degrees of freedom
  (6 observations deleted due to missingness)
AIC: 9686.1

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<ol start="2" type="1">
<li>Reproduce el siguiente gráfico que muestra – en base a los LMP y logit más complejos (con interacción) – las probabilidad predichas de ser polìtico para hombres y mujeres con biografìa en wikipedia nacidos entre los años 1810 y 2024. Compara principales resultados arrojados por ambos modelos.</li>
</ol>
<p>Implementación en <code>R</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># crea un nuevo set de datos sobre los cuales crear predicciones</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>newx <span class="ot">&lt;-</span> wiki_chileans <span class="sc">%&gt;%</span> <span class="fu">data_grid</span>(<span class="at">genero=</span><span class="fu">c</span>(<span class="st">'masculino'</span>,<span class="st">'femenino'</span>), <span class="at">agno_nacimiento=</span><span class="dv">1810</span><span class="sc">:</span><span class="dv">2024</span>,<span class="at">.model=</span>logit_3)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a><span class="co"># crea valores predichos para el nuevo set de datos</span></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>xb_lpm <span class="ot">=</span> <span class="fu">predict</span>(lpm_3 , <span class="at">newdata =</span> newx)</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>xb_logit <span class="ot">=</span> <span class="fu">predict</span>(logit_3, <span class="at">newdata =</span> newx)</span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>prob_lpm <span class="ot">=</span> xb_lpm</span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>prob_logit <span class="ot">=</span> <span class="dv">1</span><span class="sc">/</span>(<span class="dv">1</span> <span class="sc">+</span> <span class="fu">exp</span>(<span class="sc">-</span>xb_logit))</span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a>newy <span class="ot">&lt;-</span> newx <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">prob_lpm =</span> prob_lpm, <span class="at">prob_logit =</span> prob_logit) <span class="sc">%&gt;%</span></span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a>          <span class="fu">pivot_longer</span>(<span class="fu">c</span>(prob_lpm,prob_logit), <span class="at">names_to =</span> <span class="st">"model"</span>, <span class="at">names_prefix =</span> <span class="st">"prob_"</span>)</span>
<span id="cb47-12"><a href="#cb47-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-13"><a href="#cb47-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-14"><a href="#cb47-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Load the Chilean flag image (make sure to have the image in your working directory)</span></span>
<span id="cb47-15"><a href="#cb47-15" aria-hidden="true" tabindex="-1"></a>flag <span class="ot">&lt;-</span> <span class="fu">readPNG</span>(<span class="st">"chilean_flag.png"</span>)</span>
<span id="cb47-16"><a href="#cb47-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-17"><a href="#cb47-17" aria-hidden="true" tabindex="-1"></a><span class="co"># If the image doesn't already have an alpha channel (transparency), you can add one.</span></span>
<span id="cb47-18"><a href="#cb47-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Assuming the image is RGB, create an RGBA version by adding an alpha channel.</span></span>
<span id="cb47-19"><a href="#cb47-19" aria-hidden="true" tabindex="-1"></a>flag_with_alpha <span class="ot">&lt;-</span> <span class="fu">array</span>(<span class="dv">0</span>, <span class="at">dim =</span> <span class="fu">c</span>(<span class="fu">dim</span>(flag)[<span class="dv">1</span>], <span class="fu">dim</span>(flag)[<span class="dv">2</span>], <span class="dv">4</span>))</span>
<span id="cb47-20"><a href="#cb47-20" aria-hidden="true" tabindex="-1"></a>flag_with_alpha[,,<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>] <span class="ot">&lt;-</span> flag[,,<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>]  <span class="co"># Copy RGB channels</span></span>
<span id="cb47-21"><a href="#cb47-21" aria-hidden="true" tabindex="-1"></a>flag_with_alpha[,,<span class="dv">4</span>] <span class="ot">&lt;-</span> <span class="fl">0.2</span>  <span class="co"># Set alpha to 0.2 for transparency (adjust as needed)</span></span>
<span id="cb47-22"><a href="#cb47-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-23"><a href="#cb47-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Add the image as a background to the plot with transparency</span></span>
<span id="cb47-24"><a href="#cb47-24" aria-hidden="true" tabindex="-1"></a>newy <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> agno_nacimiento, <span class="at">y =</span> value, <span class="at">group=</span>genero, <span class="at">colour =</span> genero)) <span class="sc">+</span></span>
<span id="cb47-25"><a href="#cb47-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotation_custom</span>(<span class="fu">rasterGrob</span>(flag_with_alpha, </span>
<span id="cb47-26"><a href="#cb47-26" aria-hidden="true" tabindex="-1"></a>                               <span class="at">width =</span> <span class="fu">unit</span>(<span class="dv">1</span>, <span class="st">"npc"</span>), </span>
<span id="cb47-27"><a href="#cb47-27" aria-hidden="true" tabindex="-1"></a>                               <span class="at">height =</span> <span class="fu">unit</span>(<span class="dv">1</span>, <span class="st">"npc"</span>)),</span>
<span id="cb47-28"><a href="#cb47-28" aria-hidden="true" tabindex="-1"></a>                    <span class="sc">-</span><span class="cn">Inf</span>, <span class="cn">Inf</span>, <span class="sc">-</span><span class="cn">Inf</span>, <span class="cn">Inf</span>) <span class="sc">+</span> <span class="co"># Ensures the image covers the whole plot</span></span>
<span id="cb47-29"><a href="#cb47-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">linewidth =</span> <span class="fl">1.5</span>) <span class="sc">+</span></span>
<span id="cb47-30"><a href="#cb47-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"P(politico | genero='femenino', agno)"</span>, <span class="at">x =</span> <span class="st">"Año de nacimiento"</span>, <span class="at">colour =</span> <span class="st">"modelo"</span>) <span class="sc">+</span></span>
<span id="cb47-31"><a href="#cb47-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>( . <span class="sc">~</span> model ) <span class="sc">+</span></span>
<span id="cb47-32"><a href="#cb47-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_aaas</span>() <span class="sc">+</span> </span>
<span id="cb47-33"><a href="#cb47-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb47-34"><a href="#cb47-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">panel.background =</span> <span class="fu">element_blank</span>()) <span class="co"># Ensures a blank background so the image shows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="t_1_answers_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ol start="3" type="1">
<li>¿Cuál es el mayor efecto marginal posible de año de nacimiento para hombres y mujeres?</li>
</ol>
<p>El mayor efecto marginal siempre ocurre cuando <span class="math inline">\(p_{i}=0.5\)</span>, por tanto el mayor efecto marginal del año de nacimiento para las mujeres es <span class="math inline">\(\beta_{3}/4\)</span> y para los hombres es <span class="math inline">\((\beta_{3} + \beta_{4})/4\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>dydx_m_max <span class="ot">=</span> logit_3<span class="sc">$</span>coefficients[<span class="dv">3</span>]<span class="sc">/</span><span class="dv">4</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(dydx_m_max)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>agno_nacimiento 
   0.0006632898 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>dydx_h_max <span class="ot">=</span> (logit_3<span class="sc">$</span>coefficients[<span class="dv">3</span>] <span class="sc">+</span> logit_3<span class="sc">$</span>coefficients[<span class="dv">4</span>])<span class="sc">/</span><span class="dv">4</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(dydx_h_max)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>agno_nacimiento 
   -0.004488358 </code></pre>
</div>
</div>
<p>Para las mujeres, el mayor efecto marginal del año de nacimiento es un aumento muy pequeño y positivo de 0.066 puntos porcentuales en la probabilidad de ser política. Para los hombres, el mayor efecto marginal es negativo, aproximadamente -0.45 puntos porcentuales, lo que sugiere que a medida que avanza el año de nacimiento, la probabilidad de ser político disminuye más rápidamente en el caso de los hombres.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>