<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Trabajo 2">

<title>SOL3070 Análisis de Datos Categóricos</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="t_2_answers_files/libs/clipboard/clipboard.min.js"></script>
<script src="t_2_answers_files/libs/quarto-html/quarto.js"></script>
<script src="t_2_answers_files/libs/quarto-html/popper.min.js"></script>
<script src="t_2_answers_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="t_2_answers_files/libs/quarto-html/anchor.min.js"></script>
<link href="t_2_answers_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="t_2_answers_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="t_2_answers_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="t_2_answers_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="t_2_answers_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">SOL3070 Análisis de Datos Categóricos</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Trabajo 2 </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="información" class="level2">
<h2 class="anchored" data-anchor-id="información">Información</h2>
<ul>
<li><p>Ponderación: 20% de la nota final del curso.</p></li>
<li><p>Bonus: Responder la pregunta “bonus” NO es un requisito necesario para obtener puntaje completo. Responder incorrectamente la pregunta “bonus” no afectará negativamente la nota obtenida, pero responderla correctamente mejorará la nota obtenida en un máximo de 0.5 puntos (o en la cantidad necesaria para obtener nota máxima si la nota original fuera superior a 6.5)</p></li>
</ul>
</section>
<section id="introducción" class="level2">
<h2 class="anchored" data-anchor-id="introducción">Introducción</h2>
<p>En este trabajo se utilizarán datos extraídos de 9.303 biografías de chilenos disponibles en Wikipedia, en hasta 160 idiomas. Esta información fue recopilada como parte del proyecto de investigación ‘Social Memory about Chileans in Wikipedia’, financiado por Wikimedia Research Fund. Si utilizas estos datos, por favor cita la siguiente publicación: Beytía, P., Rojas, C. &amp; Cruz, C. (2024). Social memory about people from a country. The case of notable Chileans in Wikipedia. Wiki Workshop 2024.</p>
<p>Estos datos se emplearán para modelar la probabilidad de que una persona con biografía en Wikipedia pertenezca a una de las siguientes cuatro categorías de la vida pública: ‘Cultura &amp; Ciencia’, ‘Política’, ‘Deporte’ u ‘Otro’. Como variables predictoras se utilizarán el género y el año de nacimiento de los individuos.</p>
<p>Los datos están disponibles en el repositorio del curso para ser descargados.</p>
</section>
<section id="datos" class="level2">
<h2 class="anchored" data-anchor-id="datos">Datos</h2>
<p>Visualización rápida de la base de datos:</p>
<div class="cell" data-warnings="false">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>path <span class="ot">&lt;-</span> <span class="st">'/Users/mauricio/Library/Mobile Documents/com~apple~CloudDocs/Teaching/ISUC/2024_2_categorical_data_analysis/repo/homework/t_2_answers'</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(path)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>wiki_chileans <span class="ot">&lt;-</span>  <span class="fu">read_csv</span>(<span class="st">"wiki_chileans.csv"</span>) <span class="sc">%&gt;%</span> <span class="fu">as_tibble</span>()</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>wiki_chileans <span class="sc">%&gt;%</span> <span class="fu">glimpse</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 9,292
Columns: 4
$ person          &lt;chr&gt; "Gabriela Mistral", "Michelle Bachelet", "Isabel Allen…
$ categoria       &lt;chr&gt; "Cultura &amp; Ciencia", "Política", "Cultura &amp; Ciencia", …
$ genero          &lt;chr&gt; "femenino", "femenino", "femenino", "femenino", "femen…
$ agno_nacimiento &lt;dbl&gt; 1889, 1951, 1942, 1917, 1977, 1979, 1988, 1927, 2002, …</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co">#wiki_chileans &lt;- wiki_chileans %&gt;% </span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co">#  select(personLabel,genderLabel,category,birthyear)</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co">#wiki_chileans &lt;- wiki_chileans %&gt;%</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="co">#  mutate(category = case_when(</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="co">#    category %in% c("Arte", "Humanidades", "Educación", "Ciencia y tecnología", #"Comunicaciones" ) ~ "Cultura &amp; Ciencia",</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="co">#    category %in% c("Política", "Derecho") ~ "Política",</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="co">#    category %in% c("Deporte") ~ "Deporte",</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="co">#    TRUE ~ "Otro" # Incluye "Negocios", "Ejército y seguridad", "Otra", "Religión", #"Crimen</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="co">#  ))</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a><span class="co">#wiki_chileans &lt;- wiki_chileans %&gt;% mutate(</span></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a><span class="co">#  person = personLabel,</span></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a><span class="co">#  genero = genderLabel,</span></span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a><span class="co">#  agno_nacimiento = birthyear,</span></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a><span class="co">#  categoria = category) %&gt;%</span></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a><span class="co">#  select(person,categoria,genero,agno_nacimiento)  %&gt;%</span></span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a><span class="co">#  filter(genero != "género fluido" &amp; genero != "mujer transgénero")</span></span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a><span class="co">#write_csv(wiki_chileans, "/Users/mauricio/Library/Mobile Documents/com~apple~CloudDocs/Teaching/ISUC/2024_2_categorical_data_analysis/hw_ans/t_2_answers/wiki_chileans.csv")</span></span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(wiki_chileans)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9,292 × 4
   person            categoria         genero   agno_nacimiento
   &lt;chr&gt;             &lt;chr&gt;             &lt;chr&gt;              &lt;dbl&gt;
 1 Gabriela Mistral  Cultura &amp; Ciencia femenino            1889
 2 Michelle Bachelet Política          femenino            1951
 3 Isabel Allende    Cultura &amp; Ciencia femenino            1942
 4 Violeta Parra     Cultura &amp; Ciencia femenino            1917
 5 Nicole            Cultura &amp; Ciencia femenino            1977
 6 Coté de Pablo     Cultura &amp; Ciencia femenino            1979
 7 Camila Vallejo    Política          femenino            1988
 8 Margot Honecker   Política          femenino            1927
 9 Xiye Bastida      Política          femenino            2002
10 Leonor Varela     Cultura &amp; Ciencia femenino            1972
# ℹ 9,282 more rows</code></pre>
</div>
</div>
</section>
<section id="ejercicios" class="level2">
<h2 class="anchored" data-anchor-id="ejercicios">Ejercicios</h2>
<section id="i.-regresión-logística-multinomial" class="level3">
<h3 class="anchored" data-anchor-id="i.-regresión-logística-multinomial">I. Regresión Logística Multinomial</h3>
<ol type="1">
<li>Utiliza regresión logística multinomial para modelar la probabilidad de que una persona con biografía en Wikipedia pertenezca a una de las siguientes cuatro categorías de la vida pública: “Cultura &amp; Ciencia”, “Política”, “Deporte”, u “Otro”, en función del género y el año de nacimiento (sin interacción). Escribe la ecuación de regresión correspindiente a este modelo y presenta un <code>summary()</code> de los resultados y utiliza “Otro” como la categoría de referencia en la variable dependiente.</li>
</ol>
<p>Ecuación:</p>
<p><span class="math display">\[\log\left( \frac{P(\text{categoría }_j)}{P(\text{otro})} \right) = \beta_{0j} + \beta_{1j} \times \text{género} + \beta_{2j} \times \text{año}
\]</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>wiki_chileans<span class="sc">$</span>categoria <span class="ot">&lt;-</span> <span class="fu">factor</span>(wiki_chileans<span class="sc">$</span>categoria, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Otro"</span>,<span class="st">"Cultura &amp; Ciencia"</span>,<span class="st">"Política"</span>,<span class="st">"Deporte"</span>))</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>wiki_chileans<span class="sc">$</span>categoria <span class="ot">&lt;-</span> <span class="fu">relevel</span>(wiki_chileans<span class="sc">$</span>categoria, <span class="at">ref =</span> <span class="st">"Otro"</span>)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>mnlr_1 <span class="ot">&lt;-</span> <span class="fu">multinom</span>(categoria <span class="sc">~</span> genero <span class="sc">+</span> agno_nacimiento, <span class="at">data=</span>wiki_chileans)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># weights:  16 (9 variable)
initial  value 12873.129437 
iter  10 value 9490.704421
iter  20 value 9291.684917
iter  20 value 9291.684917
final  value 9291.684917 
converged</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mnlr_1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Call:
multinom(formula = categoria ~ genero + agno_nacimiento, data = wiki_chileans)

Coefficients:
                  (Intercept) generomasculino agno_nacimiento
Cultura &amp; Ciencia   -27.80974      -1.2184932      0.01590299
Política             -4.56006      -0.3291752      0.00312897
Deporte            -115.28419       1.2349601      0.05922854

Std. Errors:
                    (Intercept) generomasculino agno_nacimiento
Cultura &amp; Ciencia 0.00052821891      0.04005022   0.00002778268
Política          0.00047290661      0.02625119   0.00002576805
Deporte           0.00006023572      0.01134355   0.00002554355

Residual Deviance: 18583.37 
AIC: 18601.37 </code></pre>
</div>
</div>
<p>1.1 Interpreta los coeficientes asociados a <code>hombre-Política</code> y <code>agno_nacimiento-Deporte</code> en términos de log-odds.</p>
<p>El coeficiente para <code>hombre</code> en la categoría “Política” es -0.3292. Es decir, manteniendo constante el año de nacimiento, ser hombre está asociado con una disminución de 0.3292 en los log-odds de pertenecer a la categoría “Política” en lugar de “Cultura &amp; Ciencia”.</p>
<p>El coeficiente para agno_nacimiento en la categoría Deporte es 0.0592. Es decir, independiente del género, por cada año más reciente de nacimiento los log-odds de pertenecer a la categoría “Deporte” en lugar de “Cultura &amp; Ciencia” aumentan en 0.0592 unidades.</p>
<p>1.2 Expresa las ecuaciones y calcula las odds de pertenecer a la categoría “Política” de un hombre y de una mujer nacidos en el año 1950. Explica cómo estas odds se relacionan con la cantidad obtenida al exponencia el coeficiente <code>hombre-Política</code>.</p>
<ul>
<li><p>Log-odds para hombres:</p>
<p><span class="math display">\[\text{log-odds}_{\text{hombre}} = \beta_{0} + \beta_{\text{hombre}} \cdot 1 + \beta_{\text{agno}} \cdot \text{agno}\]</span></p></li>
<li><p>Log-odds para mujeres:</p>
<p><span class="math display">\[\text{log-odds}_{\text{mujer}} = \beta_{0} + \beta_{\text{hombre}} \cdot 0 + \beta_{\text{agno}} \cdot \text{agno}\]</span></p></li>
</ul>
<p>Por tanto, el ratio de odds entre hombres y mujeres se define como:</p>
<p><span class="math display">\[\text{Ratio} = \frac{\text{odds}_{\text{hombre}}}{\text{odds}_{\text{mujer}}} = \frac{e^{\text{log-odds}_{\text{hombre}}}}{e^{\text{log-odds}_{\text{mujer}}}}\]</span></p>
<p>Sustituyendo las expresiones de log-odds en la fórmula del ratio:</p>
<p><span class="math display">\[\text{Ratio} = \frac{e^{\text{log-odds}_{\text{hombre}}}}{e^{\text{log-odds}_{\text{mujer}}}} = \frac{e^{\left( \beta_{0\text{Política}} + \beta_{\text{hombre}} + \beta_{\text{agno}} \cdot \text{agno} \right)}}{e^{\left( \beta_{0\text{Política}} + \beta_{\text{agno}} \cdot \text{agno} \right)}}\]</span></p>
<p>Simplificando, los términos comunes se cancelan y obtenemos: <span class="math inline">\(\text{Ratio} = e^{\beta_{\text{hombre}}}\)</span></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Extraer los coeficientes del modelo para la categoría "Política"</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>coef_politica <span class="ot">&lt;-</span> <span class="fu">coef</span>(mnlr_1)[<span class="st">"Política"</span>, ]</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>coef_politica</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    (Intercept) generomasculino agno_nacimiento 
    -4.56006048     -0.32917524      0.00312897 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Año de nacimiento 1950</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>agno_nacimiento_1950 <span class="ot">&lt;-</span> <span class="dv">1950</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Coeficientes para la categoría "Política"</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>beta_intercept <span class="ot">&lt;-</span> coef_politica[<span class="st">"(Intercept)"</span>]</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>beta_genero <span class="ot">&lt;-</span> coef_politica[<span class="st">"generomasculino"</span>]</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>beta_agno <span class="ot">&lt;-</span> coef_politica[<span class="st">"agno_nacimiento"</span>]</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular el término del año de nacimiento para 1950</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>agno_1950_term <span class="ot">&lt;-</span> beta_agno <span class="sc">*</span> agno_nacimiento_1950</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular las odds para un hombre (genero = 1)</span></span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>log_odds_hombre <span class="ot">&lt;-</span> beta_intercept <span class="sc">+</span> beta_genero <span class="sc">*</span> <span class="dv">1</span> <span class="sc">+</span> agno_1950_term</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>odds_hombre <span class="ot">&lt;-</span> <span class="fu">exp</span>(log_odds_hombre)</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular las odds para una mujer (genero = 0)</span></span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>log_odds_mujer <span class="ot">&lt;-</span> beta_intercept <span class="sc">+</span> beta_genero <span class="sc">*</span> <span class="dv">0</span> <span class="sc">+</span> agno_1950_term</span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>odds_mujer <span class="ot">&lt;-</span> <span class="fu">exp</span>(log_odds_mujer)</span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar resultados</span></span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Odds para un hombre nacido en 1950 en la categoría 'Política':"</span>, odds_hombre, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Odds para un hombre nacido en 1950 en la categoría 'Política': 3.361056 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Odds para una mujer nacida en 1950 en la categoría 'Política':"</span>, odds_mujer, <span class="st">"</span><span class="sc">\n</span><span class="st"> </span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Odds para una mujer nacida en 1950 en la categoría 'Política': 4.671268 
 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular el ratio de odds hombre/mujer</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>ratio <span class="ot">&lt;-</span> odds_hombre <span class="sc">/</span> odds_mujer</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Ratio de odds (hombre/mujer) para la categoría 'Política':"</span>, ratio, <span class="st">"</span><span class="sc">\n</span><span class="st"> </span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Ratio de odds (hombre/mujer) para la categoría 'Política': 0.7195169 
 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular el exponencial del coeficiente del género (equivalente al ratio de odds)</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>exp_beta_genero <span class="ot">&lt;-</span> <span class="fu">exp</span>(beta_genero)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Exp(beta_genero) - Equivalente al ratio de odds:"</span>, exp_beta_genero, <span class="st">"</span><span class="sc">\n</span><span class="st"> </span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Exp(beta_genero) - Equivalente al ratio de odds: 0.7195169 
 </code></pre>
</div>
</div>
<p>1.3. Calcula la odds ratio de pertener a la categoría “Política” en vez de “Deporte” entre hombres y mujeres.</p>
<p>Para calcular la odds ratio de pertenecer a la categoría “Política” en vez de “Deporte” entre hombres y mujeres, usamos la siguiente expresión:</p>
<p><span class="math display">\[\text{Odds Ratio} = e^{\beta_{\text{hombre, Política}} - \beta_{\text{hombre, Deporte}}}\]</span></p>
<p>Sustituyendo,</p>
<p><span class="math display">\[
\text{Odds Ratio} = e^{(-0.3291752) - (1.2349601)} = e^{-1.5641353} \approx 0.209
\]</span></p>
<p>Es decir, las odds de pertenecer a la categoría “Política” en lugar de “Deporte” para hombres son aproximadamente <span class="math inline">\(0.209\)</span> veces las odds de una mujer en la misma comparación.</p>
<p>1.4 Expresa las ecuaciones y calcula la probabilidad de pertenecer a cada categoría para una mujer nacida en 1950.</p>
<p>Para cada categoría <span class="math inline">\(j\)</span>, la probabilidad de pertenecer a esa categoría se expresa como:</p>
<p><span class="math display">\[
P(\text{Categoría } j) = \frac{\exp(\beta_{0,j} + \beta_{\text{año},j} \times 1950)}{1 + \sum_{k=1}^{3} \exp(\beta_{0,k} + \beta_{\text{año},k} \times 1950)}
\]</span></p>
<p>Donde: - <span class="math inline">\(\beta_{0,j}\)</span> es el intercepto de la categoría <span class="math inline">\(j\)</span>, - <span class="math inline">\(\beta_{\text{año},j}\)</span> es el coeficiente del año de nacimiento para la categoría <span class="math inline">\(j\)</span>, - El denominador es la suma de todos los logits exponentiados de las categorías más la categoría de referencia (“Otro”).</p>
<p>Luego, para una mujer nacida en 1950:</p>
<ul>
<li>Probabilidad de “Política”:</li>
</ul>
<p><span class="math display">\[
P(\text{Política}) = \frac{\exp(\beta_{0,\text{Política}} + \beta_{\text{año,Política}} \times 1950)}{1 + \exp(\beta_{0,\text{Política}} + \beta_{\text{año,Política}} \times 1950) + \exp(\beta_{0,\text{Cultura}} + \beta_{\text{año,Cultura}} \times 1950) + \exp(\beta_{0,\text{Deporte}} + \beta_{\text{año,Deporte}} \times 1950)}
\]</span></p>
<ul>
<li>Probabilidad de “Cultura &amp; Ciencia”:</li>
</ul>
<p><span class="math display">\[
P(\text{Cultura \&amp; Ciencia}) = \frac{\exp(\beta_{0,\text{Cultura}} + \beta_{\text{año,Cultura}} \times 1950)}{1 + \exp(\beta_{0,\text{Política}} + \beta_{\text{año,Política}} \times 1950) + \exp(\beta_{0,\text{Cultura}} + \beta_{\text{año,Cultura}} \times 1950) + \exp(\beta_{0,\text{Deporte}} + \beta_{\text{año,Deporte}} \times 1950)}
\]</span></p>
<ul>
<li>Probabilidad de “Deporte”:</li>
</ul>
<p><span class="math display">\[
P(\text{Deporte}) = \frac{\exp(\beta_{0,\text{Deporte}} + \beta_{\text{año,Deporte}} \times 1950)}{1 + \exp(\beta_{0,\text{Política}} + \beta_{\text{año,Política}} \times 1950) + \exp(\beta_{0,\text{Cultura}} + \beta_{\text{año,Cultura}} \times 1950) + \exp(\beta_{0,\text{Deporte}} + \beta_{\text{año,Deporte}} \times 1950)}
\]</span></p>
<ul>
<li><strong>Probabilidad de “Otro”</strong>:</li>
</ul>
<p><span class="math display">\[
P(\text{Otro}) = \frac{1}{1 + \exp(\beta_{0,\text{Política}} + \beta_{\text{año,Política}} \times 1950) + \exp(\beta_{0,\text{Cultura}} + \beta_{\text{año,Cultura}} \times 1950) + \exp(\beta_{0,\text{Deporte}} + \beta_{\text{año,Deporte}} \times 1950)}
\]</span></p>
<p>Manualmente en <code>R</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Coeficientes </span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>coef_politica <span class="ot">&lt;-</span> <span class="fu">coef</span>(mnlr_1)[<span class="st">"Política"</span>, ]</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>coef_cultura  <span class="ot">&lt;-</span> <span class="fu">coef</span>(mnlr_1)[<span class="st">"Cultura &amp; Ciencia"</span>, ]</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>coef_deporte  <span class="ot">&lt;-</span> <span class="fu">coef</span>(mnlr_1)[<span class="st">"Deporte"</span>, ]</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Año de nacimiento 1950 para una mujer</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>agno_nacimiento_1950 <span class="ot">&lt;-</span> <span class="dv">1950</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Exponentes de los logits para cada categoría</span></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>exp_politica <span class="ot">&lt;-</span> <span class="fu">exp</span>(coef_politica[<span class="st">"(Intercept)"</span>] <span class="sc">+</span> coef_politica[<span class="st">"agno_nacimiento"</span>]<span class="sc">*</span> agno_nacimiento_1950)</span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>exp_cultura  <span class="ot">&lt;-</span> <span class="fu">exp</span>(coef_cultura[<span class="st">"(Intercept)"</span>]  <span class="sc">+</span> coef_cultura[<span class="st">"agno_nacimiento"</span>]<span class="sc">*</span> agno_nacimiento_1950)</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>exp_deporte  <span class="ot">&lt;-</span> <span class="fu">exp</span>(coef_deporte[<span class="st">"(Intercept)"</span>]  <span class="sc">+</span> coef_deporte[<span class="st">"agno_nacimiento"</span>]<span class="sc">*</span> agno_nacimiento_1950)</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Denominador</span></span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>denom <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">+</span> exp_politica <span class="sc">+</span> exp_cultura <span class="sc">+</span> exp_deporte</span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular probabilidades</span></span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a>prob_politica <span class="ot">&lt;-</span> exp_politica <span class="sc">/</span> denom</span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a>prob_cultura <span class="ot">&lt;-</span> exp_cultura <span class="sc">/</span> denom</span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a>prob_deporte <span class="ot">&lt;-</span> exp_deporte <span class="sc">/</span> denom</span>
<span id="cb19-21"><a href="#cb19-21" aria-hidden="true" tabindex="-1"></a>prob_otro <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">/</span> denom</span>
<span id="cb19-22"><a href="#cb19-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-23"><a href="#cb19-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar los resultados</span></span>
<span id="cb19-24"><a href="#cb19-24" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Probabilidad de pertenecer a 'Política':"</span>, prob_politica, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Probabilidad de pertenecer a 'Política': 0.1484534 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Probabilidad de pertenecer a 'Cultura &amp; Ciencia':"</span>, prob_cultura, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Probabilidad de pertenecer a 'Cultura &amp; Ciencia': 0.7805024 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Probabilidad de pertenecer a 'Deporte':"</span>, prob_deporte, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Probabilidad de pertenecer a 'Deporte': 0.03926408 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Probabilidad de pertenecer a 'Otro':"</span>, prob_otro, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Probabilidad de pertenecer a 'Otro': 0.03178011 </code></pre>
</div>
</div>
<p>Versión automática:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(mnlr_1, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">genero=</span><span class="st">"femenino"</span>, <span class="at">agno_nacimiento=</span><span class="dv">1950</span>), <span class="at">type=</span><span class="st">"probs"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Otro Cultura &amp; Ciencia          Política           Deporte 
       0.03178011        0.78050239        0.14845342        0.03926408 </code></pre>
</div>
</div>
<p>1.5. ¿Cuál es <em>efecto marginal</em> de año de nacimiento la probabilidad de que una mujer nacida en 1950 se encuentre en la categoría “Política”?</p>
<p>El efecto marginal del año de nacimiento sobre la probabilidad de pertenecer a la categoría “Política” para una mujer nacida en 1950 se expresa como:</p>
<p><span class="math display">\[\frac{\partial P(\text{Politica})}{\partial \text{agno\_nacimiento}} = P(\text{Politica}) \times \left( \beta_{\text{año,Poltica}} - \sum_{k} P(\text{Categoría } k) \times \beta_{\text{año},k} \right)\]</span></p>
<p>Donde: - <span class="math inline">\(P(\text{Política})\)</span> es la probabilidad de que una mujer pertenezca a la categoría “Política”,</p>
<ul>
<li><p><span class="math inline">\(\beta_{\text{año,Política}}\)</span> es el coeficiente del año de nacimiento para la categoría “Política”,</p></li>
<li><p><span class="math inline">\(P(\text{Categoría } k)\)</span> son las probabilidades de pertenecer a cada una de las categorías alternativas (“Cultura &amp; Ciencia”, “Deporte”, “Otro”),</p></li>
<li><p><span class="math inline">\(\beta_{\text{año},k}\)</span> son los coeficientes del año de nacimiento para cada una de las categorías.</p></li>
</ul>
<p>En <code>R</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Coeficientes del año de nacimiento para cada categoría</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>beta_anio_politica <span class="ot">&lt;-</span> coef_politica[<span class="st">"agno_nacimiento"</span>]</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>beta_anio_cultura <span class="ot">&lt;-</span> coef_cultura[<span class="st">"agno_nacimiento"</span>]</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>beta_anio_deporte <span class="ot">&lt;-</span> coef_deporte[<span class="st">"agno_nacimiento"</span>]</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular el efecto marginal</span></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>marginal_effect_politica <span class="ot">&lt;-</span> prob_politica <span class="sc">*</span> (beta_anio_politica <span class="sc">-</span> (prob_politica <span class="sc">*</span> beta_anio_politica <span class="sc">+</span> prob_cultura <span class="sc">*</span> beta_anio_cultura <span class="sc">+</span> prob_deporte <span class="sc">*</span> beta_anio_deporte))</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar el resultado</span></span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Efecto marginal del año de nacimiento sobre la probabilidad de estar en 'Política':"</span>, marginal_effect_politica, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Efecto marginal del año de nacimiento sobre la probabilidad de estar en 'Política': -0.00179234 </code></pre>
</div>
</div>
<p>El resultado que obtuvimos es:</p>
<p><span class="math display">\[\frac{\partial P(\text{Politica})}{\partial \text{ano_nacimiento}} \approx -0.00179\]</span></p>
<p>Esto indica que un aumento en un año de nacimiento reduce la probabilidad de pertenecer a la categoría “Política” en aproximadamente un 0.179 puntos porcentuales.</p>
<p>Implementación automática en <code>R</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">slopes</span>(mnlr_1, <span class="at">variables=</span><span class="st">"agno_nacimiento"</span>, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">genero=</span><span class="st">"femenino"</span>, <span class="at">agno_nacimiento=</span><span class="dv">1950</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
             Group  Estimate Std. Error      z Pr(&gt;|z|)     S     2.5 %
 Otro              -0.000483  0.0000203 -23.80   &lt;0.001 413.6 -0.000523
 Cultura &amp; Ciencia  0.000547  0.0000549   9.97   &lt;0.001  75.3  0.000439
 Política          -0.001792  0.0000778 -23.04   &lt;0.001 387.6 -0.001945
 Deporte            0.001729  0.0000747  23.14   &lt;0.001 391.1  0.001582
    97.5 %
 -0.000443
  0.000654
 -0.001640
  0.001875

Term: agno_nacimiento
Type:  probs 
Columns: rowid, term, group, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, predicted_lo, predicted_hi, predicted, genero, agno_nacimiento, categoria </code></pre>
</div>
</div>
<ol start="2" type="1">
<li>Usando los datos de infidelidad, estima un modelo Poisson para la tasa de infidelidad a lo largo del matrimonio.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"Ecdat"</span>)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(Fair)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>affairsdata <span class="ot">&lt;-</span> Fair <span class="sc">%&gt;%</span> <span class="fu">as_tibble</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li><p>La variable <code>nbaffairs</code> mide la cantidad de relaciones extra-matrimoniales que ha tenido una persona. La variable <code>ym</code> mide los años que una persona ha estado casada.</p></li>
<li><p>Modela la cantidad de relaciones extra-matrimoniales que ha tenido una persona como función de su genero (<code>age</code>), su felicidad en el matrimonio (<code>rate</code>) y la interacción entre ambas.</p></li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = nbaffairs ~ rate * factor(sex), family = poisson(link = log), 
    data = affairsdata, offset = log(ym))

Coefficients:
                     Estimate Std. Error z value             Pr(&gt;|z|)    
(Intercept)          -0.63898    0.12575  -5.081          0.000000375 ***
rate                 -0.31686    0.03650  -8.682 &lt; 0.0000000000000002 ***
factor(sex)male       0.32991    0.18779   1.757                0.079 .  
rate:factor(sex)male -0.08003    0.05408  -1.480                0.139    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for poisson family taken to be 1)

    Null deviance: 2828.8  on 600  degrees of freedom
Residual deviance: 2662.4  on 597  degrees of freedom
AIC: 3164.4

Number of Fisher Scoring iterations: 7</code></pre>
</div>
</div>
<p>10.1 Interpreta el efecto multiplicativo de la variable felicidad en el matrimonio sobre la tasa de infidelidad de los hombres.</p>
<p>Un aumento en una unidad de evaluación de felicidad en el matrimonio disminuye en un 33% ( <span class="math inline">\(e^{-0.31686-0.08003} - 1\)</span> ) la tasa de infidelidad de los hombres.</p>
<p>10.2 Estima la cantidad esperada de relaciones extra-matrimoniales para una mujer en un matrimonio infeliz (<code>rate</code>=2) de 20 años de duración.</p>
<p><span class="math inline">\(\mu_{i} = \theta_{i}\cdot n_{i}\)</span></p>
<p><span class="math inline">\(\mu_{i} = e^{(\beta_{0} + 2\beta_{rate})} \cdot ym_{i}\)</span></p>
<p><span class="math inline">\(\mu_{i} = e^{(-0.63898 + 2 \cdot -0.31686)} \cdot 20 = 5.601488\)</span></p>
<p>Implementación en <code>R</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(model_inf, <span class="at">newdata =</span> <span class="fu">data.frame</span>(<span class="at">rate=</span><span class="dv">2</span>, <span class="at">sex=</span><span class="st">"female"</span>, <span class="at">ym=</span><span class="dv">20</span>), <span class="at">type=</span><span class="st">"response"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
5.601511 </code></pre>
</div>
</div>
<p>10.3 Genera un gráfico como el siguiente, que muestre la cantidad esperada de relaciones extra-matrimoniales para hombres y mujeres en matrimonios de distintos niveles de felicidad (rate = 1 … 5), considerando una duración de 20 años.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="t_2_answers_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>