<!DOCTYPE html>
<html lang="en"><head>
<script src="class_7_files/libs/clipboard/clipboard.min.js"></script>
<script src="class_7_files/libs/quarto-html/tabby.min.js"></script>
<script src="class_7_files/libs/quarto-html/popper.min.js"></script>
<script src="class_7_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="class_7_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="class_7_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="class_7_files/libs/quarto-html/quarto-syntax-highlighting-de63f62b328812d8e578a4d74e282472.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.38">

  <meta name="author" content="Mauricio Bucca · Sociología UC">
  <meta name="dcterms.date" content="2026-07-23">
  <title>Análisis de Datos Categóricos (SOC3070)</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="class_7_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="class_7_files/libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="class_7_files/libs/revealjs/dist/theme/quarto-2740581606dc327e82f18f789b69d8a0.css">
  <link rel="stylesheet" href="../_shared/course.css">
  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">
  <link href="class_7_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="class_7_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="class_7_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="class_7_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="theme-boca quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" data-background-color="#003B7A" class="quarto-title-block center">
  <h1 class="title">Análisis de Datos Categóricos (SOC3070)</h1>
  <p class="subtitle">Regresión Lineal y el Modelo Lineal de Probabilidad</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Mauricio Bucca · Sociología UC 
</div>
</div>
</div>

  <p class="date">2026-07-23</p>
</section>
<section id="antes-hoy-después" class="slide level2 class-rhythm">
<h2>Antes · Hoy · Después</h2>
<div class="full-width">
<div class="content-box">
<p><strong>Antes</strong></p>
<p>estimación, MLE y funciones de pérdida.</p>
</div>
<div class="content-box-primary">
<p><strong>Hoy</strong></p>
<p>modelo lineal de probabilidad y sus límites.</p>
</div>
<div class="content-box-secondary">
<p><strong>Después</strong></p>
<p>modelos lineales generalizados.</p>
</div>
</div>
</section>
<section id="un-mismo-conjunto-de-modelos-dos-usos-distintos" class="slide level2">
<h2>Un mismo conjunto de modelos, dos usos distintos</h2>
<p>Las próximas clases (7 a 15) presentan un conjunto de modelos —LPM, GLM, logit, logit multinomial, Poisson— con un uso <strong>explicativo/inferencial</strong>: nos interesa el efecto de cada predictor, su significancia, su interpretación sustantiva.</p>
<div class="fragment">
<p>Más adelante en el curso (clases 17 a 22) <strong>no vamos a introducir modelos distintos</strong>: vamos a retomar exactamente estos mismos modelos, pero usados con un fin <strong>predictivo/clasificatorio</strong> — qué tan bien anticipan casos nuevos, no solo qué tan bien explican los datos que ya tenemos.</p>
</div>
<div class="fragment">
<p>Misma matemática, dos preguntas distintas. Vale la pena tenerlo en mente desde ahora.</p>
</div>
</section>
<section>
<section id="modelo-lineal-de-probabilidad" class="title-slide slide level1 inverse center middle" data-background-color="#E6A700">
<h1>Modelo Lineal de Probabilidad</h1>

</section>
<section id="modelos-de-regresión-para-variable-dependiente-categórica" class="slide level2">
<h2>Modelos de regresión para variable dependiente categórica</h2>
</section>
<section id="repaso-regresión-lineal" class="slide level2">
<h2>Repaso: regresión lineal</h2>
<div class="pull-left">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="allen.jpg"></p>
<figcaption>allen</figcaption>
</figure>
</div>
</div>
<div class="pull-right">
<div class="huge">
<div class="bold">
<p>Todo lo que siempre quisiste saber sobre regresión lineal (ˆ)</p>
</div>
</div>
<p>(ˆ) <span class="bold"><em>Pero nunca te atreviste a preguntar</em></span></p>
</div>
</section>
<section id="estructura-de-un-modelo-de-regresión-lineal" class="slide level2">
<h2>Estructura de un modelo de regresión lineal</h2>
<p>Un modelo de regresión lineal estándar tiene la siguiente estructura:</p>
<p><span class="math display">y_{i} = \overbrace{\beta_{0} + \beta_{1}x_{1i} + \dots \beta_{k}x_{ki}}^{\hat{y}} + e_{i}</span> donde:</p>
<div class="fragment">
<ul>
<li><span class="math inline">y</span> es la variable dependiente</li>
<li><span class="math inline">x_{1} \dots x_{k}</span> son predictores o variables independientes</li>
<li><span class="math inline">\beta_{1} \dots \beta_{k}</span> son los respectivos “efectos” de los predictores sobre <span class="math inline">y</span></li>
<li><span class="math inline">e</span> es un término de error aleatorio (“white noise”)</li>
<li><span class="math inline">\hat{y} \perp e</span></li>
</ul>
</div>
</section>
<section id="estructura-de-un-modelo-de-regresión-lineal-1" class="slide level2">
<h2>Estructura de un modelo de regresión lineal</h2>
<p>Podemos repensar el LM de la siguiente forma:</p>
<div class="fragment">
<p><span class="bold">Setup</span></p>
<ul>
<li>Tenemos <span class="math inline">n</span> observaciones (individuos) independientes: <span class="math inline">i = 1, \dots, n</span></li>
</ul>
</div>
<div class="fragment">
<ul>
<li>Para cada individuo observamos un valor en la variable dependiente <span class="math inline">y_{i}</span>, tal que <span class="math inline">y_{i} \in \mathbb{R}</span></li>
</ul>
</div>
<div class="fragment">
<ul>
<li>Estos resultados son realizaciones de variables aleatorias <span class="math inline">\text{Normal}(\mu_{i}, \sigma_{i})</span> con media y varianza desconocida: misma distribución pero parámetros (potencialmente) distintos
<ul>
<li>Notar que es imposible identificar estos parámetros individualmente ( <span class="math inline">n</span> observaciones y <span class="math inline">2n</span> parámetros)</li>
</ul></li>
</ul>
</div>
</section>
<section id="estructura-de-un-modelo-de-regresión-lineal-2" class="slide level2">
<h2>Estructura de un modelo de regresión lineal</h2>
<p>El modelo de regresión lineal estándar “resuelve” este problema de la siguiente manera <span class="math display">y_{i} \sim \text{Normal}(\mu_{i}, \sigma_{i}) \quad \quad \text{ donde}</span></p>
<div class="fragment">
<ul>
<li><span class="math inline">\mu_{i} = \beta_{0} + \beta_{1}x_{1i} + \dots \beta_{k}x_{ki}</span></li>
</ul>
</div>
<div class="fragment">
<p><span class="math inline">\quad =\mathbb{E}(y_{i} \mid x_{1}, \dots, x_{k})</span></p>
</div>
<div class="fragment">
<ul>
<li><span class="math inline">\sigma^{2}_{i} =  \sigma^{2}</span></li>
</ul>
</div>
<div class="fragment">
<p><span class="math inline">\quad =\operatorname{Var}(y_{i} \mid x_{1}, \dots, x_{k})</span></p>
</div>
<div class="fragment">
<ul>
<li><span class="math inline">x_{1}, \dots, x_{k}</span> son valores fijos, no variables aleatorias</li>
</ul>
</div>
<div class="fragment">
<ul>
<li>Todo lo anterior implica que, si <span class="math inline">(e_{i} = y_{i} - \mu_{i})</span>, entonces</li>
</ul>
</div>
<div class="fragment">
<p><span class="math inline">\quad e_{i} = \text{Normal}(\mu_{i}, \sigma) - \mu_{i} \sim  \text{Normal}(0, \sigma)</span></p>
</div>
<div class="fragment">
<p>En resumen,</p>
<div class="content-box-primary">
<p><span class="math display">\color{white}{ y_{i} \sim \text{Normal}(\mu_{i}, \sigma) \quad  \text{ o, equivalentemente: } \quad  y_{i} = \mu_{i} + \text{Normal}(0, \sigma)}</span></p>
</div>
</div>
<div class="fragment">
<p>Notar que LM describe los datos con <span class="math inline">k + 2</span> parámetros: <span class="math inline">\beta_{0}, \beta_{1}, \dots, \beta_{k}, \sigma</span></p>
</div>
</section>
<section id="estructura-de-un-modelo-de-regresión-lineal-3" class="slide level2">
<h2>Estructura de un modelo de regresión lineal</h2>
<p>Es común encontrar el modelo lineal escrito en forma matricial:</p>
<div class="pull-left">
<p><span class="math display">\boldsymbol{y} \sim \text{Normal}_{n}(\boldsymbol{X}\boldsymbol{\beta},\boldsymbol{\Sigma}) \quad \text{ donde ...}</span></p>
</div>
<div class="pull-right">
<ul>
<li><span class="math inline">\boldsymbol{y}</span> es un vector que contiene las diferentes <span class="math inline">y_{i}, \dots, y_{n}</span></li>
<li><span class="math inline">\boldsymbol{\mu} = \boldsymbol{X}\boldsymbol{\beta} = \beta_{0} + \beta_{1}\boldsymbol{x}_{1} + \dots + \beta_{k}\boldsymbol{x}_{k}</span></li>
<li><span class="math inline">\boldsymbol{\Sigma}</span> es la matriz de varianza-covarianza entre las observaciones</li>
</ul>
</div>
<div class="fragment">
<p>visualmente: <span class="math display">\begin{bmatrix}
y_{i} \\  \vdots \\ y_{n}
\end{bmatrix}_{(n,1)} \sim \text{Normal}_{n}\Bigg(  \boldsymbol{\mu} = \begin{bmatrix}
\beta_{0} + \beta_{1}x_{1i} + \dots \beta_{k}x_{ki} \\
\vdots \\ \beta_{0} + \beta_{1}x_{1n} + \dots \beta_{k}x_{kn}
\end{bmatrix}_{(n,1)} , \boldsymbol{\Sigma} = \begin{bmatrix}
    \sigma^{2}    &amp; 0      &amp; \ldots         &amp; 0      \\
    0      &amp; \sigma^{2}     &amp; \ldots         &amp; 0      \\
    \vdots &amp; \vdots &amp; \sigma^{2}   &amp; \vdots \\
    0      &amp; 0      &amp; \ldots         &amp; \sigma^{2}
\end{bmatrix}_{(n,n)}\Bigg)</span></p>
</div>
</section>
<section id="modelo-de-regresión-lineal" class="slide level2">
<h2>Modelo de regresión lineal</h2>
<p>“Ensamblemos” el modelo via Monte Carlo Simulation. “Data Generating Process” (<span class="bold">DGP</span>):</p>
<div class="fragment">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> int [1:5000] 29 19 62 6 62 90 6 83 65 76 ...</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> num [1:5000] 41.900 30.900 78.200 16.600 78.200 ...</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> num [1:5000] 44.400 37.030 81.880 9.850 81.410 ...</code></pre>
</div>
</div>
</div>
</section>
<section id="estimación-modelo-de-regresión-lineal" class="slide level2">
<h2>Estimación modelo de regresión lineal:</h2>
<div class="pull-left">
<div class="content-box-primary">
<p><span class="bold">OLS</span> <span class="math display">\color{white}{\hat{\boldsymbol{\beta}}_{OLS} = \underset{\beta}{\arg\min\ } \sum_{i=1}^{n} (y_{i} - \boldsymbol{X}_{i}'\boldsymbol{\beta})^{2} \quad \text{ donde}}</span></p>
</div>
</div>
<div class="pull-right">
<ul>
<li><span class="math inline">\boldsymbol{y}</span> es el vector <span class="math inline">y_{i}, \dots, y_{n}</span></li>
<li><span class="math inline">\boldsymbol{X}_{i}'\boldsymbol{\beta} = \beta_{0} + \beta_{1}x_{1i} + \dots + \beta_{k}x_{ki}</span></li>
</ul>
</div>
<div class="fragment">
<div class="pull-left">
<div class="content-box-primary">
<p><span class="bold">MLE</span> <span class="math display">\color{white}{\hat{\boldsymbol{\beta}}_{MLE} = \underset{\beta}{\arg\max\ } \prod_{i=1}^{n} \frac{1}{\sqrt{2\pi\sigma^{2}}} e^{- \frac{(y_{i} - \boldsymbol{X}_{i}'\boldsymbol{\beta})^{2}}{2\sigma^{2}}} \quad \text{ donde}}</span></p>
</div>
</div>
<div class="pull-right">
<ul>
<li><span class="math inline">\frac{1}{\sqrt{2\pi\sigma^{2}}} e^{- \frac{(x - \mu)^{2}}{2\sigma^{2}}}</span> es la densidad de probabilidad de una variable aleatoria <span class="math inline">X \sim \mathcal{N}(\mu,\sigma^2)</span></li>
</ul>
</div>
<div class="cell">
<style type="text/css">
.pull-right ~ * { clear: unset; }
.pull-right + * { clear: both; }
</style>
</div>
</div>
<div class="fragment">
<p>Ambos métodos producen mismos resultados en el caso de LM.</p>
</div>
</section>
<section id="modelo-de-regresión-lineal-1" class="slide level2">
<h2>Modelo de regresión lineal</h2>
<p>Ahora estimemos los parámetros de nuestro modelo via OLS</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x, data = our_data)

Residuals:
    Min      1Q  Median      3Q     Max 
-24.978  -4.644   0.035   4.642  25.185 

Coefficients:
            Estimate Std. Error t value            Pr(&gt;|t|)    
(Intercept) 10.169    0.193    52.600 &lt;0.000 ***
x            1.095    0.003   323.800 &lt;0.000 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.010 '*' 0.050 '.' 0.100 ' ' 1

Residual standard error: 6.940 on 4998 degrees of freedom
Multiple R-squared:  0.955, Adjusted R-squared:  0.954 
F-statistic: 105000.000 on 1 and 4998 DF,  p-value: &lt;0.000</code></pre>
</div>
</div>
</section>
<section id="modelo-de-regresión-lineal-2" class="slide level2">
<h2>Modelo de regresión lineal</h2>
<p>Ahora estimemos los parámetros via MLE</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = y ~ x, family = "gaussian", data = our_data)

Coefficients:
            Estimate Std. Error t value            Pr(&gt;|t|)    
(Intercept) 10.169    0.193    52.600 &lt;0.000 ***
x            1.095    0.003   323.800 &lt;0.000 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.010 '*' 0.050 '.' 0.100 ' ' 1

(Dispersion parameter for gaussian family taken to be 48.210)

    Null deviance: 5295609  on 4999  degrees of freedom
Residual deviance:  240941  on 4998  degrees of freedom
AIC: 33571

Number of Fisher Scoring iterations: 2</code></pre>
</div>
</div>
</section>
<section id="modelo-de-regresión-lineal-3" class="slide level2">
<h2>Modelo de regresión lineal</h2>
<div class="pull-left">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="class_7_files/figure-revealjs/unnamed-chunk-11-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
<div class="fragment">
<div class="pull-right">
<p>Observamos que:</p>
<ul>
<li><span class="math inline">\mathbb{E}(y_{i} \mid x = 50) = 64.9</span></li>
<li><span class="math inline">\mathbb{E}(y_{i} \mid x = 60) = 75.9</span></li>
<li>Estas “medias condicionales” no son determinísticas sino <span class="bold"><em>probabilísticas</em></span>.</li>
<li>Específicamente, sabemos que:
<ul>
<li><span class="math inline">y_{i} \mid x = 50  \sim \text{Normal}(\mu= 64.9, \sigma=7)</span></li>
<li><span class="math inline">y_{i} \mid x = 60  \sim \text{Normal}(\mu= 75.9, \sigma=7)</span></li>
</ul></li>
</ul>
</div>
</div>
</section>
<section id="modelo-de-regresión-lineal-4" class="slide level2">
<h2>Modelo de regresión lineal</h2>
<div class="pull-left">
<p>Así se ve:</p>
<ul>
<li><span class="math inline">\mathbb{E}(y_{i} \mid x = 50) = 64.9</span></li>
<li><span class="math inline">\mathbb{E}(y_{i} \mid x = 60) = 75.9</span></li>
</ul>
<p>donde: - <span class="math inline">y_{i} \mid x = 50  \sim \text{Normal}(\mu= 64.9, \sigma=7)</span> - <span class="math inline">y_{i} \mid x = 60  \sim \text{Normal}(\mu= 75.9, \sigma=7)</span></p>
</div>
<div class="pull-right">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="class_7_files/figure-revealjs/unnamed-chunk-12-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="interpretación-coeficientes-en-lm" class="slide level2">
<h2>Interpretación coeficientes en LM</h2>
<p><span class="math display">\text{Si } \quad \quad y_{i} = \overbrace{\beta_{0} + \beta_{1}x_{1i} + \dots \beta_{k}x_{ki}}^{\mathbb{E}(y_{i} \mid x_{1}, \dots, x_{k})} + \underbrace{e_i}_{\sim \text{Normal}(0,\sigma)}</span></p>
</section>
<section id="interpretación-coeficientes-en-lm-1" class="slide level2">
<h2>Interpretación coeficientes en LM</h2>
<p><span class="math display">\text{Si } \quad \quad y_{i} = \overbrace{\beta_{0} + \beta_{1}x_{1i} + \dots \beta_{k}x_{ki}}^{\mathbb{E}(y_{i} \mid x_{1}, \dots, x_{k})} + \underbrace{e_{i}}_{\text{Normal}}(0,\sigma)</span></p>
<p>Entonces decimos que el efecto de <span class="math inline">x_{k}</span> sobre <span class="math inline">y</span> es <span class="math inline">\beta_{k}</span>. ¿Qué significa?</p>
<div class="pull-left">
<p><span class="math display">\frac{\partial \mathbb{E}(y_{i} \mid x_{1}, \dots, x_{k})}{\partial x_{k}} = \beta_{k}</span></p>
</div>
<div class="pull-right">
<p>“Un cambio en <span class="math inline">\Delta</span> unidades de <span class="math inline">x_{k}</span> se traduce en un cambio en <span class="math inline">\Delta</span> <span class="math inline">\beta_{k}</span> unidades en el valor esperado de <span class="math inline">y_{i}</span>”</p>
</div>
</section>
<section id="interpretación-coeficientes-en-lm-2" class="slide level2">
<h2>Interpretación coeficientes en LM</h2>
<p>En nuestro ejemplo:</p>
<div class="pull-left">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x, data = our_data)

Coefficients:
(Intercept)            x  
       10.200          1.100  </code></pre>
</div>
</div>
</div>
<div class="pull-right">
<p>Si <code>x=50</code>, entonces <code>y</code>=</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 65.200</code></pre>
</div>
</div>
<p>Si <code>x=51</code>, entonces <code>y</code>=</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 66.300</code></pre>
</div>
</div>
<p>Por tanto, <span class="math inline">\beta</span>=</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.100</code></pre>
</div>
</div>
</div>
</section>
<section id="interpretación-coeficientes-en-lm-3" class="slide level2">
<h2>Interpretación coeficientes en LM</h2>
<p>Un ejemplo más complejo: podemos incluir interacciones y efectos no lineales</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> 'AsIs' num [1:10000] 114.063.... -6.405.... 472.901.... 36.265.... 387.721.... ...</code></pre>
</div>
</div>
</section>
<section id="interpretación-coeficientes-en-lm-4" class="slide level2">
<h2>Interpretación coeficientes en LM</h2>
<p>Estimamos los parámetros via OLS</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ I(x^2) * factor(d), data = our_data2)

Residuals:
    Min      1Q  Median      3Q     Max 
-203.600  -32.740    0.050   33.050  181.900 

Coefficients:
                  Estimate Std. Error t value            Pr(&gt;|t|)    
(Intercept)       9.376   1.049    8.930 &lt;0.000 ***
I(x^2)            0.100   0.000  429.990 &lt;0.000 ***
factor(d)1        0.135   1.484    0.090                0.930    
I(x^2):factor(d)1 0.050   0.000  151.250 &lt;0.000 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.010 '*' 0.050 '.' 0.100 ' ' 1

Residual standard error: 49.500 on 9996 degrees of freedom
Multiple R-squared:  0.984, Adjusted R-squared:  0.984 
F-statistic: 209000.000 on 3 and 9996 DF,  p-value: &lt;0.000</code></pre>
</div>
</div>
</section>
<section id="interpretación-coeficientes-en-lm-5" class="slide level2">
<h2>Interpretación coeficientes en LM</h2>
<div class="pull-left">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="class_7_files/figure-revealjs/unnamed-chunk-22-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
<div class="fragment">
<div class="pull-right">
<p><span class="math display">y_{i} = \beta_{0} + \beta_{1} x^{2}_{i} +  \beta_{2}d_{i} + \beta_{3} x^{2}_{i} \cdot d_{i} + e_{i}</span></p>
<p>Por tanto:</p>
<p><span class="math display">\begin{align}
\mathbb{E}(y_{i} \mid x, d) =
  \begin{cases}
    \beta_{0} + \beta_{1} x^{2}_{i}   &amp;\quad \text{ si } d_{i}=0 \\ \\
    (\beta_{0} + \beta_{2}) + (\beta_{1} + \beta_{3}) x^{2}_{i} &amp;\quad  \text{ si } d_{i}=1
  \end{cases}
\end{align}</span></p>
<p>Específicamente:</p>
<p><span class="math display">\begin{align}
\frac{\partial \mathbb{E}(y_{i} \mid x, d) }{\partial x} =
  \begin{cases}
    2 \beta_{1}x &amp; \quad \text{ si } d_{i}=0 \\ \\
    2(\beta_{1} + \beta_{3})x &amp; \quad \text{ si } d_{i}=1
  \end{cases}
\end{align}</span></p>
</div>
</div>
</section>
<section id="el-modelo-lineal-de-probabilidad-lpm" class="slide level2 inverse center middle" data-background-color="#E6A700">
<h2>El Modelo Lineal de Probabilidad (LPM)</h2>
</section>
<section id="el-modelo-lineal-de-probabilidad-lpm-1" class="slide level2">
<h2>El Modelo Lineal de Probabilidad (LPM)</h2>
<p><span class="bold">LMP</span> es simplemente un modelo de regresión lineal aplicado a una variable dicotómica. Un LMP estándar tiene la siguiente forma:</p>
<div class="fragment">
<p><span class="math display">y_{i} = \overbrace{\beta_{0} + \beta_{1}x_{1i} + \dots + \beta_{k}x_{ki}}^{\mathbb{E}(y_{i} \mid x_{1}, \dots, x_{k})} +  e_{i} \quad \quad \text{ donde } y_{i} \in \{0,1\}</span> Dado que <span class="math inline">y_{i} \in \{0,1\}</span>,</p>
<ul>
<li><span class="math inline">\mathbb{E}(y_{i} \mid x_{1}, \dots, x_{k}) \equiv \mathbb{P}(y_{i} =1 \mid x_{1}, \dots, x_{k})</span></li>
<li>Equivalentemente, <span class="math inline">\mu_{i} \equiv p_{i}</span> <br> <br></li>
</ul>
</div>
<div class="fragment">
<p>Por tanto, en un LPM</p>
<div class="content-box-primary">
<p><span class="math display">\color{white}{y_{i} \sim \text{Normal}(p_{i}, \sigma) \quad  \text{ o, equivalentemente: } \quad  y_{i} = p_{i} + \text{Normal}(0, \sigma)}</span></p>
</div>
</div>
</section>
<section id="lmp-en-la-práctica" class="slide level2">
<h2>LMP en la práctica</h2>
<p>Para ejemplificar el uso del LPM trabajaremos con los datos de demanda de bicicletas de <em>Capital Bikeshare</em>.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 15 × 6
   bikers high_demand demand  temp   hum weathersit
    &lt;dbl&gt;       &lt;dbl&gt; &lt;chr&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;fct&gt;     
 1     90           0 baja    0.380  0.760 clear     
 2    128           0 baja    0.400   0.760 clear     
 3    217           1 alta    0.420  0.710 clear     
 4    273           1 alta    0.520  0.390 clear     
 5    313           1 alta    0.500   0.420 clear     
 6    300           1 alta    0.460  0.510 clear     
 7    253           1 alta    0.460  0.470 clear     
 8    195           0 baja    0.440  0.510 clear     
 9    129           0 baja    0.420  0.540 clear     
10     93           0 baja    0.420  0.540 clear     
11     92           0 baja    0.420  0.540 clear     
12     71           0 baja    0.420  0.540 clear     
13     52           0 baja    0.400   0.580 clear     
14     38           0 baja    0.380  0.620 clear     
15     31           0 baja    0.360  0.660 clear     </code></pre>
</div>
</div>
</section>
<section id="lmp-en-la-práctica-1" class="slide level2">
<h2>LMP en la práctica</h2>
<p>Ajustaremos el siguiente modelo: <span class="math inline">\text{alta demanda}_{i} = \beta_{0} + \beta_{1}*\text{temp}_{i}</span>, que modela la probabilidad de que una hora sea de alta demanda como función de la temperatura (normalizada).</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = high_demand ~ temp, data = bikedata)

Residuals:
   Min     1Q Median     3Q    Max 
-0.620 -0.289 -0.132  0.120  1.057 

Coefficients:
            Estimate Std. Error t value            Pr(&gt;|t|)    
(Intercept)  -0.135     0.012   -11.700 &lt;0.000 ***
temp          0.787     0.022    35.900 &lt;0.000 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.010 '*' 0.050 '.' 0.100 ' ' 1

Residual standard error: 0.404 on 8643 degrees of freedom
Multiple R-squared:  0.130, Adjusted R-squared:  0.129 
F-statistic: 1290.000 on 1 and 8643 DF,  p-value: &lt;0.000</code></pre>
</div>
</div>
</section>
<section id="lmp-en-la-práctica-2" class="slide level2">
<h2>LMP en la práctica</h2>
<div class="pull-left">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="class_7_files/figure-revealjs/unnamed-chunk-25-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
<div class="fragment">
<div class="pull-right">
<p><span class="bold">Modelo</span> <span class="math inline">\text{alta demanda}_{i} = \beta_{0} + \beta_{1}*\text{temp}_{i}</span> Específicamente: <span class="math inline">\frac{\partial \mathbb{P}(\text{alta demanda}_{i}=1 \mid \text{ temp}) }{\partial \text{ temp}} = \beta_{1} = 0.787</span> <span class="bold">Interpretación</span>: “Un cambio en <span class="math inline">\Delta</span> unidades en la temperatura se traduce en un cambio en <span class="math inline">\Delta</span> <span class="math inline">\beta_{1}</span> unidades la probabilidad de que la hora sea de alta demanda” <span class="bold">Ejemplo</span>: Diferencia en probabilidad de alta demanda entre una hora de temperatura máxima (1) y una de temperatura mínima (0): <span class="math inline">(\beta_{0} + \beta_{1} \cdot 1) - (\beta_{0} + \beta_{1} \cdot 0) = \beta_{1} = 0.787</span></p>
</div>
</div>
</section>
<section id="lmp-en-la-práctica-3" class="slide level2">
<h2>LMP en la práctica</h2>
<div class="content-box-primary">
<p><span class="math display">\color{white}{\text{LPM asume que: } \quad y_{i} \sim \text{Normal}(p_{i}, \sigma) \quad  \text{ o, equivalentemente: } \quad  y_{i} = p_{i} + \text{Normal}(0, \sigma)}</span></p>
</div>
<p>En este caso: <span class="math display">\text{alta demanda}_{i} \sim \text{Normal}(\hat{p}_{i}= -0.135 + 0.787*\text{temp}_{i}, \hat{\sigma}=0.404)</span> donde <span class="math inline">\hat{p}_{i} \in (-0.135, 0.651)</span></p>
<div class="fragment">
<p>Hasta aquí todo bien, pero …</p>
</div>
</section>
<section id="limitaciones-del-lmp" class="slide level2">
<h2>Limitaciones del LMP</h2>
<div class="content-box-primary">
<p><span class="math display">\color{white}{\text{LPM asume que: } \quad  y_{i} \sim \text{Normal}(p_{i}, \sigma) \quad  \text{ o, equivalentemente: } \quad  y_{i} = p_{i} + \text{Normal}(0, \sigma)}</span></p>
</div>
<p><span class="bold">1) Distribución y rango</span></p>
<ul>
<li>LPM asume que las observaciones <span class="math inline">y_{i}, \dots, y_{n}</span> siguen una distribución normal, pero sabemos que no es así. <span class="math inline">y_{i} \in \{0,1\}</span>.</li>
</ul>
<div class="fragment">
<p>Derivado de lo anterior,</p>
<ul>
<li>A pesar de que <span class="math inline">y_{i} \in \{0,1\}</span>, las predicciones de un LPM no están restringidas a este rango. Teóricamente, <span class="math inline">p_{i} \in \{-\infty,\infty+\}</span>. En la práctica <span class="math inline">\hat{p}_{i}</span> puede salir de rango <span class="math inline">\{0,1\}</span>, especialmente cuando la probabilidad marginal <span class="math inline">\mathbb{P}(y=1)</span> es cercana a <span class="math inline">0</span> o <span class="math inline">1</span>.</li>
</ul>
</div>
</section>
<section id="limitaciones-del-lmp-1" class="slide level2">
<h2>Limitaciones del LMP</h2>
<p><span class="bold">1) Distribución y rango</span> - El problema no es sólo que obtener probabilidades predichas menores que 0 o mayores que 1 no tiene sentido. - Cuando esto ocurre, los coeficientes estimados por el LMP son <span class="bold">sesgados</span> e <span class="bold">inconsistentes</span> - Más aún, en muestras grandes el problema es peor: converge hacia valores erróneos - Problema especialmente serio cuando el modelo produce una proporción alta de predicciones fuera de rango</p>
<div class="pull-left">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="oaxaca1.png"></p>
<figcaption>oaxaca1</figcaption>
</figure>
</div>
</div>
<div class="pull-left">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="oaxaca2.png"></p>
<figcaption>oaxaca2</figcaption>
</figure>
</div>
</div>
</section>
<section id="paréntesis-sesgo-y-consistencia" class="slide level2">
<h2>Paréntesis: sesgo y consistencia</h2>
<p><span class="bold">Paréntesis: Sesgo (Bias) y Consistencia (Consistency) de un estimador</span></p>
<div class="fragment">
<div class="pull-left">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="unbiased_consistent.png"></p>
<figcaption>unb_cons</figcaption>
</figure>
</div>
</div>
</div>
<div class="fragment">
<div class="pull-right">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="biased_inconsistent.png"></p>
<figcaption>b_incons</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="paréntesis-sesgo-y-consistencia-1" class="slide level2">
<h2>Paréntesis: sesgo y consistencia</h2>
<p><span class="bold">Paréntesis: Sesgo (Bias) y Consistencia (Consistency) de un estimador</span></p>
<div class="fragment">
<div class="pull-left">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="biased_consistent.png"></p>
<figcaption>b_cons</figcaption>
</figure>
</div>
</div>
</div>
<div class="fragment">
<div class="pull-right">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="unbiased_inconsistent.png"></p>
<figcaption>unb_incons</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="limitaciones-del-lmp-2" class="slide level2">
<h2>Limitaciones del LMP</h2>
<div class="content-box-primary">
<p><span class="math display">\color{white}{\text{LPM asume que: } \quad  y_{i} \sim \text{Normal}(p_{i}, \sigma) \quad  \text{ o, equivalentemente: } \quad  y_{i} = p_{i} + \text{Normal}(0, \sigma)}</span></p>
</div>
<p><span class="bold">2) Observaciones con varianza heterogénea (o, errores heterocedásticos)</span></p>
<p><span class="math display">\begin{align}
  \operatorname{Var}(y_{i}) &amp;=  \sum_{\text{valores } y_{i}} (y_{i} - \mathbb{E}(y_{i}) )^{2} \cdot \mathbb{P}(y_{i}) \\
             &amp;= \sum_{\text{valores } y_{i}} (y_{i} - p_{i})^{2} \cdot \mathbb{P}(y_{i})
\end{align}</span></p>
</section>
<section id="limitaciones-del-lmp-3" class="slide level2">
<h2>Limitaciones del LMP</h2>
<div class="content-box-primary">
<p><span class="math display">\text{LPM asume que: } \quad  y_{i} \sim \text{Normal}(p_{i}, \sigma) \quad  \text{ o, equivalentemente: } \quad  y_{i} = p_{i} + \text{Normal}(0, \sigma)</span></p>
</div>
<p><span class="bold">2) Observaciones con varianza heterogenea (o, errores heterocedásticos)</span></p>
<p><span class="math display">\begin{align}
  \operatorname{Var}(y_{i}) &amp;=  \sum_{\text{valores } y_{i}} (y_{i} - \mathbb{E}(y_{i}) )^{2} \cdot \mathbb{P}(y_{i}) \\
             &amp;= \sum_{\text{valores } y_{i}} (y_{i} - p_{i})^{2} \cdot \mathbb{P}(y_{i}) \\  \\
             &amp;=   (1 - p_{i})^{2} \cdot \mathbb{P}(y_{i}=1) + (0 - p_{i})^{2} \cdot \mathbb{P}(y_{i}=0) \\
             &amp;=   (1 - p_{i})^{2}p_{i} + (0 - p_{i})^{2} (1-p_{i}) \\
             &amp;= p_{i}(1-p_{i})
\end{align}</span></p>
</section>
<section id="limitaciones-del-lmp-4" class="slide level2">
<h2>Limitaciones del LMP</h2>
<p><span class="bold">2) Observaciones con varianza heterogénea (o, errores heterocedásticos)</span></p>
<p><span class="math display">\begin{align}
  \operatorname{Var}(y_{i}) &amp;=  p_{i}(1-p_{i}) \\
                      &amp;= (\beta_{0} + \beta_{1}x_{1i} + \dots + \beta_{k}x_{ki})(1 - \beta_{0} + \beta_{1}x_{1i} + \dots + \beta_{k}x_{ki})
\end{align}</span></p>
<div class="fragment">
<p>Por tanto,</p>
<div class="content-box-primary">
<p><span class="math display">\color{white}{\text{LPM asume que: } \quad  y_{i} \sim \text{Normal}(p_{i}, \sigma) \quad  \text{ o, equivalentemente: } \quad  y_{i} = p_{i} + \text{Normal}(0, \sigma)}</span></p>
</div>
</div>
<div class="fragment">
<p>pero en realidad,</p>
<div class="content-box-secondary">
<p><span class="math display">\color{white}{y_{i} \sim \text{Normal}(p_{i}, \sigma_{i} = p_{i}(1-p_{i})) \quad  \text{ o, equivalentemente: } \quad  y_{i} = p_{i} + \text{Normal}(0, \sigma_{i} = p_{i}(1-p_{i}))}</span></p>
</div>
</div>
</section>
<section id="limitaciones-del-lmp-en-la-práctica" class="slide level2">
<h2>Limitaciones del LMP en la práctica</h2>
<p>Para ejemplificar estas limitaciones del LPM estimemos un modelo ligeramente más complejo: <span class="math inline">\text{alta demanda}_{i} = \beta_{0} + \beta_{1}*\text{temp}_{i} + \beta_{2}*\text{temp}^{2}_{i} + \sum_{j}\boldsymbol{1} \{\text{clima}=j\}\Big( \beta_{0j} + \beta_{1j} \cdot \text{temp}_{i} + \beta_{2j} \cdot \text{temp}^{2}_{i}\Big)</span></p>
</section>
<section id="limitaciones-del-lmp-en-la-práctica-1" class="slide level2">
<h2>Limitaciones del LMP en la práctica</h2>
<p><span class="math inline">\text{alta demanda}_{i} = \beta_{0} + \beta_{1}*\text{temp}_{i} + \beta_{2}*\text{temp}^{2}_{i} + \sum_{j}\boldsymbol{1} \{\text{clima}=j\}\Big( \beta_{0j} + \beta_{1j} \cdot \text{temp}_{i} + \beta_{2j} \cdot \text{temp}^{2}_{i}\Big)</span></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>                                            Estimate Std. Error t value      Pr(&gt;|t|)
(Intercept)                                 -0.099    0.029 -3.409 0.001
temp                                         0.695    0.128  5.412 0.000
factor(weathersit)cloudy/misty               0.050    0.062  0.802 0.423
factor(weathersit)light rain/snow            0.180    0.107  1.685 0.092
factor(weathersit)heavy rain/snow           -0.059    0.402 -0.148 0.883
I(temp^2)                                    0.107    0.128  0.842 0.400
temp:factor(weathersit)cloudy/misty         -0.305    0.280 -1.087 0.277
temp:factor(weathersit)light rain/snow      -1.353    0.499 -2.713 0.007
factor(weathersit)cloudy/misty:I(temp^2)     0.230    0.290  0.791 0.429
factor(weathersit)light rain/snow:I(temp^2)  1.276    0.540  2.362 0.018</code></pre>
</div>
</div>
</section>
<section id="limitaciones-del-lmp-en-la-práctica-2" class="slide level2">
<h2>Limitaciones del LMP en la práctica</h2>
<p><span class="bold">Predicciones fuera de rango, sesgo e inconsistencia</span></p>
<div class="pull-left">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="class_7_files/figure-revealjs/unnamed-chunk-26-1.png" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
<div class="fragment">
<div class="pull-right">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="class_7_files/figure-revealjs/unnamed-chunk-27-1.png" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="limitaciones-del-lmp-en-la-práctica-3" class="slide level2">
<h2>Limitaciones del LMP en la práctica</h2>
<p><span class="bold">Errores heterocedásticos</span></p>
<div class="pull-left">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="class_7_files/figure-revealjs/unnamed-chunk-28-1.png" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
<div class="fragment">
<div class="pull-right">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="class_7_files/figure-revealjs/unnamed-chunk-29-1.png" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="ventajas-del-lmp" class="slide level2">
<h2>Ventajas del LMP</h2>
<div class="fragment">
<ul>
<li>Fácil de estimar: OLS</li>
</ul>
</div>
<div class="fragment">
<ul>
<li>Fácil de interpretar: los coeficientes tienen una interpretación directa en términos de efectos parciales (marginales) sobre la <em>probabilidad</em> de éxito en la variable dependiente.
<ul>
<li>Especialmente importante cuando trabajamos con modelos complejos: interacciones, efectos no-lineales, etc.</li>
</ul></li>
</ul>
</div>
<div class="fragment">
<ul>
<li>Permite una serie de extensiones propias de cualquier LM (<span class="bold">mediación</span>, variables instrumentales, efectos fijos) que con otros modelos para datos categóricos (ej, logit) no son posibles o son muy complejas.</li>
</ul>
</div>
<div class="fragment">
<div class="pull-left">
<p>Por lo mismo, hay <span class="bold">mucho</span> interés en “rescatar” el LPM</p>
</div>
<div class="pull-right">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="rescue.jpg"></p>
<figcaption>rescue</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="al-rescate-de-lpm" class="slide level2">
<h2>Al rescate de LPM</h2>
<p><span class="bold">Problema: Observaciones con varianza heterogénea (heterocedasticidad)</span> <span class="math inline">\quad \quad \Box</span> <span class="bold">Solución: Errores Estándar “Robustos”</span></p>
</section>
<section id="al-rescate-de-lpm-1" class="slide level2">
<h2>Al rescate de LPM</h2>
<p><span class="bold">Problema: Observaciones con varianza heterogenea (heterocedásticidad)</span> <span class="math inline">\quad \quad \Box</span> <span class="bold">Solución: Errores Estándar “Robustos”</span></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
t test of coefficients:

                                            Estimate Std. Error t value             Pr(&gt;|t|)    
(Intercept)                                 -0.099    0.022   -4.570         0.000 ***
temp                                         0.695    0.118    5.900         0.000 ***
factor(weathersit)cloudy/misty               0.050    0.044    1.120              0.263    
factor(weathersit)light rain/snow            0.180    0.067    2.700              0.007 ** 
factor(weathersit)heavy rain/snow           -0.059    0.006  -10.750 &lt; 0.000 ***
I(temp^2)                                    0.107    0.128    0.840              0.402    
temp:factor(weathersit)cloudy/misty         -0.305    0.244   -1.250              0.212    
temp:factor(weathersit)light rain/snow      -1.353    0.385   -3.510              0.000 ***
factor(weathersit)cloudy/misty:I(temp^2)     0.230    0.278    0.820              0.410    
factor(weathersit)light rain/snow:I(temp^2)  1.276    0.474    2.690              0.007 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.010 '*' 0.050 '.' 0.100 ' ' 1</code></pre>
</div>
</div>
</section>
<section id="al-rescate-de-lpm-2" class="slide level2">
<h2>Al rescate de LPM</h2>
<p><span class="bold">Problema: Predicciones fuera de rango, sesgo e inconsistencia</span> <span class="math inline">\quad \quad \Box</span> <span class="bold">Solución: No hay</span></p>
<div class="fragment">
<p><span class="math inline">\quad \quad \Box</span> <span class="bold">Paleativo: “trimming”</span></p>
<div class="pull-left">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="oaxaca1.png"></p>
<figcaption>oaxaca1</figcaption>
</figure>
</div>
</div>
<div class="pull-left">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="oaxaca3.png"></p>
<figcaption>oaxaca2</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="al-rescate-de-lpm-3" class="slide level2">
<h2>Al rescate de LPM</h2>
<p><span class="bold">Problema: Predicciones fuera de rango, sesgo e inconsistencia</span> <span class="math inline">\quad \quad \Box</span> <span class="bold">Paleativo: “trimming”</span></p>
</section>
<section id="al-rescate-de-lpm-4" class="slide level2">
<h2>Al rescate de LPM</h2>
<p><span class="bold">Problema: Predicciones fuera de rango, sesgo e inconsistencia</span> <span class="math inline">\quad \quad \Box</span> <span class="bold">Paleativo: “trimming”</span></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = high_demand ~ temp * factor(weathersit) + I(temp^2) * 
    factor(weathersit), data = trimmed_sample)

Residuals:
   Min     1Q Median     3Q    Max 
-0.656 -0.278 -0.122  0.394  1.012 

Coefficients:
                                            Estimate Std. Error t value    Pr(&gt;|t|)    
(Intercept)                                  -0.124     0.034   -3.630     0.000 ***
temp                                          0.798     0.148    5.400 0.000 ***
factor(weathersit)cloudy/misty                0.069     0.068    1.020     0.310    
factor(weathersit)light rain/snow             0.206     0.109    1.880     0.060 .  
I(temp^2)                                     0.016     0.143    0.110     0.912    
temp:factor(weathersit)cloudy/misty          -0.381     0.305   -1.250     0.211    
temp:factor(weathersit)light rain/snow       -1.455     0.507   -2.870     0.004 ** 
factor(weathersit)cloudy/misty:I(temp^2)      0.297     0.312    0.950     0.342    
factor(weathersit)light rain/snow:I(temp^2)   1.367     0.548    2.500     0.013 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.010 '*' 0.050 '.' 0.100 ' ' 1

Residual standard error: 0.404 on 8506 degrees of freedom
Multiple R-squared:  0.136, Adjusted R-squared:  0.135 
F-statistic:  168 on 8 and 8506 DF,  p-value: &lt;0.000</code></pre>
</div>
</div>
</section>
<section id="al-rescate-de-lpm-5" class="slide level2">
<h2>Al rescate de LPM</h2>
<p><span class="bold">Problema: Predicciones fuera de rango, sesgo e inconsistencia</span> <span class="math inline">\quad \quad \Box</span> <span class="bold">Paleativo: “trimming”</span></p>
<div class="pull-left">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="class_7_files/figure-revealjs/unnamed-chunk-30-1.png" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
<div class="pull-right">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="class_7_files/figure-revealjs/unnamed-chunk-31-1.png" width="672"></p>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="esto-no-para-wooldridge-et-al-iterative-trimming" class="slide level2">
<h2>Esto no para …[Wooldridge et al: “iterative trimming”]</h2>
<div class="pull-left">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="lmp1.png"></p>
<figcaption>lmp1</figcaption>
</figure>
</div>
</div>
<div class="pull-right">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="lmp2.png"></p>
<figcaption>lmp2</figcaption>
</figure>
</div>
</div>
</section>
<section id="en-resumen" class="slide level2">
<h2>En resumen</h2>
<div class="fragment">
<ul>
<li>LMP tiene muchas ventajas y muchos adeptos (economistas) debido a su parsimonia</li>
<li>LMP tiene también muchos problemas</li>
</ul>
</div>
<div class="fragment">
<p>¿Son esas ventajas suficientes para contrapesar las desventajas?</p>
</div>
<div class="fragment">
<p>Depende del contexto, pero:</p>
<p><strong>Precaución:</strong> usar el LPM exige justificar el rango de predicción y corregir la inferencia por heterocedasticidad.</p>
</div>
</section>
<section id="gracias" class="slide level2 inverse center middle closing" data-background-color="#003B7A">
<h2>Gracias</h2>
<p><strong>Hasta la próxima clase</strong></p>
<p>Mauricio Bucca</p>

</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="class_7_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="class_7_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="class_7_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="class_7_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="class_7_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="class_7_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="class_7_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="class_7_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="class_7_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: false,

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1600,

        height: 900,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>