<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Cantillan, R. | Bucca, M.">
<meta name="dcterms.date" content="2024-10-15">

<title>Probabilidades predichas, efectos marginales y clasificación</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="custom.scss">
</head>

<body>

<header id="title-block-header" class="quarto-title-block default toc-left page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Probabilidades predichas, efectos marginales y clasificación</h1>
            <p class="subtitle lead">Teoría y Aplicación</p>
                      </div>
  </div>
    
  <div class="quarto-title-meta-author">
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-heading">Affiliation</div>
    
      <div class="quarto-title-meta-contents">
      <p class="author">Cantillan, R. | Bucca, M. </p>
    </div>
      <div class="quarto-title-meta-contents">
          <p class="affiliation">
              ISUC
            </p>
        </div>
      </div>

  <div class="quarto-title-meta">

        
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">10/15/24</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">En este manual</h2>
   
  <ul>
  <li><a href="#librerías" id="toc-librerías" class="nav-link active" data-scroll-target="#librerías"><span class="header-section-number">1</span> Librerías</a></li>
  <li><a href="#cargamos-datos" id="toc-cargamos-datos" class="nav-link" data-scroll-target="#cargamos-datos"><span class="header-section-number">2</span> Cargamos datos</a></li>
  <li><a href="#recodificación-y-selección-de-variables" id="toc-recodificación-y-selección-de-variables" class="nav-link" data-scroll-target="#recodificación-y-selección-de-variables"><span class="header-section-number">3</span> Recodificación y selección de variables</a></li>
  <li><a href="#modelo-de-clases-latentes" id="toc-modelo-de-clases-latentes" class="nav-link" data-scroll-target="#modelo-de-clases-latentes"><span class="header-section-number">4</span> Modelo de clases latentes</a>
  <ul class="collapse">
  <li><a href="#mejor-ajuste" id="toc-mejor-ajuste" class="nav-link" data-scroll-target="#mejor-ajuste"><span class="header-section-number">4.1</span> Mejor ajuste</a></li>
  </ul></li>
  <li><a href="#modelo-de-regresión-lógistica" id="toc-modelo-de-regresión-lógistica" class="nav-link" data-scroll-target="#modelo-de-regresión-lógistica"><span class="header-section-number">5</span> Modelo de regresión lógistica</a></li>
  <li><a href="#modelo-1" id="toc-modelo-1" class="nav-link" data-scroll-target="#modelo-1"><span class="header-section-number">6</span> Modelo 1</a></li>
  <li><a href="#probabilidades-predichas" id="toc-probabilidades-predichas" class="nav-link" data-scroll-target="#probabilidades-predichas"><span class="header-section-number">7</span> Probabilidades Predichas</a></li>
  <li><a href="#efectos-marginales" id="toc-efectos-marginales" class="nav-link" data-scroll-target="#efectos-marginales"><span class="header-section-number">8</span> Efectos Marginales</a></li>
  <li><a href="#principales-diferencias" id="toc-principales-diferencias" class="nav-link" data-scroll-target="#principales-diferencias"><span class="header-section-number">9</span> Principales Diferencias</a></li>
  <li><a href="#ejemplo-numérico" id="toc-ejemplo-numérico" class="nav-link" data-scroll-target="#ejemplo-numérico"><span class="header-section-number">10</span> Ejemplo Numérico</a></li>
  <li><a href="#aplicación-al-modelo-de-clases-latentes" id="toc-aplicación-al-modelo-de-clases-latentes" class="nav-link" data-scroll-target="#aplicación-al-modelo-de-clases-latentes"><span class="header-section-number">11</span> Aplicación al Modelo de Clases Latentes</a>
  <ul class="collapse">
  <li><a href="#cálculo-probabilidades-predichas" id="toc-cálculo-probabilidades-predichas" class="nav-link" data-scroll-target="#cálculo-probabilidades-predichas"><span class="header-section-number">11.1</span> Cálculo probabilidades predichas</a></li>
  <li><a href="#cálculo-efectos-marginales" id="toc-cálculo-efectos-marginales" class="nav-link" data-scroll-target="#cálculo-efectos-marginales"><span class="header-section-number">11.2</span> Cálculo efectos marginales</a></li>
  </ul></li>
  <li><a href="#clasificación" id="toc-clasificación" class="nav-link" data-scroll-target="#clasificación"><span class="header-section-number">12</span> Clasificación</a>
  <ul class="collapse">
  <li><a href="#interpretación" id="toc-interpretación" class="nav-link" data-scroll-target="#interpretación"><span class="header-section-number">12.1</span> Interpretación</a></li>
  <li><a href="#decisiones-y-consideraciones" id="toc-decisiones-y-consideraciones" class="nav-link" data-scroll-target="#decisiones-y-consideraciones"><span class="header-section-number">12.2</span> Decisiones y Consideraciones</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
</div>
<main class="content quarto-banner-title-block" id="quarto-document-content">




<section id="librerías" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="librerías"><span class="header-section-number">1</span> Librerías</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="co"># librerías </span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidymodels)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gtsummary)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(marginaleffects)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(poLCA)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(nnet)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(httr)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(utils)</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(margins)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("pROC")</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pROC)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="co">#install.packages("ROSE")</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ROSE)</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(reshape2)</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="cargamos-datos" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="cargamos-datos"><span class="header-section-number">2</span> Cargamos datos</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="co">#ELSOC 2018</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>url <span class="ot">&lt;-</span> <span class="st">"https://github.com/rcantillan/ricantillan.rbind.io/raw/main/dat/ELSOC/ELSOC_W03_v2.00_R.RData"</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>response <span class="ot">&lt;-</span> <span class="fu">GET</span>(url)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>local_path <span class="ot">&lt;-</span> <span class="st">"ELSOC_W03_v2.00_R.RData"</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="fu">writeBin</span>(response<span class="sc">$</span>content, local_path)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"ELSOC_W03_v2.00_R.RData"</span>) </span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="recodificación-y-selección-de-variables" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="recodificación-y-selección-de-variables"><span class="header-section-number">3</span> Recodificación y selección de variables</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co"># recod, and select </span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>a<span class="ot">&lt;-</span>elsoc_2018<span class="sc">%&gt;%</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="co">#mutate_at(vars(matches("c12")), ~ifelse(. &gt; 1, 1, 2)) %&gt;% </span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span> (<span class="at">conf_gral   =</span> <span class="fu">case_when</span>(c02 <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> <span class="dv">1</span>,  </span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>                                         c02 <span class="sc">==</span> <span class="dv">2</span> <span class="sc">~</span> <span class="dv">0</span>, </span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>                                         c02 <span class="sc">==</span> <span class="dv">3</span> <span class="sc">~</span> <span class="dv">0</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>  <span class="co">#dplyr::mutate (extranjero  = case_when(m45 %in% 1 ~ 0,</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>  <span class="co">#                                       m45 %in% 2 :8 ~ 1)) %&gt;% </span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span> (<span class="at">mujer       =</span> <span class="fu">case_when</span>(m0_sexo <span class="sc">==</span> <span class="dv">1</span> <span class="sc">~</span> <span class="dv">0</span>,</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>                                         m0_sexo <span class="sc">==</span> <span class="dv">2</span> <span class="sc">~</span> <span class="dv">1</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span> (<span class="at">edad        =</span> <span class="fu">case_when</span>(m0_edad <span class="sc">%in%</span> <span class="dv">18</span><span class="sc">:</span><span class="dv">24</span> <span class="sc">~</span> <span class="st">"18_24"</span>,</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>                                         m0_edad <span class="sc">%in%</span> <span class="dv">25</span><span class="sc">:</span><span class="dv">34</span> <span class="sc">~</span> <span class="st">"25_34"</span>,</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>                                         m0_edad <span class="sc">%in%</span> <span class="dv">35</span><span class="sc">:</span><span class="dv">44</span> <span class="sc">~</span> <span class="st">"35_44"</span>,</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>                                         m0_edad <span class="sc">%in%</span> <span class="dv">45</span><span class="sc">:</span><span class="dv">54</span> <span class="sc">~</span> <span class="st">"45_54"</span>,</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>                                         m0_edad <span class="sc">%in%</span> <span class="dv">55</span><span class="sc">:</span><span class="dv">64</span> <span class="sc">~</span> <span class="st">"55_64"</span>, </span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>                                         m0_edad <span class="sc">%in%</span> <span class="dv">65</span><span class="sc">:</span><span class="dv">88</span> <span class="sc">~</span> <span class="st">"65"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span> (<span class="at">nivel_educ  =</span> <span class="fu">case_when</span>(m01 <span class="sc">%in%</span> <span class="dv">1</span> <span class="sc">:</span><span class="dv">3</span> <span class="sc">~</span> <span class="st">"básica"</span>,</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>                                         m01 <span class="sc">%in%</span> <span class="dv">4</span> <span class="sc">:</span><span class="dv">5</span> <span class="sc">~</span> <span class="st">"media"</span>,</span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>                                         m01 <span class="sc">%in%</span> <span class="dv">6</span> <span class="sc">:</span><span class="dv">7</span> <span class="sc">~</span> <span class="st">"técnica"</span>,</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>                                         m01 <span class="sc">%in%</span> <span class="dv">8</span> <span class="sc">:</span><span class="dv">10</span> <span class="sc">~</span> <span class="st">"univers"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">matches</span>(<span class="st">"c12_"</span>), </span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>                <span class="sc">~</span><span class="fu">case_when</span>(</span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>                  . <span class="sc">%in%</span> <span class="fu">c</span>(<span class="sc">-</span><span class="dv">999</span>, <span class="sc">-</span><span class="dv">888</span>) <span class="sc">~</span> <span class="cn">NA_real_</span>,  <span class="co"># No Responde y No Sabe = NA</span></span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>                  . <span class="sc">==</span> <span class="dv">3</span> <span class="sc">~</span> <span class="dv">2</span>,  <span class="co"># Si es mayor que 1 (es decir, 2 o 3), asigna 1</span></span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a>                  <span class="cn">TRUE</span> <span class="sc">~</span> <span class="dv">1</span>  <span class="co"># Para el resto (1), asigna 2</span></span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a>                ))) <span class="sc">%&gt;%</span> </span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(idencuesta, mujer, edad, nivel_educ, c12_01<span class="sc">:</span>c12_09, conf_gral)</span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a><span class="co">#elsoc_2018$c02</span></span>
<span id="cb3-31"><a href="#cb3-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-32"><a href="#cb3-32" aria-hidden="true" tabindex="-1"></a><span class="co"># set NA</span></span>
<span id="cb3-33"><a href="#cb3-33" aria-hidden="true" tabindex="-1"></a>a[a<span class="sc">==</span><span class="st">"-999"</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb3-34"><a href="#cb3-34" aria-hidden="true" tabindex="-1"></a>a[a<span class="sc">==</span><span class="st">"-888"</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb3-35"><a href="#cb3-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-36"><a href="#cb3-36" aria-hidden="true" tabindex="-1"></a><span class="co"># delete NA in covariable</span></span>
<span id="cb3-37"><a href="#cb3-37" aria-hidden="true" tabindex="-1"></a>a<span class="ot">&lt;-</span>a <span class="sc">%&gt;%</span> <span class="fu">drop_na</span>(mujer, edad, nivel_educ, c12_01<span class="sc">:</span>c12_09)</span>
<span id="cb3-38"><a href="#cb3-38" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="modelo-de-clases-latentes" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="modelo-de-clases-latentes"><span class="header-section-number">4</span> Modelo de clases latentes</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, message = FALSE}</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="co"># usamos poLCA para realizar la clasificación </span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>f <span class="ot">&lt;-</span> <span class="fu">cbind</span>(c12_01, c12_02, c12_03, c12_04, c12_05,</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>            c12_06, c12_07, c12_08, c12_09) <span class="sc">~</span> <span class="cn">NULL</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="co"># generamos los modelos de clases latentes</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>lca1 <span class="ot">&lt;-</span> <span class="fu">poLCA</span>(f,a,<span class="at">nclass=</span><span class="dv">1</span>,<span class="at">graphs=</span>F)</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>lca2 <span class="ot">&lt;-</span> <span class="fu">poLCA</span>(f,a,<span class="at">nclass=</span><span class="dv">2</span>,<span class="at">graphs=</span>F)</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>lca3 <span class="ot">&lt;-</span> <span class="fu">poLCA</span>(f,a,<span class="at">nclass=</span><span class="dv">3</span>,<span class="at">graphs=</span>F)</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>lca4 <span class="ot">&lt;-</span> <span class="fu">poLCA</span>(f,a,<span class="at">nclass=</span><span class="dv">4</span>,<span class="at">graphs=</span>F)  </span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>lca5 <span class="ot">&lt;-</span> <span class="fu">poLCA</span>(f,a,<span class="at">nclass=</span><span class="dv">5</span>,<span class="at">graphs=</span>F)  </span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>lca6 <span class="ot">&lt;-</span> <span class="fu">poLCA</span>(f,a,<span class="at">nclass=</span><span class="dv">6</span>,<span class="at">graphs=</span>F)  </span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a><span class="do">##  Estadísticos de ajuste (todos los modelos)</span></span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>AIC<span class="fl">.1</span> <span class="ot">&lt;-</span><span class="fu">as.numeric</span>(lca1<span class="sc">$</span>aic)</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>AIC<span class="fl">.2</span> <span class="ot">&lt;-</span><span class="fu">as.numeric</span>(lca2<span class="sc">$</span>aic)</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>AIC<span class="fl">.3</span> <span class="ot">&lt;-</span><span class="fu">as.numeric</span>(lca3<span class="sc">$</span>aic)</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>AIC<span class="fl">.4</span> <span class="ot">&lt;-</span><span class="fu">as.numeric</span>(lca4<span class="sc">$</span>aic)</span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>AIC<span class="fl">.5</span> <span class="ot">&lt;-</span><span class="fu">as.numeric</span>(lca5<span class="sc">$</span>aic)</span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>AIC<span class="fl">.6</span> <span class="ot">&lt;-</span><span class="fu">as.numeric</span>(lca6<span class="sc">$</span>aic)</span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>BIC<span class="fl">.1</span> <span class="ot">&lt;-</span><span class="fu">as.numeric</span>(lca1<span class="sc">$</span>bic)</span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a>BIC<span class="fl">.2</span> <span class="ot">&lt;-</span><span class="fu">as.numeric</span>(lca2<span class="sc">$</span>bic)</span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a>BIC<span class="fl">.3</span> <span class="ot">&lt;-</span><span class="fu">as.numeric</span>(lca3<span class="sc">$</span>bic)</span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a>BIC<span class="fl">.4</span> <span class="ot">&lt;-</span><span class="fu">as.numeric</span>(lca4<span class="sc">$</span>bic)</span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a>BIC<span class="fl">.5</span> <span class="ot">&lt;-</span><span class="fu">as.numeric</span>(lca5<span class="sc">$</span>bic)</span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a>BIC<span class="fl">.6</span> <span class="ot">&lt;-</span><span class="fu">as.numeric</span>(lca6<span class="sc">$</span>bic)</span>
<span id="cb4-29"><a href="#cb4-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-30"><a href="#cb4-30" aria-hidden="true" tabindex="-1"></a>llik<span class="fl">.1</span> <span class="ot">&lt;-</span><span class="fu">as.numeric</span>(lca1<span class="sc">$</span>llik)</span>
<span id="cb4-31"><a href="#cb4-31" aria-hidden="true" tabindex="-1"></a>llik<span class="fl">.2</span> <span class="ot">&lt;-</span><span class="fu">as.numeric</span>(lca2<span class="sc">$</span>llik)</span>
<span id="cb4-32"><a href="#cb4-32" aria-hidden="true" tabindex="-1"></a>llik<span class="fl">.3</span> <span class="ot">&lt;-</span><span class="fu">as.numeric</span>(lca3<span class="sc">$</span>llik)</span>
<span id="cb4-33"><a href="#cb4-33" aria-hidden="true" tabindex="-1"></a>llik<span class="fl">.4</span> <span class="ot">&lt;-</span><span class="fu">as.numeric</span>(lca4<span class="sc">$</span>llik)</span>
<span id="cb4-34"><a href="#cb4-34" aria-hidden="true" tabindex="-1"></a>llik<span class="fl">.5</span> <span class="ot">&lt;-</span><span class="fu">as.numeric</span>(lca5<span class="sc">$</span>llik)</span>
<span id="cb4-35"><a href="#cb4-35" aria-hidden="true" tabindex="-1"></a>llik<span class="fl">.6</span> <span class="ot">&lt;-</span><span class="fu">as.numeric</span>(lca6<span class="sc">$</span>llik)</span>
<span id="cb4-36"><a href="#cb4-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-37"><a href="#cb4-37" aria-hidden="true" tabindex="-1"></a>chisq<span class="fl">.1</span> <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(lca1<span class="sc">$</span>Chisq)</span>
<span id="cb4-38"><a href="#cb4-38" aria-hidden="true" tabindex="-1"></a>chisq<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(lca2<span class="sc">$</span>Chisq)</span>
<span id="cb4-39"><a href="#cb4-39" aria-hidden="true" tabindex="-1"></a>chisq<span class="fl">.3</span> <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(lca3<span class="sc">$</span>Chisq)</span>
<span id="cb4-40"><a href="#cb4-40" aria-hidden="true" tabindex="-1"></a>chisq<span class="fl">.4</span> <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(lca4<span class="sc">$</span>Chisq)</span>
<span id="cb4-41"><a href="#cb4-41" aria-hidden="true" tabindex="-1"></a>chisq<span class="fl">.5</span> <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(lca5<span class="sc">$</span>Chisq)</span>
<span id="cb4-42"><a href="#cb4-42" aria-hidden="true" tabindex="-1"></a>chisq<span class="fl">.6</span> <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(lca6<span class="sc">$</span>Chisq)</span>
<span id="cb4-43"><a href="#cb4-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-44"><a href="#cb4-44" aria-hidden="true" tabindex="-1"></a>G<span class="fl">.1</span> <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(lca1<span class="sc">$</span>Gsq)</span>
<span id="cb4-45"><a href="#cb4-45" aria-hidden="true" tabindex="-1"></a>G<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(lca2<span class="sc">$</span>Gsq)</span>
<span id="cb4-46"><a href="#cb4-46" aria-hidden="true" tabindex="-1"></a>G<span class="fl">.3</span> <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(lca3<span class="sc">$</span>Gsq)</span>
<span id="cb4-47"><a href="#cb4-47" aria-hidden="true" tabindex="-1"></a>G<span class="fl">.4</span> <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(lca4<span class="sc">$</span>Gsq)</span>
<span id="cb4-48"><a href="#cb4-48" aria-hidden="true" tabindex="-1"></a>G<span class="fl">.5</span> <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(lca5<span class="sc">$</span>Gsq)</span>
<span id="cb4-49"><a href="#cb4-49" aria-hidden="true" tabindex="-1"></a>G<span class="fl">.6</span> <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(lca6<span class="sc">$</span>Gsq)</span>
<span id="cb4-50"><a href="#cb4-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-51"><a href="#cb4-51" aria-hidden="true" tabindex="-1"></a>n.obs1 <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(lca1<span class="sc">$</span>Nobs)</span>
<span id="cb4-52"><a href="#cb4-52" aria-hidden="true" tabindex="-1"></a>n.obs2 <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(lca2<span class="sc">$</span>Nobs)</span>
<span id="cb4-53"><a href="#cb4-53" aria-hidden="true" tabindex="-1"></a>n.obs3 <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(lca3<span class="sc">$</span>Nobs)</span>
<span id="cb4-54"><a href="#cb4-54" aria-hidden="true" tabindex="-1"></a>n.obs4 <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(lca4<span class="sc">$</span>Nobs)</span>
<span id="cb4-55"><a href="#cb4-55" aria-hidden="true" tabindex="-1"></a>n.obs5 <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(lca5<span class="sc">$</span>Nobs)</span>
<span id="cb4-56"><a href="#cb4-56" aria-hidden="true" tabindex="-1"></a>n.obs6 <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(lca6<span class="sc">$</span>Nobs)</span>
<span id="cb4-57"><a href="#cb4-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-58"><a href="#cb4-58" aria-hidden="true" tabindex="-1"></a><span class="co">#Creación de Vectores para TABLA DE COMPARACIÓN</span></span>
<span id="cb4-59"><a href="#cb4-59" aria-hidden="true" tabindex="-1"></a>AIC <span class="ot">&lt;-</span> <span class="fu">c</span>(AIC<span class="fl">.1</span>,AIC<span class="fl">.2</span>,AIC<span class="fl">.3</span>,AIC<span class="fl">.4</span>,AIC<span class="fl">.5</span>,AIC<span class="fl">.6</span>)</span>
<span id="cb4-60"><a href="#cb4-60" aria-hidden="true" tabindex="-1"></a>BIC <span class="ot">&lt;-</span> <span class="fu">c</span>(BIC<span class="fl">.1</span>,BIC<span class="fl">.2</span>,BIC<span class="fl">.3</span>,BIC<span class="fl">.4</span>,BIC<span class="fl">.5</span>,BIC<span class="fl">.6</span>)</span>
<span id="cb4-61"><a href="#cb4-61" aria-hidden="true" tabindex="-1"></a>llik <span class="ot">&lt;-</span> <span class="fu">c</span>(llik<span class="fl">.1</span>,llik<span class="fl">.2</span>,llik<span class="fl">.3</span>,llik<span class="fl">.4</span>,llik<span class="fl">.5</span>,llik<span class="fl">.6</span>)</span>
<span id="cb4-62"><a href="#cb4-62" aria-hidden="true" tabindex="-1"></a>chi.cuadrado <span class="ot">&lt;-</span> <span class="fu">c</span>(chisq<span class="fl">.1</span>,chisq<span class="fl">.2</span>,chisq<span class="fl">.3</span>,chisq<span class="fl">.4</span>,chisq<span class="fl">.5</span>,chisq<span class="fl">.6</span>)</span>
<span id="cb4-63"><a href="#cb4-63" aria-hidden="true" tabindex="-1"></a>G2 <span class="ot">&lt;-</span> <span class="fu">c</span>(G<span class="fl">.1</span>,G<span class="fl">.2</span>,G<span class="fl">.3</span>,G<span class="fl">.4</span>,G<span class="fl">.5</span>,G<span class="fl">.6</span>)</span>
<span id="cb4-64"><a href="#cb4-64" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="fu">c</span>(n.obs1,n.obs2,n.obs3,n.obs4,n.obs5,n.obs6)</span>
<span id="cb4-65"><a href="#cb4-65" aria-hidden="true" tabindex="-1"></a>Modelos <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"1 clase"</span>, <span class="st">"2 clases"</span>, <span class="st">"3 clases"</span>, <span class="st">"4 clases"</span>, <span class="st">"5 clases"</span>,<span class="st">"6 clases"</span>)</span>
<span id="cb4-66"><a href="#cb4-66" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Conditional item response (column) probabilities,
 by outcome variable, for each class (row) 
 
$c12_01
           Pr(1)  Pr(2)
class 1:  0.8019 0.1981

$c12_02
           Pr(1)  Pr(2)
class 1:  0.8098 0.1902

$c12_03
          Pr(1) Pr(2)
class 1:  0.981 0.019

$c12_04
           Pr(1)  Pr(2)
class 1:  0.9322 0.0678

$c12_05
           Pr(1)  Pr(2)
class 1:  0.9581 0.0419

$c12_06
           Pr(1)  Pr(2)
class 1:  0.9181 0.0819

$c12_07
           Pr(1)  Pr(2)
class 1:  0.8999 0.1001

$c12_08
           Pr(1)  Pr(2)
class 1:  0.9712 0.0288

$c12_09
           Pr(1)  Pr(2)
class 1:  0.9619 0.0381

Estimated class population shares 
 1 
 
Predicted class memberships (by modal posterior prob.) 
 1 
 
========================================================= 
Fit for 1 latent classes: 
========================================================= 
number of observations: 3675 
number of estimated parameters: 9 
residual degrees of freedom: 502 
maximum log-likelihood: -8826.037 
 
AIC(1): 17670.07
BIC(1): 17725.96
G^2(1): 870.7513 (Likelihood ratio/deviance statistic) 
X^2(1): 15056988 (Chi-square goodness of fit) 
 
Conditional item response (column) probabilities,
 by outcome variable, for each class (row) 
 
$c12_01
           Pr(1)  Pr(2)
class 1:  0.8516 0.1484
class 2:  0.6138 0.3862

$c12_02
           Pr(1)  Pr(2)
class 1:  0.8536 0.1464
class 2:  0.6442 0.3558

$c12_03
           Pr(1)  Pr(2)
class 1:  0.9979 0.0021
class 2:  0.9167 0.0833

$c12_04
           Pr(1)  Pr(2)
class 1:  0.9615 0.0385
class 2:  0.8216 0.1784

$c12_05
           Pr(1)  Pr(2)
class 1:  0.9929 0.0071
class 2:  0.8262 0.1738

$c12_06
           Pr(1)  Pr(2)
class 1:  0.9799 0.0201
class 2:  0.6843 0.3157

$c12_07
           Pr(1)  Pr(2)
class 1:  0.9277 0.0723
class 2:  0.7946 0.2054

$c12_08
           Pr(1)  Pr(2)
class 1:  0.9872 0.0128
class 2:  0.9105 0.0895

$c12_09
           Pr(1)  Pr(2)
class 1:  0.9769 0.0231
class 2:  0.9053 0.0947

Estimated class population shares 
 0.791 0.209 
 
Predicted class memberships (by modal posterior prob.) 
 0.855 0.145 
 
========================================================= 
Fit for 2 latent classes: 
========================================================= 
number of observations: 3675 
number of estimated parameters: 19 
residual degrees of freedom: 492 
maximum log-likelihood: -8629.254 
 
AIC(2): 17296.51
BIC(2): 17414.48
G^2(2): 477.1844 (Likelihood ratio/deviance statistic) 
X^2(2): 8181.793 (Chi-square goodness of fit) 
 
Conditional item response (column) probabilities,
 by outcome variable, for each class (row) 
 
$c12_01
           Pr(1)  Pr(2)
class 1:  0.6836 0.3164
class 2:  0.9232 0.0768
class 3:  0.5691 0.4309

$c12_02
           Pr(1)  Pr(2)
class 1:  0.7194 0.2806
class 2:  0.9373 0.0627
class 3:  0.5498 0.4502

$c12_03
           Pr(1)  Pr(2)
class 1:  0.8765 0.1235
class 2:  0.9973 0.0027
class 3:  0.9897 0.0103

$c12_04
           Pr(1)  Pr(2)
class 1:  0.7225 0.2775
class 2:  0.9525 0.0475
class 3:  0.9795 0.0205

$c12_05
           Pr(1)  Pr(2)
class 1:  0.7060 0.2940
class 2:  0.9887 0.0113
class 3:  1.0000 0.0000

$c12_06
           Pr(1)  Pr(2)
class 1:  0.6619 0.3381
class 2:  0.9881 0.0119
class 3:  0.8688 0.1312

$c12_07
           Pr(1)  Pr(2)
class 1:  0.7174 0.2826
class 2:  0.9201 0.0799
class 3:  0.9347 0.0653

$c12_08
           Pr(1)  Pr(2)
class 1:  0.8743 0.1257
class 2:  0.9855 0.0145
class 3:  0.9812 0.0188

$c12_09
           Pr(1)  Pr(2)
class 1:  0.8846 0.1154
class 2:  0.9780 0.0220
class 3:  0.9590 0.0410

Estimated class population shares 
 0.1186 0.619 0.2623 
 
Predicted class memberships (by modal posterior prob.) 
 0.0732 0.6335 0.2933 
 
========================================================= 
Fit for 3 latent classes: 
========================================================= 
number of observations: 3675 
number of estimated parameters: 29 
residual degrees of freedom: 482 
maximum log-likelihood: -8567.52 
 
AIC(3): 17193.04
BIC(3): 17373.11
G^2(3): 353.7162 (Likelihood ratio/deviance statistic) 
X^2(3): 2524.807 (Chi-square goodness of fit) 
 
ALERT: iterations finished, MAXIMUM LIKELIHOOD NOT FOUND 
 
Conditional item response (column) probabilities,
 by outcome variable, for each class (row) 
 
$c12_01
           Pr(1)  Pr(2)
class 1:  0.5897 0.4103
class 2:  0.9497 0.0503
class 3:  0.7195 0.2805
class 4:  0.6751 0.3249

$c12_02
           Pr(1)  Pr(2)
class 1:  0.6146 0.3854
class 2:  0.9451 0.0549
class 3:  0.7412 0.2588
class 4:  0.6772 0.3228

$c12_03
           Pr(1)  Pr(2)
class 1:  0.9838 0.0162
class 2:  0.9985 0.0015
class 3:  0.8908 0.1092
class 4:  0.8239 0.1761

$c12_04
           Pr(1)  Pr(2)
class 1:  0.9697 0.0303
class 2:  0.9555 0.0445
class 3:  0.6679 0.3321
class 4:  0.8232 0.1768

$c12_05
           Pr(1)  Pr(2)
class 1:  1.0000 0.0000
class 2:  0.9920 0.0080
class 3:  0.6213 0.3787
class 4:  0.7916 0.2084

$c12_06
           Pr(1)  Pr(2)
class 1:  0.8700 0.1300
class 2:  0.9940 0.0060
class 3:  0.7039 0.2961
class 4:  0.5322 0.4678

$c12_07
           Pr(1)  Pr(2)
class 1:  0.9192 0.0808
class 2:  0.9212 0.0788
class 3:  0.7952 0.2048
class 4:  0.3550 0.6450

$c12_08
           Pr(1)  Pr(2)
class 1:  0.9764 0.0236
class 2:  0.9853 0.0147
class 3:  1.0000 0.0000
class 4:  0.2308 0.7692

$c12_09
           Pr(1)  Pr(2)
class 1:  0.9569 0.0431
class 2:  0.9789 0.0211
class 3:  0.9108 0.0892
class 4:  0.7727 0.2273

Estimated class population shares 
 0.3405 0.5531 0.09 0.0165 
 
Predicted class memberships (by modal posterior prob.) 
 0.3189 0.6109 0.0558 0.0144 
 
========================================================= 
Fit for 4 latent classes: 
========================================================= 
number of observations: 3675 
number of estimated parameters: 39 
residual degrees of freedom: 472 
maximum log-likelihood: -8547.141 
 
AIC(4): 17172.28
BIC(4): 17414.44
G^2(4): 312.9582 (Likelihood ratio/deviance statistic) 
X^2(4): 944.5943 (Chi-square goodness of fit) 
 
ALERT: iterations finished, MAXIMUM LIKELIHOOD NOT FOUND 
 
Conditional item response (column) probabilities,
 by outcome variable, for each class (row) 
 
$c12_01
           Pr(1)  Pr(2)
class 1:  0.7399 0.2601
class 2:  0.6572 0.3428
class 3:  0.5531 0.4469
class 4:  0.6372 0.3628
class 5:  0.8916 0.1084

$c12_02
           Pr(1)  Pr(2)
class 1:  0.7072 0.2928
class 2:  0.7775 0.2225
class 3:  0.0983 0.9017
class 4:  0.5819 0.4181
class 5:  0.9379 0.0621

$c12_03
           Pr(1)  Pr(2)
class 1:  0.8863 0.1137
class 2:  0.9329 0.0671
class 3:  1.0000 0.0000
class 4:  0.8554 0.1446
class 5:  1.0000 0.0000

$c12_04
           Pr(1)  Pr(2)
class 1:  0.6454 0.3546
class 2:  0.8763 0.1237
class 3:  0.9923 0.0077
class 4:  0.7812 0.2188
class 5:  0.9584 0.0416

$c12_05
           Pr(1)  Pr(2)
class 1:  0.0040 0.9960
class 2:  1.0000 0.0000
class 3:  1.0000 0.0000
class 4:  0.7395 0.2605
class 5:  0.9932 0.0068

$c12_06
           Pr(1)  Pr(2)
class 1:  0.7262 0.2738
class 2:  0.7386 0.2614
class 3:  0.8895 0.1105
class 4:  0.4055 0.5945
class 5:  0.9963 0.0037

$c12_07
           Pr(1)  Pr(2)
class 1:  0.7635 0.2365
class 2:  0.8475 0.1525
class 3:  0.9585 0.0415
class 4:  0.1555 0.8445
class 5:  0.9239 0.0761

$c12_08
           Pr(1)  Pr(2)
class 1:  0.9821 0.0179
class 2:  0.9525 0.0475
class 3:  0.9839 0.0161
class 4:  0.0047 0.9953
class 5:  0.9860 0.0140

$c12_09
           Pr(1)  Pr(2)
class 1:  0.9173 0.0827
class 2:  0.9233 0.0767
class 3:  0.9656 0.0344
class 4:  0.6981 0.3019
class 5:  0.9792 0.0208

Estimated class population shares 
 0.0356 0.2069 0.0999 0.0077 0.6498 
 
Predicted class memberships (by modal posterior prob.) 
 0.04 0.0852 0.1535 0.0071 0.7143 
 
========================================================= 
Fit for 5 latent classes: 
========================================================= 
number of observations: 3675 
number of estimated parameters: 49 
residual degrees of freedom: 462 
maximum log-likelihood: -8537.025 
 
AIC(5): 17172.05
BIC(5): 17476.31
G^2(5): 292.7257 (Likelihood ratio/deviance statistic) 
X^2(5): 628.157 (Chi-square goodness of fit) 
 
ALERT: iterations finished, MAXIMUM LIKELIHOOD NOT FOUND 
 
Conditional item response (column) probabilities,
 by outcome variable, for each class (row) 
 
$c12_01
           Pr(1)  Pr(2)
class 1:  0.6549 0.3451
class 2:  0.5763 0.4237
class 3:  0.6327 0.3673
class 4:  0.8598 0.1402
class 5:  0.9355 0.0645
class 6:  0.4471 0.5529

$c12_02
           Pr(1)  Pr(2)
class 1:  0.8977 0.1023
class 2:  0.3119 0.6881
class 3:  0.7536 0.2464
class 4:  0.6464 0.3536
class 5:  0.9091 0.0909
class 6:  0.5266 0.4734

$c12_03
           Pr(1)  Pr(2)
class 1:  0.9258 0.0742
class 2:  0.7297 0.2703
class 3:  0.9059 0.0941
class 4:  0.8751 0.1249
class 5:  1.0000 0.0000
class 6:  1.0000 0.0000

$c12_04
           Pr(1)  Pr(2)
class 1:  0.9180 0.0820
class 2:  0.6387 0.3613
class 3:  0.2937 0.7063
class 4:  1.0000 0.0000
class 5:  0.9566 0.0434
class 6:  0.9765 0.0235

$c12_05
           Pr(1)  Pr(2)
class 1:  0.9564 0.0436
class 2:  0.5643 0.4357
class 3:  0.5722 0.4278
class 4:  0.7841 0.2159
class 5:  0.9917 0.0083
class 6:  1.0000 0.0000

$c12_06
           Pr(1)  Pr(2)
class 1:  0.8955 0.1045
class 2:  0.0000 1.0000
class 3:  0.7162 0.2838
class 4:  0.6044 0.3956
class 5:  0.9911 0.0089
class 6:  0.8597 0.1403

$c12_07
           Pr(1)  Pr(2)
class 1:  0.6656 0.3344
class 2:  0.1421 0.8579
class 3:  0.8130 0.1870
class 4:  0.8091 0.1909
class 5:  0.9344 0.0656
class 6:  0.9510 0.0490

$c12_08
           Pr(1)  Pr(2)
class 1:  0.8163 0.1837
class 2:  0.0000 1.0000
class 3:  1.0000 0.0000
class 4:  0.9571 0.0429
class 5:  0.9929 0.0071
class 6:  0.9828 0.0172

$c12_09
           Pr(1)  Pr(2)
class 1:  0.9070 0.0930
class 2:  0.6401 0.3599
class 3:  0.8992 0.1008
class 4:  0.9410 0.0590
class 5:  0.9795 0.0205
class 6:  0.9546 0.0454

Estimated class population shares 
 0.0802 0.0036 0.0404 0.0667 0.6196 0.1895 
 
Predicted class memberships (by modal posterior prob.) 
 0.0397 0.0035 0.0307 0.0506 0.7061 0.1693 
 
========================================================= 
Fit for 6 latent classes: 
========================================================= 
number of observations: 3675 
number of estimated parameters: 59 
residual degrees of freedom: 452 
maximum log-likelihood: -8528.939 
 
AIC(6): 17175.88
BIC(6): 17542.23
G^2(6): 276.5544 (Likelihood ratio/deviance statistic) 
X^2(6): 372.7709 (Chi-square goodness of fit) 
 
ALERT: iterations finished, MAXIMUM LIKELIHOOD NOT FOUND 
 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="co">#CREACIÓN TABLA ESTADÍSTICOS DE AJUSTE MODELOS TODAS LAS VARIABLES</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>fit.indices <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(Modelos,AIC,BIC,llik,chi.cuadrado,G2,N)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(fit.indices, <span class="at">caption =</span> <span class="st">"Indicadores de ajuste de los modelos"</span>)</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Indicadores de ajuste de los modelos</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Modelos</th>
<th style="text-align: right;">AIC</th>
<th style="text-align: right;">BIC</th>
<th style="text-align: right;">llik</th>
<th style="text-align: right;">chi.cuadrado</th>
<th style="text-align: right;">G2</th>
<th style="text-align: right;">N</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1 clase</td>
<td style="text-align: right;">17670.07</td>
<td style="text-align: right;">17725.96</td>
<td style="text-align: right;">-8826.037</td>
<td style="text-align: right;">1.505699e+07</td>
<td style="text-align: right;">870.7513</td>
<td style="text-align: right;">3675</td>
</tr>
<tr class="even">
<td style="text-align: left;">2 clases</td>
<td style="text-align: right;">17296.51</td>
<td style="text-align: right;">17414.48</td>
<td style="text-align: right;">-8629.254</td>
<td style="text-align: right;">8.181793e+03</td>
<td style="text-align: right;">477.1844</td>
<td style="text-align: right;">3675</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3 clases</td>
<td style="text-align: right;">17193.04</td>
<td style="text-align: right;">17373.11</td>
<td style="text-align: right;">-8567.520</td>
<td style="text-align: right;">2.524807e+03</td>
<td style="text-align: right;">353.7162</td>
<td style="text-align: right;">3675</td>
</tr>
<tr class="even">
<td style="text-align: left;">4 clases</td>
<td style="text-align: right;">17172.28</td>
<td style="text-align: right;">17414.44</td>
<td style="text-align: right;">-8547.141</td>
<td style="text-align: right;">9.445943e+02</td>
<td style="text-align: right;">312.9582</td>
<td style="text-align: right;">3675</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5 clases</td>
<td style="text-align: right;">17172.05</td>
<td style="text-align: right;">17476.31</td>
<td style="text-align: right;">-8537.025</td>
<td style="text-align: right;">6.281570e+02</td>
<td style="text-align: right;">292.7257</td>
<td style="text-align: right;">3675</td>
</tr>
<tr class="even">
<td style="text-align: left;">6 clases</td>
<td style="text-align: right;">17175.88</td>
<td style="text-align: right;">17542.23</td>
<td style="text-align: right;">-8528.939</td>
<td style="text-align: right;">3.727709e+02</td>
<td style="text-align: right;">276.5544</td>
<td style="text-align: right;">3675</td>
</tr>
</tbody>
</table>
</div>
</div>
<section id="mejor-ajuste" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="mejor-ajuste"><span class="header-section-number">4.1</span> Mejor ajuste</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="co"># best model. </span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>lca3 <span class="ot">&lt;-</span> <span class="fu">poLCA</span>(f,a,<span class="at">nclass=</span><span class="dv">3</span>,<span class="at">graphs=</span>T)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Conditional item response (column) probabilities,
 by outcome variable, for each class (row) 
 
$c12_01
           Pr(1)  Pr(2)
class 1:  0.6840 0.3160
class 2:  0.5720 0.4280
class 3:  0.9248 0.0752

$c12_02
           Pr(1)  Pr(2)
class 1:  0.7194 0.2806
class 2:  0.5542 0.4458
class 3:  0.9386 0.0614

$c12_03
           Pr(1)  Pr(2)
class 1:  0.8765 0.1235
class 2:  0.9896 0.0104
class 3:  0.9973 0.0027

$c12_04
           Pr(1)  Pr(2)
class 1:  0.7222 0.2778
class 2:  0.9791 0.0209
class 3:  0.9524 0.0476

$c12_05
           Pr(1)  Pr(2)
class 1:  0.7053 0.2947
class 2:  1.0000 0.0000
class 3:  0.9886 0.0114

$c12_06
           Pr(1)  Pr(2)
class 1:  0.6620 0.3380
class 2:  0.8698 0.1302
class 3:  0.9885 0.0115

$c12_07
           Pr(1)  Pr(2)
class 1:  0.7173 0.2827
class 2:  0.9343 0.0657
class 3:  0.9201 0.0799

$c12_08
           Pr(1)  Pr(2)
class 1:  0.8742 0.1258
class 2:  0.9812 0.0188
class 3:  0.9855 0.0145

$c12_09
           Pr(1)  Pr(2)
class 1:  0.8846 0.1154
class 2:  0.9591 0.0409
class 3:  0.9780 0.0220

Estimated class population shares 
 0.1184 0.2675 0.6141 
 
Predicted class memberships (by modal posterior prob.) 
 0.0718 0.2947 0.6335 
 
========================================================= 
Fit for 3 latent classes: 
========================================================= 
number of observations: 3675 
number of estimated parameters: 29 
residual degrees of freedom: 482 
maximum log-likelihood: -8567.518 
 
AIC(3): 17193.04
BIC(3): 17373.11
G^2(3): 353.7121 (Likelihood ratio/deviance statistic) 
X^2(3): 2522.64 (Chi-square goodness of fit) 
 
ALERT: iterations finished, MAXIMUM LIKELIHOOD NOT FOUND 
 </code></pre>
</div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="co">#Extraer valores de inicio (modelo seleccionado)</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>probs.start<span class="ot">&lt;-</span>lca3<span class="sc">$</span>probs.start</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="co">#lca3$probs.start</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="co">#Reordnar clases, si es necesario</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>new.probs.start<span class="ot">&lt;-</span><span class="fu">poLCA.reorder</span>(probs.start, <span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">2</span>,<span class="dv">1</span>))</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a><span class="co">#Reanalizar con gráficos</span></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>lca3<span class="ot">&lt;-</span><span class="fu">poLCA</span>(f, a, <span class="at">nclass=</span><span class="dv">3</span>, <span class="at">probs.start=</span>new.probs.start, <span class="at">graphs=</span>T, <span class="at">na.rm=</span><span class="cn">TRUE</span>, <span class="at">maxiter=</span><span class="dv">3000</span>)</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Agregr columna de clasificación</span></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>a_lca <span class="ot">&lt;-</span> <span class="fu">cbind</span>(a, <span class="st">"lclass"</span> <span class="ot">=</span> lca3<span class="sc">$</span>predclass)</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>a_lca<span class="sc">$</span>lclass <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(a_lca<span class="sc">$</span>lclass) <span class="co"># definir factor</span></span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Graficar patrones de membresías múltiples. </span></span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>lcmodel <span class="ot">&lt;-</span> reshape2<span class="sc">::</span><span class="fu">melt</span>(lca3<span class="sc">$</span>probs, <span class="at">level=</span><span class="dv">2</span>)</span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>lcmodel <span class="ot">&lt;-</span> lcmodel<span class="sc">%&gt;%</span></span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">Var1=</span><span class="fu">case_when</span>(Var1<span class="sc">==</span><span class="st">"class 1: "</span><span class="sc">~</span><span class="st">"class 1</span><span class="sc">\n</span><span class="st">(61%)"</span>,</span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a>                               Var1<span class="sc">==</span><span class="st">"class 2: "</span><span class="sc">~</span><span class="st">"class 2</span><span class="sc">\n</span><span class="st">(26%)"</span>,</span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a>                               Var1<span class="sc">==</span><span class="st">"class 3: "</span><span class="sc">~</span><span class="st">"class 3</span><span class="sc">\n</span><span class="st">(12%)"</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">class =</span> <span class="fu">factor</span>(Var1, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"class 1</span><span class="sc">\n</span><span class="st">(61%)"</span>, <span class="st">"class 2</span><span class="sc">\n</span><span class="st">(26%)"</span>, <span class="st">"class 3</span><span class="sc">\n</span><span class="st">(12%)"</span>)))</span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-27"><a href="#cb9-27" aria-hidden="true" tabindex="-1"></a>lcmodel<span class="sc">$</span>L2 <span class="ot">&lt;-</span> plyr<span class="sc">::</span><span class="fu">mapvalues</span>(lcmodel<span class="sc">$</span>L2, </span>
<span id="cb9-28"><a href="#cb9-28" aria-hidden="true" tabindex="-1"></a>                                  <span class="fu">c</span>(<span class="st">'c12_01'</span>,<span class="st">'c12_02'</span>,<span class="st">'c12_03'</span>,<span class="st">'c12_04'</span>,<span class="st">'c12_05'</span>,<span class="st">'c12_06'</span>,<span class="st">'c12_07'</span>,<span class="st">'c12_08'</span>, <span class="st">'c12_09'</span>),</span>
<span id="cb9-29"><a href="#cb9-29" aria-hidden="true" tabindex="-1"></a>                                  <span class="fu">c</span>(<span class="st">"neighborhood"</span>,<span class="st">"religious"</span>,<span class="st">"political"</span>,<span class="st">"union"</span>,<span class="st">"professional"</span>,<span class="st">"charity"</span>,<span class="st">"sports"</span>,<span class="st">"student"</span>, <span class="st">"other"</span>))</span>
<span id="cb9-30"><a href="#cb9-30" aria-hidden="true" tabindex="-1"></a>level_order <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"neighborhood"</span>,<span class="st">"religious"</span>,<span class="st">"charity"</span>,<span class="st">"political"</span>,<span class="st">"union"</span>,<span class="st">"professional"</span>,<span class="st">"sports"</span>,<span class="st">"student"</span>, <span class="st">"other"</span>)</span>
<span id="cb9-31"><a href="#cb9-31" aria-hidden="true" tabindex="-1"></a>lcmodel<span class="sc">$</span>L2 <span class="ot">&lt;-</span> <span class="fu">factor</span>(lcmodel<span class="sc">$</span>L2, <span class="at">levels =</span> level_order)</span>
<span id="cb9-32"><a href="#cb9-32" aria-hidden="true" tabindex="-1"></a>lcmodel<span class="sc">$</span>Var2 <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(lcmodel<span class="sc">$</span>Var2 <span class="sc">==</span> <span class="st">"Pr(1)"</span>, <span class="st">"No"</span>, <span class="st">"Sí"</span>)</span>
<span id="cb9-33"><a href="#cb9-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-34"><a href="#cb9-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-35"><a href="#cb9-35" aria-hidden="true" tabindex="-1"></a>zp1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(lcmodel, <span class="fu">aes</span>(<span class="at">x =</span> L2, <span class="at">y =</span> value, <span class="at">fill =</span> Var2)) <span class="sc">+</span></span>
<span id="cb9-36"><a href="#cb9-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="st">"stack"</span>) <span class="sc">+</span></span>
<span id="cb9-37"><a href="#cb9-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> class, <span class="at">ncol =</span> <span class="dv">1</span>, <span class="at">strip.position =</span> <span class="st">"right"</span>) <span class="sc">+</span></span>
<span id="cb9-38"><a href="#cb9-38" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb9-39"><a href="#cb9-39" aria-hidden="true" tabindex="-1"></a>    <span class="at">text =</span> <span class="fu">element_text</span>(<span class="at">size=</span><span class="dv">15</span>),</span>
<span id="cb9-40"><a href="#cb9-40" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.ticks.y =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb9-41"><a href="#cb9-41" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.position =</span> <span class="st">"top"</span>,</span>
<span id="cb9-42"><a href="#cb9-42" aria-hidden="true" tabindex="-1"></a>    <span class="at">panel.grid.major.y =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb9-43"><a href="#cb9-43" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">8</span>),</span>
<span id="cb9-44"><a href="#cb9-44" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">10</span>),</span>
<span id="cb9-45"><a href="#cb9-45" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>, <span class="at">angle =</span> <span class="dv">90</span>, <span class="at">hjust =</span> <span class="dv">1</span>),</span>
<span id="cb9-46"><a href="#cb9-46" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.text.y =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">10</span>),</span>
<span id="cb9-47"><a href="#cb9-47" aria-hidden="true" tabindex="-1"></a>    <span class="at">strip.text.y =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">0</span>),</span>
<span id="cb9-48"><a href="#cb9-48" aria-hidden="true" tabindex="-1"></a>    <span class="at">strip.background =</span> <span class="fu">element_blank</span>()</span>
<span id="cb9-49"><a href="#cb9-49" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb9-50"><a href="#cb9-50" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">""</span>, <span class="at">y =</span> <span class="st">""</span>, <span class="at">fill =</span> <span class="st">"Es miembro?"</span>) <span class="sc">+</span></span>
<span id="cb9-51"><a href="#cb9-51" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">""</span>, <span class="at">y =</span> <span class="st">"Pr (y)"</span>, <span class="at">title =</span> <span class="st">""</span>) <span class="sc">+</span></span>
<span id="cb9-52"><a href="#cb9-52" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Sí"</span> <span class="ot">=</span> <span class="st">"#8e44ad"</span>, <span class="st">"No"</span> <span class="ot">=</span> <span class="st">"#17202a"</span>)) <span class="sc">+</span></span>
<span id="cb9-53"><a href="#cb9-53" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">labels =</span> scales<span class="sc">::</span><span class="fu">percent_format</span>(<span class="at">scale =</span> <span class="dv">100</span>))</span>
<span id="cb9-54"><a href="#cb9-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-55"><a href="#cb9-55" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(zp1)</span>
<span id="cb9-56"><a href="#cb9-56" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Conditional item response (column) probabilities,
 by outcome variable, for each class (row) 
 
$c12_01
           Pr(1)  Pr(2)
class 1:  0.9254 0.0746
class 2:  0.5730 0.4270
class 3:  0.6841 0.3159

$c12_02
           Pr(1)  Pr(2)
class 1:  0.9390 0.0610
class 2:  0.5557 0.4443
class 3:  0.7194 0.2806

$c12_03
           Pr(1)  Pr(2)
class 1:  0.9974 0.0026
class 2:  0.9896 0.0104
class 3:  0.8765 0.1235

$c12_04
           Pr(1)  Pr(2)
class 1:  0.9523 0.0477
class 2:  0.9789 0.0211
class 3:  0.7221 0.2779

$c12_05
           Pr(1)  Pr(2)
class 1:  0.9886 0.0114
class 2:  1.0000 0.0000
class 3:  0.7050 0.2950

$c12_06
           Pr(1)  Pr(2)
class 1:  0.9887 0.0113
class 2:  0.8702 0.1298
class 3:  0.6620 0.3380

$c12_07
           Pr(1)  Pr(2)
class 1:  0.9201 0.0799
class 2:  0.9342 0.0658
class 3:  0.7173 0.2827

$c12_08
           Pr(1)  Pr(2)
class 1:  0.9855 0.0145
class 2:  0.9812 0.0188
class 3:  0.8742 0.1258

$c12_09
           Pr(1)  Pr(2)
class 1:  0.9780 0.0220
class 2:  0.9592 0.0408
class 3:  0.8846 0.1154

Estimated class population shares 
 0.6123 0.2694 0.1184 
 
Predicted class memberships (by modal posterior prob.) 
 0.6302 0.2947 0.0751 
 
========================================================= 
Fit for 3 latent classes: 
========================================================= 
number of observations: 3675 
number of estimated parameters: 29 
residual degrees of freedom: 482 
maximum log-likelihood: -8567.518 
 
AIC(3): 17193.04
BIC(3): 17373.11
G^2(3): 353.7118 (Likelihood ratio/deviance statistic) 
X^2(3): 2521.96 (Chi-square goodness of fit) 
 </code></pre>
</div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-7-2.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="modelo-de-regresión-lógistica" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="modelo-de-regresión-lógistica"><span class="header-section-number">5</span> Modelo de regresión lógistica</h2>
<p><span class="math display">\[
\begin{align*}
\log\left(\frac{P(conf_gral = 1)}{1 - P(conf_gral = 1)}\right) = &amp; \beta_0 \\
&amp; + \beta_1 \cdot mujer \\
&amp; + \beta_2 \cdot edad25_34 \\
&amp; + \beta_3 \cdot edad35_44 \\
&amp; + \beta_4 \cdot edad45_54 \\
&amp; + \beta_5 \cdot edad55_64 \\
&amp; + \beta_6 \cdot edad65 \\
&amp; + \beta_7 \cdot nivel_educmedia \\
&amp; + \beta_8 \cdot nivel_eductécnica \\
&amp; + \beta_9 \cdot nivel_educunivers \\
&amp; + \beta_{10} \cdot lclass2 \\
&amp; + \beta_{11} \cdot lclass3
\end{align*}
\]</span> Donde:</p>
<ul>
<li><p><span class="math inline">\(\log\left(\frac{P(conf_gral = 1)}{1 - P(conf_gral = 1)}\right)\)</span> es el logaritmo de las odds (logit) de <span class="math inline">\(conf_gral = 1\)</span></p></li>
<li><p><span class="math inline">\(\beta_0\)</span> es el intercepto</p></li>
<li><p><span class="math inline">\(\beta_1, \beta_2, ..., \beta_{11}\)</span> son los coeficientes de regresión para cada variable predictora</p></li>
<li><p><span class="math inline">\(mujer\)</span> es una variable binaria (0 = hombre, 1 = mujer)</p></li>
<li><p><span class="math inline">\(edad25_34, edad35_44, ..., edad65\)</span> son variables dummy para las categorías de edad (la categoría de referencia no aparece en la ecuación)</p></li>
<li><p><span class="math inline">\(nivel_educmedia, nivel_eductécnica, nivel_educunivers\)</span> son variables dummy para los niveles educativos (la categoría de referencia no aparece en la ecuación)</p></li>
<li><p><span class="math inline">\(lclass2, lclass3\)</span> son variables dummy para las clases latentes 2 y 3 (la clase latente 1 es la categoría de referencia)</p></li>
</ul>
</section>
<section id="modelo-1" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="modelo-1"><span class="header-section-number">6</span> Modelo 1</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Regresión loística. </span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(conf_gral <span class="sc">~</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>            mujer <span class="sc">+</span> edad <span class="sc">+</span> nivel_educ <span class="sc">+</span> lclass,</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>          <span class="at">data =</span> a_lca,</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>          <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = conf_gral ~ mujer + edad + nivel_educ + lclass, 
    family = "binomial", data = a_lca)

Coefficients:
                  Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)       -2.52791    0.25882  -9.767  &lt; 2e-16 ***
mujer             -0.43820    0.11285  -3.883 0.000103 ***
edad25_34          0.02165    0.21983   0.099 0.921533    
edad35_44          0.23494    0.21978   1.069 0.285080    
edad45_54          0.09199    0.23106   0.398 0.690541    
edad55_64         -0.10938    0.23785  -0.460 0.645616    
edad65            -0.21617    0.25853  -0.836 0.403064    
nivel_educmedia    0.06958    0.18473   0.377 0.706453    
nivel_eductécnica  0.48217    0.21068   2.289 0.022100 *  
nivel_educunivers  1.33018    0.19004   6.999 2.57e-12 ***
lclass2            0.21451    0.13115   1.636 0.101921    
lclass3            0.45476    0.17990   2.528 0.011475 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 2417.0  on 3650  degrees of freedom
Residual deviance: 2269.5  on 3639  degrees of freedom
  (24 observations deleted due to missingness)
AIC: 2293.5

Number of Fisher Scoring iterations: 5</code></pre>
</div>
</div>
</section>
<section id="probabilidades-predichas" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="probabilidades-predichas"><span class="header-section-number">7</span> Probabilidades Predichas</h2>
<p>Las probabilidades predichas representan la probabilidad estimada de que ocurra el evento de interés (en este caso, <span class="math inline">\(conf\_gral = 1\)</span>) para un conjunto específico de valores de las variables predictoras.</p>
<p>Notación:</p>
<ul>
<li>Sea <span class="math inline">\(Y\)</span> la variable dependiente binaria (<span class="math inline">\(conf\_gral\)</span>)</li>
<li>Sea <span class="math inline">\(\mathbf{X}\)</span> el vector de variables predictoras (<span class="math inline">\(mujer\)</span>, <span class="math inline">\(edad\)</span>, <span class="math inline">\(nivel\_educ\)</span>, <span class="math inline">\(lclass\)</span>)</li>
<li>Sea <span class="math inline">\(\boldsymbol{\beta}\)</span> el vector de coeficientes estimados</li>
</ul>
<p>La probabilidad predicha se denota como:</p>
<p><span class="math display">\[
P(Y = 1 | \mathbf{X} = \mathbf{x}) = \pi(\mathbf{x}) = \frac{1}{1 + e^{-\mathbf{x}\boldsymbol{\beta}}}
\]</span></p>
<p>Donde:</p>
<ul>
<li><span class="math inline">\(\pi(\mathbf{x})\)</span> es la probabilidad predicha para un conjunto específico de valores <span class="math inline">\(\mathbf{x}\)</span></li>
<li><span class="math inline">\(\mathbf{x}\boldsymbol{\beta}\)</span> es el predictor lineal (la suma de los productos de cada variable predictora y su coeficiente correspondiente)</li>
</ul>
</section>
<section id="efectos-marginales" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="efectos-marginales"><span class="header-section-number">8</span> Efectos Marginales</h2>
<p>Los efectos marginales miden el cambio en la probabilidad predicha cuando una variable predictora cambia en una unidad, manteniendo todas las demás variables constantes.</p>
<p>Para una variable continua <span class="math inline">\(X_j\)</span>, el efecto marginal se define como:</p>
<p><span class="math display">\[
\frac{\partial \pi(\mathbf{x})}{\partial X_j} = \pi(\mathbf{x})(1 - \pi(\mathbf{x}))\beta_j
\]</span></p>
<p>Para una variable categórica (como <span class="math inline">\(lclass\)</span>), el efecto marginal al cambiar de la categoría de referencia a la categoría <span class="math inline">\(k\)</span> se calcula como:</p>
<p><span class="math display">\[
EM = P(Y = 1 | X_j = k) - P(Y = 1 | X_j = ref)
\]</span></p>
<p>Donde:</p>
<ul>
<li><span class="math inline">\(P(Y = 1 | X_j = k)\)</span> es la probabilidad predicha cuando la variable <span class="math inline">\(X_j\)</span> está en la categoría <span class="math inline">\(k\)</span></li>
<li><span class="math inline">\(P(Y = 1 | X_j = ref)\)</span> es la probabilidad predicha cuando la variable <span class="math inline">\(X_j\)</span> está en la categoría de referencia</li>
</ul>
</section>
<section id="principales-diferencias" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="principales-diferencias"><span class="header-section-number">9</span> Principales Diferencias</h2>
<ol type="1">
<li><strong>Escala:</strong>
<ul>
<li>Probabilidades Predichas: <span class="math inline">\(\pi(\mathbf{x}) \in [0, 1]\)</span></li>
<li>Efectos Marginales: <span class="math inline">\(EM \in [-1, 1]\)</span></li>
</ul></li>
<li><strong>Interpretación:</strong>
<ul>
<li>Probabilidades Predichas: Probabilidad absoluta de que <span class="math inline">\(Y = 1\)</span> para un conjunto específico de <span class="math inline">\(\mathbf{X}\)</span></li>
<li>Efectos Marginales: Cambio en la probabilidad de <span class="math inline">\(Y = 1\)</span> cuando <span class="math inline">\(X_j\)</span> cambia en una unidad o categoría</li>
</ul></li>
<li><strong>Dependencia de otras variables:</strong>
<ul>
<li>Probabilidades Predichas: Dependen de los valores específicos de todas las <span class="math inline">\(\mathbf{X}\)</span></li>
<li>Efectos Marginales: Se calculan manteniendo las demás variables constantes (usualmente en sus medias o en valores de referencia)</li>
</ul></li>
<li><strong>Uso en el análisis:</strong>
<ul>
<li>Probabilidades Predichas: Útiles para predecir el resultado para casos específicos</li>
<li>Efectos Marginales: Útiles para interpretar el impacto de cada variable en el modelo</li>
</ul></li>
</ol>
</section>
<section id="ejemplo-numérico" class="level2" data-number="10">
<h2 data-number="10" class="anchored" data-anchor-id="ejemplo-numérico"><span class="header-section-number">10</span> Ejemplo Numérico</h2>
<p>Supongamos que para <span class="math inline">\(lclass\)</span> tenemos:</p>
<ul>
<li><span class="math inline">\(P(Y = 1 | lclass = 1) = 0.3\)</span></li>
<li><span class="math inline">\(P(Y = 1 | lclass = 2) = 0.4\)</span></li>
<li><span class="math inline">\(P(Y = 1 | lclass = 3) = 0.5\)</span></li>
</ul>
<p>Entonces:</p>
<ul>
<li>Las probabilidades predichas son 0.3, 0.4, y 0.5 para <span class="math inline">\(lclass\)</span> 1, 2, y 3 respectivamente.</li>
<li>El efecto marginal de pasar de <span class="math inline">\(lclass\)</span> 1 a <span class="math inline">\(lclass\)</span> 2 es: <span class="math inline">\(0.4 - 0.3 = 0.1\)</span></li>
<li>El efecto marginal de pasar de <span class="math inline">\(lclass\)</span> 1 a <span class="math inline">\(lclass\)</span> 3 es: <span class="math inline">\(0.5 - 0.3 = 0.2\)</span></li>
</ul>
<p>Esto significa que, en promedio, pasar de la clase latente 1 a la 2 aumenta la probabilidad de <span class="math inline">\(Y = 1\)</span> en 0.1, mientras que pasar de la clase latente 1 a la 3 la aumenta en 0.2.</p>
</section>
<section id="aplicación-al-modelo-de-clases-latentes" class="level2" data-number="11">
<h2 data-number="11" class="anchored" data-anchor-id="aplicación-al-modelo-de-clases-latentes"><span class="header-section-number">11</span> Aplicación al Modelo de Clases Latentes</h2>
<p>En el contexto de tu modelo de clases latentes:</p>
<ol type="1">
<li><p>Las probabilidades predichas te mostrarían la probabilidad estimada de <span class="math inline">\(conf\_gral = 1\)</span> para cada combinación de clase latente y otras características (como nivel educativo, edad, etc.).</p></li>
<li><p>Los efectos marginales te mostrarían cómo cambia esta probabilidad cuando pasas de una clase latente a otra, manteniendo las demás características constantes.</p></li>
</ol>
<p>Esto te permite no solo predecir la probabilidad de <span class="math inline">\(conf\_gral = 1\)</span> para diferentes perfiles de individuos, sino también entender cómo la pertenencia a diferentes clases latentes influye en esta probabilidad, controlando por otros factores.</p>
<section id="cálculo-probabilidades-predichas" class="level3" data-number="11.1">
<h3 data-number="11.1" class="anchored" data-anchor-id="cálculo-probabilidades-predichas"><span class="header-section-number">11.1</span> Cálculo probabilidades predichas</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="co"># probabilidades predichas</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear un nuevo conjunto de datos</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>newdata <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">mujer =</span> <span class="dv">0</span>,  <span class="co"># Hombre como referencia</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">edad =</span> <span class="st">"25_34"</span>,  <span class="co"># Edad de referencia</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">nivel_educ =</span> <span class="fu">unique</span>(a_lca<span class="sc">$</span>nivel_educ),  <span class="co"># Todos los niveles educativos</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">lclass =</span> <span class="fu">factor</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>)  <span class="co"># Las tres categorías de lclass como factor</span></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Asegurarse de que los niveles de lclass coincidan con los del modelo original</span></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(newdata<span class="sc">$</span>lclass) <span class="ot">&lt;-</span> <span class="fu">levels</span>(a_lca<span class="sc">$</span>lclass)</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular probabilidades predichas</span></span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a>predicted_probs <span class="ot">&lt;-</span> <span class="fu">predict</span>(m1, <span class="at">newdata =</span> newdata, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Añadir las probabilidades predichas al conjunto de datos</span></span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a>newdata<span class="sc">$</span>prob <span class="ot">=</span> predicted_probs</span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear el gráfico</span></span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(newdata, <span class="fu">aes</span>(<span class="at">x =</span> lclass, <span class="at">y =</span> prob, <span class="at">fill =</span> nivel_educ)) <span class="sc">+</span></span>
<span id="cb13-22"><a href="#cb13-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width =</span> <span class="fl">0.9</span>), <span class="at">width =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb13-23"><a href="#cb13-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">sprintf</span>(<span class="st">"%.3f"</span>, prob)), </span>
<span id="cb13-24"><a href="#cb13-24" aria-hidden="true" tabindex="-1"></a>            <span class="at">position =</span> <span class="fu">position_dodge</span>(<span class="at">width =</span> <span class="fl">0.9</span>), </span>
<span id="cb13-25"><a href="#cb13-25" aria-hidden="true" tabindex="-1"></a>            <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb13-26"><a href="#cb13-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Probabilidades predichas por clase latente y nivel educativo"</span>,</span>
<span id="cb13-27"><a href="#cb13-27" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Clase latente"</span>,</span>
<span id="cb13-28"><a href="#cb13-28" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Probabilidad predicha"</span>,</span>
<span id="cb13-29"><a href="#cb13-29" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">"Nivel educativo"</span>) <span class="sc">+</span></span>
<span id="cb13-30"><a href="#cb13-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb13-31"><a href="#cb13-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">0</span>, <span class="at">hjust =</span> <span class="fl">0.5</span>),</span>
<span id="cb13-32"><a href="#cb13-32" aria-hidden="true" tabindex="-1"></a>        <span class="at">legend.position =</span> <span class="st">"bottom"</span>) <span class="sc">+</span></span>
<span id="cb13-33"><a href="#cb13-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="dv">0</span>, <span class="fu">max</span>(newdata<span class="sc">$</span>prob) <span class="sc">*</span> <span class="fl">1.1</span>) <span class="sc">+</span>  </span>
<span id="cb13-34"><a href="#cb13-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">"Set2"</span>) </span>
<span id="cb13-35"><a href="#cb13-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-36"><a href="#cb13-36" aria-hidden="true" tabindex="-1"></a><span class="co"># Imprimir un resumen de las probabilidades predichas</span></span>
<span id="cb13-37"><a href="#cb13-37" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(newdata[<span class="fu">order</span>(newdata<span class="sc">$</span>lclass, newdata<span class="sc">$</span>nivel_educ), ])</span>
<span id="cb13-38"><a href="#cb13-38" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   mujer  edad nivel_educ lclass       prob
1      0 25_34     básica      1 0.07542070
2      0 25_34      media      1 0.08041797
3      0 25_34    técnica      1 0.11669714
4      0 25_34    univers      1 0.23575746
5      0 25_34     básica      2 0.09180871
6      0 25_34      media      2 0.09777699
7      0 25_34    técnica      2 0.14068927
8      0 25_34    univers      2 0.27656347
9      0 25_34     básica      3 0.11390128
10     0 25_34      media      3 0.12111422
11     0 25_34    técnica      3 0.17231259
12     0 25_34    univers      3 0.32710218</code></pre>
</div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="cálculo-efectos-marginales" class="level3" data-number="11.2">
<h3 data-number="11.2" class="anchored" data-anchor-id="cálculo-efectos-marginales"><span class="header-section-number">11.2</span> Cálculo efectos marginales</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Efectos marginales. </span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular los efectos marginales</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>marg_effects <span class="ot">&lt;-</span> <span class="fu">margins</span>(m1, <span class="at">variables =</span> <span class="st">"lclass"</span>)</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Resumen de los efectos marginales</span></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>summary_marg <span class="ot">&lt;-</span> <span class="fu">summary</span>(marg_effects)</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(summary_marg)</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Filtrar solo las filas relacionadas con lclass</span></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>lclass_effects <span class="ot">&lt;-</span> summary_marg[<span class="fu">grep</span>(<span class="st">"lclass"</span>, summary_marg<span class="sc">$</span>factor), ]</span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear un dataframe para graficar</span></span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>plot_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">lclass =</span> <span class="fu">factor</span>(lclass_effects<span class="sc">$</span>factor),</span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">effect =</span> lclass_effects<span class="sc">$</span>AME,</span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">lower =</span> lclass_effects<span class="sc">$</span>lower,</span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">upper =</span> lclass_effects<span class="sc">$</span>upper</span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear el gráfico</span></span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(plot_data, <span class="fu">aes</span>(<span class="at">x =</span> lclass, <span class="at">y =</span> effect)) <span class="sc">+</span></span>
<span id="cb15-23"><a href="#cb15-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">fill =</span> <span class="st">"skyblue"</span>, <span class="at">width =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb15-24"><a href="#cb15-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> lower, <span class="at">ymax =</span> upper), <span class="at">width =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb15-25"><a href="#cb15-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">sprintf</span>(<span class="st">"%.3f"</span>, effect)), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb15-26"><a href="#cb15-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Efectos marginales promedio para lclass"</span>,</span>
<span id="cb15-27"><a href="#cb15-27" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Clase latente"</span>,</span>
<span id="cb15-28"><a href="#cb15-28" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Efecto marginal promedio"</span>) <span class="sc">+</span></span>
<span id="cb15-29"><a href="#cb15-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb15-30"><a href="#cb15-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb15-31"><a href="#cb15-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="fu">min</span>(plot_data<span class="sc">$</span>lower) <span class="sc">*</span> <span class="fl">1.1</span>, <span class="fu">max</span>(plot_data<span class="sc">$</span>upper) <span class="sc">*</span> <span class="fl">1.1</span>)</span>
<span id="cb15-32"><a href="#cb15-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-33"><a href="#cb15-33" aria-hidden="true" tabindex="-1"></a><span class="co"># Imprimir los efectos marginales</span></span>
<span id="cb15-34"><a href="#cb15-34" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(plot_data)</span>
<span id="cb15-35"><a href="#cb15-35" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  factor    AME     SE      z      p   lower  upper
 lclass2 0.0189 0.0119 1.5870 0.1125 -0.0044 0.0423
 lclass3 0.0438 0.0194 2.2536 0.0242  0.0057 0.0819
         lclass     effect        lower      upper
lclass2 lclass2 0.01892925 -0.004448470 0.04230697
lclass3 lclass3 0.04382624  0.005711129 0.08194135</code></pre>
</div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="clasificación" class="level2" data-number="12">
<h2 data-number="12" class="anchored" data-anchor-id="clasificación"><span class="header-section-number">12</span> Clasificación</h2>
<p>En el contexto de la regresión logística, la clasificación se refiere al proceso de asignar cada observación a una de las dos categorías de la variable dependiente (en este caso, <span class="math inline">\(conf_gral\)</span>) basándose en las probabilidades predichas por el modelo.</p>
<p>La idea básica es la siguiente:</p>
<p>El modelo de regresión logística produce una probabilidad predicha <span class="math inline">\(\hat{p}\)</span> para cada observación. Se establece un umbral de decisión, comúnmente 0.5. Si <span class="math inline">\(\hat{p} \geq 0.5\)</span>, la observación se clasifica como 1 (tiene confianza general). Si <span class="math inline">\(\hat{p} &lt; 0.5\)</span>, la observación se clasifica como 0 (no tiene confianza general).</p>
<p>Matemáticamente, podemos expresar esto como: <span class="math display">\[
\text{Clasificación} =
\begin{cases}
1 &amp; \text{si } \hat{p} \geq 0.5 \
0 &amp; \text{si } \hat{p} &lt; 0.5
\end{cases}
\]</span> Donde <span class="math inline">\(\hat{p} = P(conf_gral = 1 | X)\)</span> es la probabilidad predicha por el modelo. Evaluación de la Clasificación Para evaluar la calidad de la clasificación, se utilizan varias métricas:</p>
<p>Exactitud (Accuracy): Proporción de predicciones correctas. <span class="math display">\[\text{Exactitud} = \frac{\text{TP} + \text{TN}}{\text{TP} + \text{TN} + \text{FP} + \text{FN}}\]</span> Sensibilidad (Sensitivity) o Tasa de Verdaderos Positivos: Proporción de positivos reales correctamente identificados. <span class="math display">\[\text{Sensibilidad} = \frac{\text{TP}}{\text{TP} + \text{FN}}\]</span> Especificidad (Specificity) o Tasa de Verdaderos Negativos: Proporción de negativos reales correctamente identificados. <span class="math display">\[\text{Especificidad} = \frac{\text{TN}}{\text{TN} + \text{FP}}\]</span></p>
<p>Donde TP = Verdaderos Positivos, TN = Verdaderos Negativos, FP = Falsos Positivos, FN = Falsos Negativos.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, warning=FALSE, message=TRUE}</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Preparar los datos</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Asumiendo que a_lca ya está cargado en el entorno</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>complete_cases <span class="ot">&lt;-</span> <span class="fu">complete.cases</span>(a_lca[, <span class="fu">c</span>(<span class="st">"conf_gral"</span>, <span class="st">"mujer"</span>, <span class="st">"edad"</span>, <span class="st">"nivel_educ"</span>, <span class="st">"lclass"</span>)])</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>a_lca_complete <span class="ot">&lt;-</span> a_lca[complete_cases, ]</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Asegurar que las variables categóricas sean factores</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>a_lca_complete<span class="sc">$</span>edad <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(a_lca_complete<span class="sc">$</span>edad)</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>a_lca_complete<span class="sc">$</span>nivel_educ <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(a_lca_complete<span class="sc">$</span>nivel_educ)</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>a_lca_complete<span class="sc">$</span>lclass <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(a_lca_complete<span class="sc">$</span>lclass)</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Calcular pesos para las clases</span></span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>class_weights <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(a_lca_complete<span class="sc">$</span>conf_gral <span class="sc">==</span> <span class="dv">1</span>, </span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>                        (<span class="dv">1</span><span class="sc">/</span><span class="fu">table</span>(a_lca_complete<span class="sc">$</span>conf_gral)[<span class="dv">2</span>]) <span class="sc">*</span> <span class="fl">0.5</span>,</span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>                        (<span class="dv">1</span><span class="sc">/</span><span class="fu">table</span>(a_lca_complete<span class="sc">$</span>conf_gral)[<span class="dv">1</span>]) <span class="sc">*</span> <span class="fl">0.5</span>)</span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a><span class="co"># 3. Entrenar el modelo con pesos</span></span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a>m1_weighted <span class="ot">&lt;-</span> <span class="fu">glm</span>(conf_gral <span class="sc">~</span> mujer <span class="sc">+</span> edad <span class="sc">+</span> nivel_educ <span class="sc">+</span> lclass, </span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a>                   <span class="at">data =</span> a_lca_complete, </span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a>                   <span class="at">family =</span> <span class="st">"binomial"</span>,</span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a>                   <span class="at">weights =</span> class_weights)</span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-23"><a href="#cb17-23" aria-hidden="true" tabindex="-1"></a><span class="co"># 4. Evaluar el modelo con umbral 0.3</span></span>
<span id="cb17-24"><a href="#cb17-24" aria-hidden="true" tabindex="-1"></a>threshold <span class="ot">&lt;-</span> <span class="fl">0.3</span></span>
<span id="cb17-25"><a href="#cb17-25" aria-hidden="true" tabindex="-1"></a>pred_probs <span class="ot">&lt;-</span> <span class="fu">predict</span>(m1_weighted, <span class="at">newdata =</span> a_lca_complete, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb17-26"><a href="#cb17-26" aria-hidden="true" tabindex="-1"></a>pred_class <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(pred_probs <span class="sc">&gt;</span> threshold, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb17-27"><a href="#cb17-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-28"><a href="#cb17-28" aria-hidden="true" tabindex="-1"></a>conf_matrix <span class="ot">&lt;-</span> <span class="fu">table</span>(<span class="at">Predicted =</span> pred_class, <span class="at">Actual =</span> a_lca_complete<span class="sc">$</span>conf_gral)</span>
<span id="cb17-29"><a href="#cb17-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-30"><a href="#cb17-30" aria-hidden="true" tabindex="-1"></a><span class="co"># 5. Calcular métricas</span></span>
<span id="cb17-31"><a href="#cb17-31" aria-hidden="true" tabindex="-1"></a>accuracy <span class="ot">&lt;-</span> <span class="fu">sum</span>(<span class="fu">diag</span>(conf_matrix)) <span class="sc">/</span> <span class="fu">sum</span>(conf_matrix)</span>
<span id="cb17-32"><a href="#cb17-32" aria-hidden="true" tabindex="-1"></a>sensitivity <span class="ot">&lt;-</span> conf_matrix[<span class="dv">2</span>,<span class="dv">2</span>] <span class="sc">/</span> <span class="fu">sum</span>(conf_matrix[,<span class="dv">2</span>])</span>
<span id="cb17-33"><a href="#cb17-33" aria-hidden="true" tabindex="-1"></a>specificity <span class="ot">&lt;-</span> conf_matrix[<span class="dv">1</span>,<span class="dv">1</span>] <span class="sc">/</span> <span class="fu">sum</span>(conf_matrix[,<span class="dv">1</span>])</span>
<span id="cb17-34"><a href="#cb17-34" aria-hidden="true" tabindex="-1"></a>precision <span class="ot">&lt;-</span> conf_matrix[<span class="dv">2</span>,<span class="dv">2</span>] <span class="sc">/</span> <span class="fu">sum</span>(conf_matrix[<span class="dv">2</span>,])</span>
<span id="cb17-35"><a href="#cb17-35" aria-hidden="true" tabindex="-1"></a>f1_score <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> (precision <span class="sc">*</span> sensitivity) <span class="sc">/</span> (precision <span class="sc">+</span> sensitivity)</span>
<span id="cb17-36"><a href="#cb17-36" aria-hidden="true" tabindex="-1"></a>roc_obj <span class="ot">&lt;-</span> <span class="fu">roc</span>(a_lca_complete<span class="sc">$</span>conf_gral, pred_probs)</span>
<span id="cb17-37"><a href="#cb17-37" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting levels: control = 0, case = 1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Setting direction: controls &lt; cases</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, warning=FALSE, message=TRUE}</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>auc_value <span class="ot">&lt;-</span> <span class="fu">auc</span>(roc_obj)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 6. Visualizar la matriz de confusión</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">as.data.frame</span>(conf_matrix), <span class="fu">aes</span>(<span class="at">x =</span> Actual, <span class="at">y =</span> Predicted, <span class="at">fill =</span> Freq)) <span class="sc">+</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_tile</span>() <span class="sc">+</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">sprintf</span>(<span class="st">"%d"</span>, Freq)), <span class="at">vjust =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_gradient</span>(<span class="at">low =</span> <span class="st">"white"</span>, <span class="at">high =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Matriz de Confusión (Umbral = 0.3)"</span>,</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Visualización de Verdaderos/Falsos Positivos/Negativos"</span>,</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Valor Real"</span>,</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Predicción"</span>) <span class="sc">+</span></span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"No Confianza"</span>, <span class="st">"Confianza"</span>)) <span class="sc">+</span></span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_discrete</span>(<span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"No Confianza"</span>, <span class="st">"Confianza"</span>))</span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a><span class="co"># 7. Visualizar distribución de probabilidades predichas</span></span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">data.frame</span>(<span class="at">prob =</span> pred_probs, <span class="at">actual =</span> <span class="fu">factor</span>(a_lca_complete<span class="sc">$</span>conf_gral)), <span class="fu">aes</span>(<span class="at">x =</span> prob, <span class="at">fill =</span> actual)) <span class="sc">+</span></span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">position =</span> <span class="st">"identity"</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">bins =</span> <span class="dv">50</span>) <span class="sc">+</span></span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> threshold, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"blue"</span>, <span class="st">"green"</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"No Confianza"</span>, <span class="st">"Confianza"</span>)) <span class="sc">+</span></span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Distribución de Probabilidades Predichas"</span>,</span>
<span id="cb20-23"><a href="#cb20-23" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="fu">paste</span>(<span class="st">"Umbral de clasificación:"</span>, threshold),</span>
<span id="cb20-24"><a href="#cb20-24" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Probabilidad Predicha"</span>,</span>
<span id="cb20-25"><a href="#cb20-25" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Frecuencia"</span>,</span>
<span id="cb20-26"><a href="#cb20-26" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">"Valor Real"</span>) <span class="sc">+</span></span>
<span id="cb20-27"><a href="#cb20-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb20-28"><a href="#cb20-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-29"><a href="#cb20-29" aria-hidden="true" tabindex="-1"></a><span class="co"># 8. Visualizar métricas de rendimiento</span></span>
<span id="cb20-30"><a href="#cb20-30" aria-hidden="true" tabindex="-1"></a>metrics <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb20-31"><a href="#cb20-31" aria-hidden="true" tabindex="-1"></a>  <span class="at">Metric =</span> <span class="fu">c</span>(<span class="st">"Exactitud"</span>, <span class="st">"Sensibilidad"</span>, <span class="st">"Especificidad"</span>, <span class="st">"Precisión"</span>, <span class="st">"F1-Score"</span>),</span>
<span id="cb20-32"><a href="#cb20-32" aria-hidden="true" tabindex="-1"></a>  <span class="at">Value =</span> <span class="fu">c</span>(accuracy, sensitivity, specificity, precision, f1_score)</span>
<span id="cb20-33"><a href="#cb20-33" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb20-34"><a href="#cb20-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-35"><a href="#cb20-35" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(metrics, <span class="fu">aes</span>(<span class="at">x =</span> Metric, <span class="at">y =</span> Value)) <span class="sc">+</span></span>
<span id="cb20-36"><a href="#cb20-36" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">fill =</span> <span class="st">"skyblue"</span>) <span class="sc">+</span></span>
<span id="cb20-37"><a href="#cb20-37" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">sprintf</span>(<span class="st">"%.3f"</span>, Value)), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb20-38"><a href="#cb20-38" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylim</span>(<span class="dv">0</span>, <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb20-39"><a href="#cb20-39" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Métricas de Rendimiento del Modelo"</span>,</span>
<span id="cb20-40"><a href="#cb20-40" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="fu">paste</span>(<span class="st">"Umbral de clasificación:"</span>, threshold),</span>
<span id="cb20-41"><a href="#cb20-41" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">""</span>,</span>
<span id="cb20-42"><a href="#cb20-42" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Valor"</span>) <span class="sc">+</span></span>
<span id="cb20-43"><a href="#cb20-43" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb20-44"><a href="#cb20-44" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span>
<span id="cb20-45"><a href="#cb20-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-46"><a href="#cb20-46" aria-hidden="true" tabindex="-1"></a><span class="co"># 9. Visualizar curva ROC</span></span>
<span id="cb20-47"><a href="#cb20-47" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">data.frame</span>(<span class="at">FPR =</span> <span class="dv">1</span> <span class="sc">-</span> roc_obj<span class="sc">$</span>specificities, <span class="at">TPR =</span> roc_obj<span class="sc">$</span>sensitivities)) <span class="sc">+</span></span>
<span id="cb20-48"><a href="#cb20-48" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">x =</span> FPR, <span class="at">y =</span> TPR)) <span class="sc">+</span></span>
<span id="cb20-49"><a href="#cb20-49" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">slope =</span> <span class="dv">1</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb20-50"><a href="#cb20-50" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="fl">0.75</span>, <span class="at">y =</span> <span class="fl">0.25</span>, </span>
<span id="cb20-51"><a href="#cb20-51" aria-hidden="true" tabindex="-1"></a>           <span class="at">label =</span> <span class="fu">paste</span>(<span class="st">"AUC ="</span>, <span class="fu">round</span>(auc_value, <span class="dv">3</span>))) <span class="sc">+</span></span>
<span id="cb20-52"><a href="#cb20-52" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Curva ROC"</span>,</span>
<span id="cb20-53"><a href="#cb20-53" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Tasa de Falsos Positivos (1 - Especificidad)"</span>,</span>
<span id="cb20-54"><a href="#cb20-54" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Tasa de Verdaderos Positivos (Sensibilidad)"</span>) <span class="sc">+</span></span>
<span id="cb20-55"><a href="#cb20-55" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb20-56"><a href="#cb20-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-57"><a href="#cb20-57" aria-hidden="true" tabindex="-1"></a><span class="co"># 10. Imprimir un resumen del modelo</span></span>
<span id="cb20-58"><a href="#cb20-58" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1_weighted)</span>
<span id="cb20-59"><a href="#cb20-59" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = conf_gral ~ mujer + edad + nivel_educ + lclass, 
    family = "binomial", data = a_lca_complete, weights = class_weights)

Coefficients:
                  Estimate Std. Error z value Pr(&gt;|z|)
(Intercept)       -0.36523    9.69855  -0.038    0.970
mujer             -0.45996    4.31436  -0.107    0.915
edad25_34          0.04030    8.76848   0.005    0.996
edad35_44          0.26732    8.79926   0.030    0.976
edad45_54          0.11870    9.02192   0.013    0.990
edad55_64         -0.04219    9.16586  -0.005    0.996
edad65            -0.18204    9.89282  -0.018    0.985
nivel_educmedia    0.06834    6.29916   0.011    0.991
nivel_eductécnica  0.48886    7.46792   0.065    0.948
nivel_educunivers  1.33776    7.11981   0.188    0.851
lclass2            0.18372    4.91370   0.037    0.970
lclass3            0.36007    7.57626   0.048    0.962

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 1.3863  on 3650  degrees of freedom
Residual deviance: 1.2847  on 3639  degrees of freedom
AIC: 24

Number of Fisher Scoring iterations: 4</code></pre>
</div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-11-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-11-3.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-11-4.png" class="img-fluid" width="672"></p>
</div>
</div>
<section id="interpretación" class="level3" data-number="12.1">
<h3 data-number="12.1" class="anchored" data-anchor-id="interpretación"><span class="header-section-number">12.1</span> Interpretación</h3>
<ol type="1">
<li><strong>Matriz de Confusión</strong>:
<ul>
<li>La matriz de confusión nos muestra cómo se clasifican nuestras predicciones en comparación con los valores reales.</li>
<li>Los números en la diagonal (210 y 369) representan las predicciones correctas.</li>
<li>Los números fuera de la diagonal (6 y 3066) representan los errores de clasificación.</li>
<li>Observamos que hay un gran número de falsos positivos (3066), lo que indica que el modelo tiende a sobreestimar la confianza.</li>
</ul></li>
<li><strong>Distribución de Probabilidades Predichas</strong>:
<ul>
<li>Este gráfico nos muestra cómo el modelo asigna probabilidades a las observaciones.</li>
<li>La línea roja punteada representa nuestro umbral de clasificación (0.3).</li>
<li>Observamos que muchas observaciones de “No Confianza” (azul) están por encima del umbral, lo que explica los numerosos falsos positivos.</li>
</ul></li>
<li><strong>Métricas de Rendimiento</strong>:
<ul>
<li>Exactitud (0.159): Solo el 15.9% de todas las predicciones son correctas.</li>
<li>Sensibilidad (0.984): El modelo identifica correctamente el 98.4% de los casos reales de confianza.</li>
<li>Especificidad (0.064): Solo el 6.4% de los casos reales de no confianza son correctamente identificados.</li>
<li>Precisión (0.107): De todos los casos que el modelo predice como confianza, solo el 10.7% realmente lo son.</li>
<li>F1-Score (0.194): Este valor bajo refleja el desequilibrio entre la alta sensibilidad y la baja precisión.</li>
</ul></li>
<li><strong>Curva ROC</strong>:
<ul>
<li>La curva ROC nos muestra el rendimiento del clasificador a diferentes umbrales.</li>
<li>Un clasificador perfecto tendría un AUC de 1, mientras que uno aleatorio tendría 0.5.</li>
<li>Nuestro AUC de 0.675 indica que el modelo tiene cierta capacidad discriminativa, aunque no es excelente.</li>
</ul></li>
</ol>
</section>
<section id="decisiones-y-consideraciones" class="level3" data-number="12.2">
<h3 data-number="12.2" class="anchored" data-anchor-id="decisiones-y-consideraciones"><span class="header-section-number">12.2</span> Decisiones y Consideraciones</h3>
<ol type="1">
<li><strong>Elección del Umbral</strong>:
<ul>
<li>El umbral de 0.3 prioriza la sensibilidad sobre la especificidad.</li>
<li>Esto es útil si es crucial no perder casos reales de confianza, incluso a costa de muchos falsos positivos.</li>
</ul></li>
<li><strong>Implicaciones Prácticas</strong>:
<ul>
<li>Alta Sensibilidad: Casi todos los casos reales de confianza son identificados.</li>
<li>Baja Especificidad: Muchos casos de no confianza son clasificados erróneamente como confianza.</li>
<li>Considerar si el costo de los falsos positivos es aceptable en el contexto de tu investigación.</li>
</ul></li>
<li><strong>Posibles Mejoras</strong>:
<ul>
<li>Ajustar el umbral: Un umbral más alto podría mejorar la especificidad a costa de la sensibilidad.</li>
<li>Recolectar más datos o características: Esto podría mejorar la capacidad predictiva del modelo.</li>
<li>Explorar técnicas de balanceo de clases más avanzadas.</li>
</ul></li>
<li><strong>Contexto de Uso</strong>:
<ul>
<li>Este modelo podría ser útil como una herramienta de “screening” inicial, donde los casos identificados como positivos pasarían por una evaluación más detallada posteriormente.</li>
</ul></li>
</ol>
<p>En resumen, este modelo con un umbral de 0.3 es muy sensible pero poco específico. La decisión de usarlo dependerá de si es más importante capturar todos los casos positivos posibles o tener predicciones más precisas en general.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>