<!DOCTYPE html>
<html lang="en"><head>
<script src="bonus_tablas_contingencia_files/libs/clipboard/clipboard.min.js"></script>
<script src="bonus_tablas_contingencia_files/libs/quarto-html/tabby.min.js"></script>
<script src="bonus_tablas_contingencia_files/libs/quarto-html/popper.min.js"></script>
<script src="bonus_tablas_contingencia_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="bonus_tablas_contingencia_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="bonus_tablas_contingencia_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="bonus_tablas_contingencia_files/libs/quarto-html/quarto-syntax-highlighting-de63f62b328812d8e578a4d74e282472.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.38">

  <meta name="author" content="Mauricio Bucca · Sociología UC">
  <meta name="dcterms.date" content="2026-07-23">
  <title>Análisis de Datos Categóricos (SOC3070)</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="bonus_tablas_contingencia_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="bonus_tablas_contingencia_files/libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
      }
    pre.numberSource { margin-left: 3em;  padding-left: 4px; }
    div.sourceCode
      { color: #24292e;  }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #24292e; } /* Normal */
    code span.al { color: #ff5555; font-weight: bold; } /* Alert */
    code span.an { color: #6a737d; } /* Annotation */
    code span.at { color: #d73a49; } /* Attribute */
    code span.bn { color: #005cc5; } /* BaseN */
    code span.bu { color: #d73a49; } /* BuiltIn */
    code span.cf { color: #d73a49; } /* ControlFlow */
    code span.ch { color: #032f62; } /* Char */
    code span.cn { color: #005cc5; } /* Constant */
    code span.co { color: #6a737d; } /* Comment */
    code span.cv { color: #6a737d; } /* CommentVar */
    code span.do { color: #6a737d; } /* Documentation */
    code span.dt { color: #d73a49; } /* DataType */
    code span.dv { color: #005cc5; } /* DecVal */
    code span.er { color: #ff5555; text-decoration: underline; } /* Error */
    code span.ex { color: #d73a49; font-weight: bold; } /* Extension */
    code span.fl { color: #005cc5; } /* Float */
    code span.fu { color: #6f42c1; } /* Function */
    code span.im { color: #032f62; } /* Import */
    code span.in { color: #6a737d; } /* Information */
    code span.kw { color: #d73a49; } /* Keyword */
    code span.op { color: #24292e; } /* Operator */
    code span.ot { color: #6f42c1; } /* Other */
    code span.pp { color: #d73a49; } /* Preprocessor */
    code span.re { color: #6a737d; } /* RegionMarker */
    code span.sc { color: #005cc5; } /* SpecialChar */
    code span.ss { color: #032f62; } /* SpecialString */
    code span.st { color: #032f62; } /* String */
    code span.va { color: #e36209; } /* Variable */
    code span.vs { color: #032f62; } /* VerbatimString */
    code span.wa { color: #ff5555; } /* Warning */
  </style>
  <link rel="stylesheet" href="bonus_tablas_contingencia_files/libs/revealjs/dist/theme/quarto-2740581606dc327e82f18f789b69d8a0.css">
  <link rel="stylesheet" href="../_shared/course.css">
  <script>window.backupDefine = window.define; window.define = undefined;</script><script src="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js"></script>
  <script>document.addEventListener("DOMContentLoaded", function () {
 var mathElements = document.getElementsByClassName("math");
 var macros = [];
 for (var i = 0; i < mathElements.length; i++) {
  var texText = mathElements[i].firstChild;
  if (mathElements[i].tagName == "SPAN") {
   katex.render(texText.data, mathElements[i], {
    displayMode: mathElements[i].classList.contains('display'),
    throwOnError: false,
    macros: macros,
    fleqn: false
   });
}}});
  </script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css">
  <link href="bonus_tablas_contingencia_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="bonus_tablas_contingencia_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="bonus_tablas_contingencia_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="bonus_tablas_contingencia_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="theme-arsenal quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" data-background-color="#D71920" class="quarto-title-block center">
  <h1 class="title">Análisis de Datos Categóricos (SOC3070)</h1>
  <p class="subtitle">Tablas de Contingencia</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Mauricio Bucca · Sociología UC 
</div>
</div>
</div>

  <p class="date">2026-07-23</p>
</section>
<section id="antes-hoy-después" class="slide level2 class-rhythm">
<h2>Antes · Hoy · Después</h2>
<div class="full-width">
<div class="content-box">
<p><strong>Antes</strong></p>
<p>valor esperado, varianza y máxima verosimilitud.</p>
</div>
<div class="content-box-primary">
<p><strong>Hoy</strong></p>
<p>tablas de contingencia, asociación e independencia.</p>
</div>
<div class="content-box-secondary">
<p><strong>Después</strong></p>
<p>regresión lineal para outcomes categóricos.</p>
</div>
</div>
</section>
<section>
<section id="tablas-de-contingencia" class="title-slide slide level1 inverse center middle" data-background-color="#063672">
<h1>Tablas de Contingencia</h1>

</section>
<section id="datos-de-demanda-de-bicicletas-ejemplo" class="slide level2">
<h2>Datos de demanda de bicicletas, ejemplo</h2>
<ul>
<li>Usaremos datos del sistema de bicicletas compartidas <em>Capital Bikeshare</em> (Washington DC, 2011–2012).</li>
<li>8.645 observaciones horarias. Para cada hora observamos el número de arriendos (<code>bikers</code>) y covariables como temperatura, humedad, situación climática, hora del día, día de la semana y feriados.</li>
</ul>
<div class="fragment">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 8
  bikers  temp   hum windspeed workingday weathersit   hr    demanda
   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt; &lt;fct&gt;        &lt;fct&gt; &lt;chr&gt;  
1     16  0.240  0.810    0               0 clear        0     baja   
2     40  0.220  0.800     0               0 clear        1     baja   
3     32  0.220  0.800     0               0 clear        2     baja   
4     13  0.240  0.750    0               0 clear        3     baja   
5      1  0.240  0.750    0               0 clear        4     baja   
6      1  0.240  0.750    0.090          0 cloudy/misty 5     baja   
7      2  0.220  0.800     0               0 clear        6     baja   
8      3  0.200   0.860    0               0 clear        7     baja   </code></pre>
</div>
</div>
</div>
</section>
<section id="datos-de-demanda-de-bicicletas-ejemplo-1" class="slide level2">
<h2>Datos de demanda de bicicletas, ejemplo</h2>
<div class="fragment">
<p>Si estuviéramos interesados en estudiar la asociación entre el tipo de día (hábil vs.&nbsp;no hábil) y el nivel de demanda (alta vs.&nbsp;baja), el primer paso probablemente sería construir una tabla de este tipo:</p>
</div>
<div class="fragment">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href=""></a>ctable <span class="ot">&lt;-</span> bikedata <span class="sc">%&gt;%</span> <span class="fu">with</span>(<span class="fu">table</span>(dia,demanda))</span>
<span id="cb2-2"><a href=""></a><span class="fu">print</span>(ctable)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>          demanda
dia        alta baja
  hábil    1397 4514
  no hábil  759 1975</code></pre>
</div>
</div>
</div>
<div class="fragment">
<p>Este tipo de tablas se denomina <em>tablas de contingencia</em>.</p>
</div>
</section>
<section id="tablas-de-contingencia-1" class="slide level2">
<h2>Tablas de contingencia</h2>
<p>Una definición formal: una tabla de contingencia es una matriz que muestra la <em>distribución multivariada</em> de frecuencias de un número arbitrario de variables categóricas.</p>
<p>Caso simple:</p>
<ul>
<li><span class="math inline">X</span> y <span class="math inline">Y</span> son dos variables categóricas.
<ul>
<li><span class="math inline">X</span> tiene <span class="math inline">I</span> categorías <span class="math inline">\{i, \dots, I \}</span></li>
<li><span class="math inline">Y</span> tiene <span class="math inline">J</span> categorías <span class="math inline">\{j, \dots, J \}</span>.</li>
</ul></li>
</ul>
<div class="fragment">
<p>Una tabla rectangular que clasifica todas las combinaciones posibles de <span class="math inline">X</span> y <span class="math inline">Y</span> tendrá <span class="math inline">I</span> filas para las categorías de <span class="math inline">X</span>, <span class="math inline">J</span> columnas para las categorías de <span class="math inline">Y</span>, y <span class="math inline">I \times J</span> celdas.</p>
</div>
</section>
<section id="tablas-de-contingencia-2" class="slide level2">
<h2>Tablas de contingencia</h2>
<ul>
<li>Una tabla que clasifica <span class="math inline">n</span> variables se denomina una tabla <span class="math inline">n</span>-way</li>
<li>Una tabla con <span class="math inline">I</span> filas y <span class="math inline">J</span> columnas se denomina una <span class="math inline">I \times J</span> (léase I-por-J)</li>
</ul>
<div class="fragment">
<p>Por ejemplo, la tabla en nuestro ejemplo es una tabla 2-way, 2-por-2</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>          demanda
dia        alta baja
  hábil    1397 4514
  no hábil  759 1975</code></pre>
</div>
</div>
</div>
<div class="fragment">
<ul>
<li>Una tabla de contingencia <span class="math inline">n_{ij}</span> (frecuencia conjunta) denota la frecuencia observada en la celda <span class="math inline">i,j</span>, es decir, el número de casos presentes en la combinación <span class="math inline">X=i \text{ y } Y=j</span></li>
<li>Usando la notación matricial <span class="math inline">i</span> indexa las filas y <span class="math inline">j</span> las columnas.</li>
</ul>
</div>
</section>
<section id="distribución-conjunta-y-marginal-de-frecuencias" class="slide level2">
<h2>Distribución conjunta y marginal de frecuencias</h2>
<p>Estructura general de una tabla 2-way, <span class="math inline">I \times J</span></p>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 14%">
<col style="width: 17%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;"></th>
<th style="text-align: center;"><span class="math inline">Y=y_{1}</span></th>
<th style="text-align: center;"><span class="math inline">Y=y_{2}</span></th>
<th style="text-align: center;"><span class="math inline">\dots</span></th>
<th style="text-align: center;"><span class="math inline">Y=y_{J}</span></th>
<th style="text-align: center;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">X=x_{1}</span></td>
<td style="text-align: center;"><span class="math inline">n_{11}</span></td>
<td style="text-align: center;"><span class="math inline">n_{12}</span></td>
<td style="text-align: center;"><span class="math inline">\dots</span></td>
<td style="text-align: center;"><span class="math inline">n_{1J}</span></td>
<td style="text-align: center;"><span class="math inline">n_{1+}</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">X=x_{2}</span></td>
<td style="text-align: center;"><span class="math inline">n_{21}</span></td>
<td style="text-align: center;"><span class="math inline">n_{22}</span></td>
<td style="text-align: center;"><span class="math inline">\dots</span></td>
<td style="text-align: center;"><span class="math inline">n_{2J}</span></td>
<td style="text-align: center;"><span class="math inline">n_{2+}</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\dots</span></td>
<td style="text-align: center;"><span class="math inline">\dots</span></td>
<td style="text-align: center;"><span class="math inline">\dots</span></td>
<td style="text-align: center;"><span class="math inline">\dots</span></td>
<td style="text-align: center;"><span class="math inline">\dots</span></td>
<td style="text-align: center;"><span class="math inline">\dots</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">X=x_{I}</span></td>
<td style="text-align: center;"><span class="math inline">n_{I1}</span></td>
<td style="text-align: center;"><span class="math inline">n_{I2}</span></td>
<td style="text-align: center;"><span class="math inline">\dots</span></td>
<td style="text-align: center;"><span class="math inline">n_{IJ}</span></td>
<td style="text-align: center;"><span class="math inline">n_{I+}</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">Total</td>
<td style="text-align: center;"><span class="math inline">n_{+1}</span></td>
<td style="text-align: center;"><span class="math inline">n_{+2}</span></td>
<td style="text-align: center;"><span class="math inline">\dots</span></td>
<td style="text-align: center;"><span class="math inline">n_{+J}</span></td>
<td style="text-align: center;"><span class="math inline">n_{++}</span></td>
</tr>
</tbody>
</table>
</section></section>
<section>
<section id="estructura-probabilística" class="title-slide slide level1 inverse center middle" data-background-color="#063672">
<h1>Estructura probabilística</h1>

</section>
<section id="distribución-conjunta" class="slide level2">
<h2>Distribución conjunta</h2>
<p>Supongamos que elegimos al azar un individuo de nuestra población. ¿Cual es la probabilidad de que pertenezca una celda dada de la tabla de contingencia?</p>
<div class="fragment">
<p>Para cada frecuencia conjunta <span class="math inline">n_{ij}</span> en la tabla existe una probabilidad conjunta asociada <span class="math inline">p_{ij}</span>, tal que <span class="math display">p_{ij} = \mathbb{P}(X = i, Y = j)</span> - denota la probabilidad de que una observación muestreada al azar pertenezca a la celda <span class="math inline">(i,j)</span>. - la colección de probabilidades <span class="math inline">p_{ij}</span> forma la <span class="bold">distribución conjunta</span> de <span class="math inline">X</span> y <span class="math inline">Y</span>, <span class="math inline">f(x,y)</span>.</p>
</div>
</section>
<section id="estimación" class="slide level2">
<h2>Estimación</h2>
<p>Cuando trabajamos con muestras, esta probabilidad se puede estimar (MLE) a partir de las frecuencias en la tabla: <span class="math display">\hat{p}_{ij} = \frac{n_{ij}}{n}</span></p>
</section>
<section id="distribución-conjunta-1" class="slide level2">
<h2>Distribución conjunta</h2>
<p>En nuestro ejemplo,</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>          demanda
dia          alta   baja
  hábil    0.162 0.522
  no hábil 0.088 0.229</code></pre>
</div>
</div>
<div class="fragment">
<p>Como con cualquier distribución de probabilidad, sabemos que los <span class="math inline">p_{ij}</span> suman a 1.</p>
</div>
<div class="fragment">
<p>Veamos en el caso de nuestro estimador: Si <span class="math inline">\hat{p}_{ij} = \frac{n_{ij}}{n}</span>, entonces <span class="math display">\sum_{i} \sum_{j} \frac{n_{ij}}{n} = \frac{n}{n} = 1</span></p>
</div>
</section>
<section id="distribuciones-marginales" class="slide level2">
<h2>Distribuciones marginales</h2>
<p>Podemos obtener la distribución marginal de las variables <span class="math inline">X</span> y <span class="math inline">Y</span> a partir de su distribución conjunta.</p>
<div class="fragment">
<ul>
<li>La distribución marginal de <span class="math inline">X</span> (filas) está dada por:<br>
<span class="math display">p_{i+} = \sum_{j} p_{ij}</span></li>
</ul>
</div>
<div class="fragment">
<ul>
<li>La distribución marginal de <span class="math inline">Y</span> (columnas) está dada por:<br>
<span class="math display">p_{+j} = \sum_{i} p_{ij}</span></li>
</ul>
</div>
</section>
<section id="distribuciones-marginales-1" class="slide level2">
<h2>Distribuciones marginales</h2>
<div class="pull-left">
<p>Cuando trabajamos con una muestra podemos estimar las distribuciones marginales a partir de las proporciones muestrales.</p>
</div>
<div class="pull-right">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>          demanda
dia          alta   baja
  hábil    0.162 0.522
  no hábil 0.088 0.229</code></pre>
</div>
</div>
</div>
<div class="fragment">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href=""></a><span class="co"># marginal distribution rows</span></span>
<span id="cb7-2"><a href=""></a><span class="fu">rowSums</span>(joint_dis)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   hábil no hábil 
  0.684   0.316 </code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href=""></a><span class="co"># marginal distribution columns</span></span>
<span id="cb9-2"><a href=""></a><span class="fu">colSums</span>(joint_dis)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  alta   baja 
0.249 0.751 </code></pre>
</div>
</div>
</div>
<div class="fragment">
<p>Como toda distribución de probabilidad, <span class="bold">suma a 1</span>.</p>
</div>
</section>
<section id="distribución-conjunta-y-marginal-de-probabilidades" class="slide level2">
<h2>Distribución conjunta y marginal de probabilidades</h2>
<p>En resumen,</p>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 14%">
<col style="width: 17%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;"></th>
<th style="text-align: center;"><span class="math inline">Y=y_{1}</span></th>
<th style="text-align: center;"><span class="math inline">Y=y_{2}</span></th>
<th style="text-align: center;"><span class="math inline">\dots</span></th>
<th style="text-align: center;"><span class="math inline">Y=y_{J}</span></th>
<th style="text-align: center;">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">X=x_{1}</span></td>
<td style="text-align: center;"><span class="math inline">p_{11}</span></td>
<td style="text-align: center;"><span class="math inline">p_{12}</span></td>
<td style="text-align: center;"><span class="math inline">\dots</span></td>
<td style="text-align: center;"><span class="math inline">p_{1J}</span></td>
<td style="text-align: center;"><span class="math inline">p_{1+}</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">X=x_{2}</span></td>
<td style="text-align: center;"><span class="math inline">p_{21}</span></td>
<td style="text-align: center;"><span class="math inline">p_{22}</span></td>
<td style="text-align: center;"><span class="math inline">\dots</span></td>
<td style="text-align: center;"><span class="math inline">p_{2J}</span></td>
<td style="text-align: center;"><span class="math inline">p_{2+}</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\dots</span></td>
<td style="text-align: center;"><span class="math inline">\dots</span></td>
<td style="text-align: center;"><span class="math inline">\dots</span></td>
<td style="text-align: center;"><span class="math inline">\dots</span></td>
<td style="text-align: center;"><span class="math inline">\dots</span></td>
<td style="text-align: center;"><span class="math inline">\dots</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">X=x_{I}</span></td>
<td style="text-align: center;"><span class="math inline">p_{I1}</span></td>
<td style="text-align: center;"><span class="math inline">p_{I2}</span></td>
<td style="text-align: center;"><span class="math inline">\dots</span></td>
<td style="text-align: center;"><span class="math inline">p_{IJ}</span></td>
<td style="text-align: center;"><span class="math inline">p_{I+}</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">Total</td>
<td style="text-align: center;"><span class="math inline">p_{+1}</span></td>
<td style="text-align: center;"><span class="math inline">p_{+2}</span></td>
<td style="text-align: center;"><span class="math inline">\dots</span></td>
<td style="text-align: center;"><span class="math inline">p_{+J}</span></td>
<td style="text-align: center;">1</td>
</tr>
</tbody>
</table>
<p>Estructura general de probabilidades en una tabla 2-way, <span class="math inline">I \times J</span></p>
</section>
<section id="distribucion-conjunta-y-marginales" class="slide level2 middle">
<h2>Distribucion conjunta y marginales</h2>
<div class="center">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="bonus_tablas_contingencia_files/figure-revealjs/unnamed-chunk-8-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="distribuciones-condicionales" class="slide level2">
<h2>Distribuciones condicionales</h2>
<ul>
<li>Recuerden que <span class="math inline">\mathbb{P}(Y=y \mid X=x)</span> es la probabilidad de que la variable <span class="math inline">Y</span> tome valor <span class="math inline">y</span> si <span class="math inline">X</span> toma valor <span class="math inline">x</span>.</li>
</ul>
<div class="fragment">
<ul>
<li>La distribución condicional <span class="math inline">f(y \mid x)</span> es una función que expresa la probabilidad que <span class="math inline">Y</span> tome cada uno de sus posibles valores <span class="math inline">y</span>’s para <span class="math inline">X</span> fijo en cada uno de sus valores posibles <span class="math inline">x</span>’s.</li>
</ul>
</div>
<div class="fragment">
<p>Por tanto,</p>
<ul>
<li>En una tabla de contingencia podemos construir las distribuciones condicionales de las variables <span class="math inline">X</span> (o <span class="math inline">Y</span>) fijando la otra variable en sus diferentes niveles.</li>
</ul>
</div>
<div class="fragment">
<ul>
<li>Normalmente nos referimos como la “variable independiente” a la variable que usamos para condicionar, mientras que la otra variable actúa como “variable dependiente”.</li>
</ul>
</div>
</section>
<section id="distribuciones-condicionales-1" class="slide level2">
<h2>Distribuciones condicionales</h2>
<div class="pull-left">
<p>En nuestro ejemplo podemos construir la distribución condicional de la variable <code>demanda</code> dado <code>dia</code> usando la fórmula general para probabilidades condicionales:</p>
</div>
<div class="pull-right">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>          demanda
dia        alta baja
  hábil    1397 4514
  no hábil  759 1975</code></pre>
</div>
</div>
</div>
<div class="fragment">
<p><span class="math display">\begin{align}
\mathbb{P}( \text{demanda}=j | \text{ día}=i  ) &amp;= \frac{\mathbb{P}(\text{demanda}=j , \text{ día}=i )}{\mathbb{P}(\text{ día}=i)}
\end{align}</span></p>
</div>
</section>
<section id="distribuciones-condicionales-2" class="slide level2">
<h2>Distribuciones condicionales</h2>
<div class="pull-left">
<p>Sustituyendo las probabilidades de la ecuación por sus respectivos estimadores podemos estimar las distribuciones condicionales en la tabla:</p>
</div>
<div class="pull-right">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>          demanda
dia        alta baja
  hábil    1397 4514
  no hábil  759 1975</code></pre>
</div>
</div>
</div>
<div class="fragment">
<p><span class="math display">\begin{align}
\hat{p}_{j | i} &amp;= \frac{P(\text{demanda}=j , \text{ día}=i )}{P(\text{ día}=i)} \\ \\
  &amp;= \frac{\frac{n_{ij}}{n}}{\frac{\sum_{j} n_{ij}}{n}} = \frac{n_{ij}}{\sum_{j}n_{ij}}
\end{align}</span></p>
</div>
</section>
<section id="distribuciones-condicionales-3" class="slide level2">
<h2>Distribuciones condicionales</h2>
<div class="pull-left">
<p>Sustituyendo las probabilidades de la ecuación por sus respectivos estimadores podemos estimar las distribuciones condicionales en la tabla:</p>
</div>
<div class="pull-right">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>          demanda
dia        alta baja
  hábil    1397 4514
  no hábil  759 1975</code></pre>
</div>
</div>
</div>
<p>Por ejemplo, la probabilidad condicional de tener alta demanda dado que el día es hábil se estima de la siguiente manera:</p>
<p><span class="math display">\begin{align}
\hat{p}_{ \text{alta} | \text{hábil}} &amp; = \frac{n_{11}}{\sum_{j}n_{1j}} \\ \\
&amp;= \frac{1397.000}{1397.000 + 4514.000} = 0.236
\end{align}</span></p>
</section>
<section id="distribuciones-condicionales-4" class="slide level2">
<h2>Distribuciones condicionales</h2>
<div class="pull-left">
<p>Sustituyendo las probabilidades de la ecuación por sus respectivos estimadores podemos estimar las distribuciones condicionales en la tabla:</p>
</div>
<div class="pull-right">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>          demanda
dia        alta baja
  hábil    1397 4514
  no hábil  759 1975</code></pre>
</div>
</div>
</div>
<p>En términos más generales, la <em>distribución condicional</em> de la variable <code>demanda</code>, dado <code>dia</code> se estima del siguiente modo:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>          demanda
dia          alta   baja
  hábil    0.236 0.764
  no hábil 0.278 0.722</code></pre>
</div>
</div>
</section>
<section id="una-advertencia-paradoja-de-simpson" class="slide level2">
<h2>Una advertencia: Paradoja de Simpson</h2>
<p>Lo anterior implica algo incómodo: la asociación <strong>marginal</strong> entre dos variables puede ser distinta —incluso de signo opuesto— a la asociación <strong>condicional</strong> dentro de subgrupos.</p>
<div class="fragment">
<p><span class="bold">Ejemplo clásico</span>: en la demanda judicial contra UC Berkeley (1973), los datos agregados mostraban una tasa de admisión menor para mujeres que para hombres. Al condicionar por carrera, la mayoría de las carreras individualmente favorecía levemente a las mujeres — el patrón se revertía porque ellas postulaban más a carreras con tasas de admisión generales más bajas.</p>
</div>
<div class="fragment">
<p>La lección para nuestra tabla <code>dia</code> × <code>demanda</code>: si existiera una tercera variable (p.&nbsp;ej. <code>mes</code>) correlacionada con ambas, la asociación marginal que acabamos de medir podría no reflejar el patrón dentro de cada mes. Es el mismo problema que motiva controlar por covariables en un modelo de regresión.</p>
</div>
</section>
<section id="independencia-estadística" class="slide level2">
<h2>Independencia estadística</h2>
<ul>
<li>Recuerden, dos variables <span class="math inline">X</span> y <span class="math inline">Y</span> son independientes si al saber algo sobre <span class="math inline">X</span> no aprendemos nada sobre <span class="math inline">Y</span>, y viceversa: <span class="math inline">\mathbb{P}(Y|X) = \mathbb{P}(Y)</span>.</li>
<li>Check: <span class="math inline">X \bot Y \iff \mathbb{P}(X,Y) = \mathbb{P}(X)\mathbb{P}(Y)</span></li>
</ul>
<div class="fragment">
<p><span class="bold">Ejercicio rápido</span>: Supongamos que el 70% de las horas son de días hábiles, y el 25% son de alta demanda. Si la alta demanda fuera independiente del tipo de día, ¿cuál sería la probabilidad de que, al elegir una hora al azar, encontremos una de día hábil y alta demanda?</p>
<div class="full-width content-box-secondary">
<p><span class="bolder">Respuesta</span>: <span class="math display">\mathbb{P}(\text{alta},\text{hábil}) = \mathbb{P}(\text{alta})\mathbb{P}(\text{hábil}) = 0.25 \times 0.70 = 0.175</span></p>
</div>
</div>
</section>
<section id="independencia-estadística-1" class="slide level2">
<h2>Independencia estadística</h2>
<p>Podemos usar esta propiedad para comprobar independencia en una tabla de contingencia.</p>
<div class="fragment">
<ul>
<li>Si <span class="math inline">X \bot Y</span> las probabilidades conjuntas <span class="bold">esperadas bajo el supuesto de independencia</span> están dadas por: <span class="math display">\tilde{p}_{ij} = p_{i+} \times  p_{+j}</span></li>
</ul>
</div>
<div class="fragment">
<ul>
<li>Asimismo, las frecuencias esperadas bajo independencia están dadas por: <span class="math display">\tilde{n}_{ij} = n \times p_{i+} \times  p_{+j}</span></li>
</ul>
</div>
<div class="fragment">
<p><span class="bold">Importante</span>: noten que sólo necesitamos saber la distribución marginal de las variables para calcular las probabilidades y frecuencias esperadas bajo independencia.</p>
</div>
</section>
<section id="independencia-estadística-2" class="slide level2">
<h2>Independencia estadística</h2>
<div class="pull-left">
<p><span class="bold">Distribución conjunta observada</span></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>          demanda
dia          alta   baja
  hábil    0.162 0.522
  no hábil 0.088 0.229</code></pre>
</div>
</div>
</div>
<div class="pull-right">
<p><span class="bold">Distribuciones marginales</span></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   hábil no hábil 
  0.684   0.316 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>  alta   baja 
0.249 0.751 </code></pre>
</div>
</div>
</div>
<div class="fragment">
<p><span class="bold">Distribución conjunta esperada bajo independencia</span></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>        alta   baja
[1,] 0.171 0.513
[2,] 0.079 0.237</code></pre>
</div>
</div>
</div>
</section>
<section id="test-chi2-de-indepencia-estadística" class="slide level2 inverse center middle" data-background-color="#063672">
<h2>Test <span class="math inline">\chi^{2}</span> de indepencia estadística</h2>
</section>
<section id="test-chi2-de-indepencia-estadística-1" class="slide level2">
<h2>Test <span class="math inline">\chi^{2}</span> de indepencia estadística</h2>
<p>Primer paso, testear que exista <em>algo</em> de asociación: ¿son estas tablas <em>suficientemente distintas</em>?</p>
<div class="pull-left">
<p><span class="bold">Frecuencias observadas</span></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>          demanda
dia        alta baja
  hábil    1397 4514
  no hábil  759 1975</code></pre>
</div>
</div>
</div>
<div class="fragment">
<div class="pull-right">
<p><span class="bold">Frecuencias esperadas bajo independencia</span></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>           alta baja
hábil    1474.200 4437
no hábil  681.800 2052</code></pre>
</div>
</div>
</div>
<p>Donde cada frecuencia esperada bajo independencia está dada por: <span class="math inline">\tilde{n}_{ij} = n \times \hat{p}_{i+} \times  \hat{p}_{+j}</span></p>
</div>
<div class="fragment">
<ul>
<li>El test Pearson <span class="math inline">\chi^{2}</span> ( <span class="math inline">t</span> ) mide el grado asociación en la tabla de la siguiente manera:</li>
</ul>
<div class="content-box-secondary">
<p><span class="math display">t =\sum_{\text{all k: } i,j} \frac{(n_{ij} - \tilde{n}_{ij})^{2}}{\tilde{n}_{ij}}</span></p>
</div>
<p>Un valor alto de <span class="math inline">t</span> sugiere que las variables no son independientes.</p>
</div>
<div class="fragment">
<p>Pero, ¿cuánto es “alto”?</p>
</div>
</section>
<section id="test-chi2-de-indepencia-estadística-2" class="slide level2">
<h2>Test <span class="math inline">\chi^{2}</span> de indepencia estadística</h2>
<p><span class="bold">Nota:</span></p>
<ul>
<li>Si <span class="math inline">Z_{1}, \dots , Z_{k}</span> son variables independientes y cada <span class="math inline">Z \sim \text{Normal}(0,1)</span>,</li>
<li>Entonces la variable <span class="math inline">Y = \sum_{k} Z^{2} \sim \chi^{2}_{k}</span>. <span class="math inline">Y</span> distribuye <span class="math inline">\chi^{2}</span> con <span class="math inline">k</span> grados de libertad.</li>
</ul>
<div class="fragment">
<p><span class="bold">Heuristica:</span></p>
<ul>
<li><span class="math inline">t =\sum_{\text{all k: } i,j} \frac{(n_{ij} - \tilde{n}_{ij})^{2}}{\tilde{n}_{ij}}</span></li>
<li>Si no hay asociación entre las variables ( <span class="math inline">H_{0}</span> es verdadera ) entonces: <span class="math inline">t =\sum_{\text{all k: } i,j} \frac{(\text{algo cercano a cero})^{2}}{\tilde{n}_{ij}}</span></li>
</ul>
</div>
<div class="fragment">
<div class="content-box-secondary">
<p>Pearson demostró que si <span class="math inline">H_{0}</span> es veradera, entonces: <span class="math display">t \sim \chi_{df}^{2}, \quad  \text{ donde } \quad  df= (I-1)(J-1)</span></p>
</div>
</div>
</section>
<section id="test-chi2-de-indepencia-estadística-3" class="slide level2">
<h2>Test <span class="math inline">\chi^{2}</span> de indepencia estadística</h2>
<p><span class="bold">p-value</span>:</p>
<div class="content-box-secondary">
<p><span class="math display">\mathbb{P}(t  &gt; \hat{t} \mid H_{0})</span></p>
</div>
<p>equivalente a:</p>
<div class="fragment">
<div class="content-box-secondary">
<p><span class="math display">\mathbb{P}(\chi_{df}^{2}  &gt; \hat{t})</span></p>
</div>
<div class="cell">
<style type="text/css">
.pull-right ~ * { clear: unset; }
.pull-right + * { clear: both; }
</style>
</div>
</div>
</section>
<section id="test-chi2-de-indepencia-estadística-4" class="slide level2">
<h2>Test <span class="math inline">\chi^{2}</span> de indepencia estadística</h2>
<div class="pull-left">
<p><span class="bold">Frecuencias observadas</span></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>          demanda
dia        alta baja
  hábil    1397 4514
  no hábil  759 1975</code></pre>
</div>
</div>
</div>
<div class="pull-right">
<p><span class="bold">Frecuencias esperadas bajo independencia</span></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>           alta baja
hábil    1474.200 4437
no hábil  681.800 2052</code></pre>
</div>
</div>
</div>
<div class="fragment">
<p><span class="bold">(O-E)^2/E</span></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>          demanda
dia         alta  baja
  hábil    4.039 1.342
  no hábil 8.732 2.901</code></pre>
</div>
</div>
</div>
<div class="fragment">
<p><span class="bold">Test Chi-2 : ∑ (O-E)^2/E</span></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 17.010</code></pre>
</div>
</div>
</div>
</section>
<section id="test-chi2-de-indepencia-estadística-5" class="slide level2">
<h2>Test <span class="math inline">\chi^{2}</span> de indepencia estadística</h2>
<div class="pull-left">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="bonus_tablas_contingencia_files/figure-revealjs/unnamed-chunk-25-1.png" width="816"></p>
</figure>
</div>
</div>
</div>
<p><span class="bold">Para ser claros:</span> Si la hipótesis de independencia ( <span class="math inline">H_{0}</span> ) es cierta, nuestro test <span class="math inline">t</span> distribuye <span class="math inline">\chi^{2}</span> con <span class="math inline">df= (I-1)(J-1)=1</span></p>
</div>
<div class="fragment">
<div class="pull-right">
<p><span class="bold">p-value</span> <span class="math display">\mathbb{P}(\chi_{df=1}^{2} \geq \hat{t} )</span></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.000</code></pre>
</div>
</div>
</div>
</div>
</section>
<section id="test-chi2-de-indepencia-estadística-6" class="slide level2">
<h2>Test <span class="math inline">\chi^{2}</span> de indepencia estadística</h2>
<div class="pull-left">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="bonus_tablas_contingencia_files/figure-revealjs/unnamed-chunk-27-1.png" width="816"></p>
</figure>
</div>
</div>
</div>
<p><span class="bold">Para ser claros:</span> Si la hipótesis de independencia ( <span class="math inline">H_{0}</span> ) es cierta, nuestro <span class="math inline">\text{test } \chi^{2}</span> distribuye <span class="math inline">\chi^{2}</span> con <span class="math inline">df= (I-1)(J-1)=1</span></p>
</div>
<div class="pull-right">
<p><span class="bold">p-value</span> <span class="math display">\mathbb{P}(\chi_{df=1}^{2} \geq \hat{t})</span></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.000</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  ctable
X-squared = 17, df = 1, p-value = 0.000</code></pre>
</div>
</div>
</div>
<div class="fragment">
<p><span class="bold">Conclusión</span>: con 8.645 observaciones, el valor obtenido en nuestro test es extremadamente improbable bajo independencia (p-value <span class="math inline">\approx 0</span>). Tenemos evidencia fuerte de que el tipo de día y el nivel de demanda están asociados.</p>
</div>
</section>
<section id="medidas-de-asociación" class="slide level2 inverse center middle" data-background-color="#063672">
<h2>Medidas de Asociación</h2>
</section>
<section id="asociación-en-tablas-de-contingencia" class="slide level2">
<h2>Asociación en tablas de contingencia</h2>
<p>Las variables de una tabla de contingencia están asociadas si la distribución condicional de las variables es distinta de su distribución marginal. Formalmente,</p>
<ul>
<li><p><span class="math inline">f_{Y \mid X}(Y \mid X) \neq f_{Y}(Y)</span> y por tanto,</p></li>
<li><p><span class="math inline">f_{X \mid Y}(X \mid Y) \neq f_{X}(X)</span></p></li>
</ul>
</section>
<section id="asociación-en-tablas-de-contingencia-1" class="slide level2">
<h2>Asociación en tablas de contingencia</h2>
<p>Continuando con nuestro ejemplo,</p>
<div class="pull-left">
<p><span class="math inline">f(\text{demanda} \mid \text{dia})</span></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>          demanda
dia          alta   baja
  hábil    0.236 0.764
  no hábil 0.278 0.722</code></pre>
</div>
</div>
<p><span class="math inline">f(\text{demanda})</span></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  alta   baja 
0.249 0.751 </code></pre>
</div>
</div>
</div>
<div class="fragment">
<div class="pull-right">
<p>Al parecer, las horas de días hábiles tienen una probabilidad distinta de alta demanda que las de días no hábiles. En lo que sigue vamos a usar este ejemplo para estudiar:</p>
<ul>
<li>Diferentes formas de cuantificar la asociación (o la ausencia de la misma) entre variables de una tabla de contingencia</li>
<li>Evaluar si las diferencias observadas son o no más sustanciales de lo se esperaría debido al mero azar.</li>
</ul>
</div>
</div>
</section>
<section id="medidas-de-asociación-1" class="slide level2 inverse center middle" data-background-color="#063672">
<h2>Medidas de Asociación</h2>
</section>
<section id="diferencia-de-proporciones" class="slide level2">
<h2>Diferencia de proporciones</h2>
</section>
<section id="diferencia-de-proporciones-1" class="slide level2">
<h2>Diferencia de proporciones</h2>
<ul>
<li>Supongamos que tenemos una tabla de contingencia 2-ways que cruza las variables binarias <span class="math inline">X</span> (independiente) y <span class="math inline">Y</span> (dependiente). Éxito se codifica con valor 1 y el fracaso con el valor 0.</li>
<li>Para detectar la asociación necesitamos medir diferencias en la distribución de <span class="math inline">Y</span> condicional en <span class="math inline">X</span></li>
</ul>
<div class="fragment">
<p>La diferencia de proporciones cuantifica estas diferencias de la siguiente manera: <span class="math display">\delta = \mathbb{P}(Y=1 \mid X=1) - \mathbb{P}(Y=1 \mid X=0)</span></p>
</div>
<div class="fragment">
<p>Noten que <span class="math inline">\delta \in [-1,1]</span> donde <span class="math inline">\delta=0</span> indica proporciones iguales.</p>
</div>
<div class="fragment">
<p>Volviendo a nuestro ejemplo, llamemos <span class="math inline">\hat{p}_{H}</span> a la proporción de horas de alta demanda en días hábiles y <span class="math inline">\hat{p}_{NH}</span> a la proporción de alta demanda en días no hábiles. La diferencia de proporciones se define simplemente como:</p>
<p><span class="math display">\begin{align}
  \hat{\delta} &amp;= \hat{p}_{H} - \hat{p}_{NH} \\ \\
  &amp;= 0.236 - 0.278 \\ \\
  &amp;= -0.041
\end{align}</span></p>
</div>
</section>
<section id="diferencia-de-proporciones-2" class="slide level2">
<h2>Diferencia de proporciones</h2>
<p>Dos consideraciones importantes:</p>
<ol type="1">
<li>La diferencia de proporciones debe estar adecuadamente definida en términos de una variable dependiente y otra independiente. La razón es que, en general: <span class="math display">\mathbb{P}(Y=1 \mid X=1) - \mathbb{P}(Y=1 \mid X=0) \neq  \mathbb{P}(X=1 \mid Y=1) - \mathbb{P}(X=1 \mid Y=0)</span></li>
</ol>
<div class="fragment">
<p>En nuestro ejemplo:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>          demanda
dia          alta   baja
  hábil    0.648 0.696
  no hábil 0.352 0.304</code></pre>
</div>
</div>
<p>Si tratamos el tipo de día como variable dependiente y definimos “día hábil” como la categoría de éxito, la diferencia en las proporciones es <span class="math inline">\delta = -0.048</span>.</p>
</div>
</section>
<section id="diferencia-de-proporciones-3" class="slide level2">
<h2>Diferencia de proporciones</h2>
<ol start="2" type="1">
<li>La diferencia de proporciones es una estadística intuitiva y fácil de interpretar, pero por sí sola puede ser engañosa cuando las proporciones son ambas cercanas a cero. Consideremos los dos casos hipotéticos siguientes:</li>
</ol>
<p><span class="math display">\begin{align}
  \text{Caso 1: } p_{1a}=0.410 \text{ and } p_{1b}=0.401  \\ \\
  \text{aquí: } \delta_{1} = 0.009
\end{align}</span></p>
<div class="fragment">
<p>y</p>
<p><span class="math display">\begin{align}
  \text{Caso 2: } p_{2a}=0.010 \text{ and } p_{2b}=0.001  \\ \\
  \text{aquí: } \delta_{2} = 0.009
\end{align}</span></p>
</div>
<div class="fragment">
<p>¿Problemas? En el caso 1 ambas porciones son, según todos los indicios, casi idénticas. En el caso 2, sin embargo, ambas proporciones son similares en términos absolutos, por muy diferentes en términos relativos: <span class="math inline">0.010</span> es 10 veces mayor <span class="math inline">0.001</span>.</p>
</div>
</section>
<section id="medidas-de-asociación-2" class="slide level2 inverse center middle" data-background-color="#063672">
<h2>Medidas de Asociación</h2>
</section>
<section id="odds-ratio" class="slide level2">
<h2>Odds Ratio</h2>
</section>
<section id="odds-ratio-1" class="slide level2">
<h2>Odds Ratio</h2>
<div class="fragment">
<ul>
<li>Odds ratio ( <span class="math inline">\theta</span> ) es una medida fundamental de asociación.</li>
</ul>
</div>
<div class="fragment">
<ul>
<li>Parámetro de interés en el modelo más importante de datos categóricos: regresión logística.</li>
</ul>
</div>
<div class="fragment">
<ul>
<li><span class="math inline">\theta</span> está formulada para tablas de 2-por-2, pero también puede calcularse para tablas de mayor dimensión:
<ul>
<li>Toda tabla <span class="math inline">n</span>-ways, <span class="math inline">I \times J</span>, puede ser re-escrita como <span class="math inline">(I-1) \times (J-1) \times (n-1)</span> tablas de 2-por-2.</li>
</ul></li>
</ul>
</div>
</section>
<section id="odds" class="slide level2">
<h2>Odds</h2>
<p>La Odds Ratio es el ratio de dos “odds”, donde las “odds” una variable binaria <span class="math inline">Y</span> se definen como:</p>
<p><span class="math display">\begin{align}
  \text{odds} &amp;= \frac{\mathbb{P}(Y=1)}{1-\mathbb{P}(Y=1)} \\ \\
              &amp;=  \frac{p}{1-p}
\end{align}</span></p>
<div class="fragment">
<p>Por ejemplo, si <span class="math inline">Y</span> tiene una probabilidad de éxito <span class="math inline">p=0.75</span>, las odds de éxito son <span class="math inline">\text{odds}=\frac{0.75}{0.25} = 3</span></p>
<ul>
<li>Esto significa que las “chances” de éxito son 3:1</li>
</ul>
</div>
</section>
<section id="odds-1" class="slide level2">
<h2>Odds</h2>
<p>las Odds son funciones de probabilidades y, por lo tanto, las probabilidades también pueden expresarse en función de las odds. Formalmente:</p>
<p><span class="math display">p = \frac{\text{odds}}{1 + \text{odds}}</span></p>
<div class="fragment">
<p>Siguiendo con ejemplo anterior, si sabemos que las odds de éxito son igual a 3, entonces la probabilidad <span class="math inline">p</span> de éxito es:</p>
<p><span class="math display">\begin{align}
p &amp;= \frac{3}{1 + 3} \\ \\
  &amp;= 0.75
\end{align}</span></p>
</div>
</section>
<section id="odds-ratio-2" class="slide level2">
<h2>Odds Ratio</h2>
<p>Las <span class="bold">odds</span> resumen la distribución de una sola variable binaria. Para medir la asociación entre dos de estas variables en una tabla podemos calcular la <span class="bold">odds <em>ratio</em></span>.</p>
<div class="fragment">
<p>Si <span class="math inline">X</span> e <span class="math inline">Y</span> son las variables binarias – independiente y dependiente – la distribución condicional <span class="math inline">f(Y \mid X)</span> se puede resumir con dos <span class="bold">odds</span>:</p>
<p><span class="math display">\begin{align}
  \text{odds}_{0} &amp;=  \frac{\mathbb{P}(Y=1 | X=0) }{1 - \mathbb{P}(Y=1 | X=0) } \quad \text{y} \\ \\
  \text{odds}_{1} &amp;=  \frac{\mathbb{P}(Y=1 | X=1) }{1 - \mathbb{P}(Y=1 | X=1) }
\end{align}</span></p>
</div>
<div class="fragment">
<p>La <span class="bold">odds <em>ratio</em></span>, por tanto, es:</p>
<p><span class="math display">\begin{align}
  \theta &amp;= \frac{\text{odds}_{1}}{\text{odds}_{0}} \\ \\\
\end{align}</span>\end{align}</p>
</div>
</section>
<section id="odds-ratio-3" class="slide level2">
<h2>Odds Ratio</h2>
<p>Volviendo a nuestro ejemplo,</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>          demanda
dia          alta   baja
  hábil    0.236 0.764
  no hábil 0.278 0.722</code></pre>
</div>
</div>
<p>Si <span class="math inline">\hat{p}_{H}</span> es la proporción de alta demanda en días hábiles y <span class="math inline">\hat{p}_{NH}</span> la proporción de alta demanda en días no hábiles.</p>
<p><span class="math display">\begin{align}
  \hat{\theta} = \frac{\text{odds}_{H}}{\text{odds}_{NH}} &amp;= \frac{\hat{p}_{H}/(1 - \hat{p}_{H})}{\hat{p}_{NH}/(1 - \hat{p}_{NH})} \\ \\
         &amp;= \frac{0.236/0.764}{0.278/0.722} \\ \\
         &amp;= 0.805
\end{align}</span></p>
</section>
<section id="odds-ratio-4" class="slide level2">
<h2>Odds Ratio</h2>
<p>Dado que estas proporciones se <em>estiman</em> a partir de los recuentos de la tabla, <span class="math inline">\hat{\theta}</span> también puede expresarse de la siguiente manera, denominada <span class="bold">cross-product ratio</span>. En nuestro ejemplo,</p>
<div class="pull-left">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>          demanda
dia        alta baja
  hábil    1397 4514
  no hábil  759 1975</code></pre>
</div>
</div>
</div>
<div class="pull-right">
<p><span class="math display">\begin{align}
  \hat{\theta} &amp;= \frac{\hat{p}_{H}/(1 - \hat{p}_{H})}{\hat{p}_{M}/(1 - \hat{p}_{M})} \\ \\
   &amp;= \frac{\frac{n_{21}}{n_{2+}} / \frac{n_{22}}{n_{2+}}}{\frac{n_{11}}{n_{1+}}/ \frac{n_{12}}{n_{1+} }} = \frac{n_{21}/n_{22}}{n_{11}/n_{12}}  \\ \\
   &amp;= \frac{n_{21} \times n_{12}}{n_{22} \times n_{11}} \\ \\
\end{align}</span></p>
</div>
<div class="fragment">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.805</code></pre>
</div>
</div>
</div>
</section>
<section id="odds-ratio-5" class="slide level2">
<h2>Odds Ratio</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.805</code></pre>
</div>
</div>
<p><span class="bold">Interpretación</span>: las odds de alta demanda en un día hábil son 0.805 veces las de un día no hábil. Notice that:</p>
<ul>
<li><span class="math inline">\theta \in [0,\infty+]</span></li>
</ul>
<div class="fragment">
<ul>
<li><span class="math inline">\theta=1</span> indica igualdad de odds y, por lo tanto, independencia</li>
</ul>
</div>
<div class="fragment">
<ul>
<li><span class="math inline">\theta &gt; 1</span> indica que el éxito es más probable para el grupo en el numerador (días hábiles en este caso)</li>
</ul>
</div>
<div class="fragment">
<ul>
<li><span class="math inline">\theta &lt; 1</span> indica que el éxito es más probable para el grupo en el denominador (días no hábiles en este caso)</li>
</ul>
</div>
<div class="fragment">
<ul>
<li>Valores lejos de 1, en cualquier dirección, representan una fuerte evidencia contra independencia</li>
</ul>
</div>
</section>
<section id="propiedades-de-la-odds-ratio" class="slide level2">
<h2>Propiedades de la Odds Ratio</h2>
<ol type="1">
<li>Invirtiendo el orden de las filas o columnas obtenemos el inverso la odds ratio original.</li>
</ol>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>          demanda
dia          alta   baja
  hábil    0.236 0.764
  no hábil 0.278 0.722</code></pre>
</div>
</div>
<p>Si <span class="math inline">\hat{p}_{H}</span> es la proporción de alta demanda en días hábiles y <span class="math inline">\hat{p}_{NH}</span> en días no hábiles.</p>
<div class="pull-left">
<p><span class="math display">\begin{align}
  \hat{\theta}_{H,NH} &amp;= \frac{\hat{p}_{H}/(1 - \hat{p}_{H})}{\hat{p}_{NH}/(1 - \hat{p}_{NH})} \\ \\
         &amp;= 0.805
\end{align}</span></p>
</div>
<div class="pull-right">
<p><span class="math display">\begin{align}
  \hat{\theta}_{NH,H} &amp;= \frac{\hat{p}_{NH}/(1 - \hat{p}_{NH})}{\hat{p}_{H}/(1 - \hat{p}_{H})} \\ \\
         &amp;= 1.242
\end{align}</span></p>
</div>
<div class="full-width">
<p>Tanto <span class="math inline">\theta</span> como <span class="math inline">1/\theta</span> expresan el <span class="bold">mismo grado de asociación</span>.</p>
</div>
</section>
<section id="propiedades-de-la-odds-ratio-1" class="slide level2">
<h2>Propiedades de la Odds Ratio</h2>
<ol start="2" type="1">
<li>A diferencia de las otras medidas, la odds ratio no varia en función de que variable actúa como dependiente e independiente. En otras palabras, no es necesario identificar una variable independiente para estimar correctamente <span class="math inline">\theta</span></li>
</ol>
<div class="fragment">
<p>En nuestro ejemplo, tomando el tipo de día como variable dependiente, donde <span class="math inline">\hat{p}_{A}</span> es la probabilidad de que sea un día hábil entre las horas de alta demanda y <span class="math inline">\hat{p}_{B}</span> es la misma probabilidad entre las horas de baja demanda, la odds ratio de “día hábil” es:</p>
<div class="pull-left">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>          demanda
dia          alta   baja
  hábil    0.648 0.696
  no hábil 0.352 0.304</code></pre>
</div>
</div>
</div>
<div class="pull-right">
<p><span class="math display">\begin{align}
  \hat{\theta} &amp;= \frac{\hat{p}_{A}/(1 - \hat{p}_{A})}{\hat{p}_{B}/(1 - \hat{p}_{B})} \\ \\
         &amp;= 0.805
\end{align}</span></p>
</div>
</div>
</section>
<section id="propiedades-de-la-odds-ratio-2" class="slide level2">
<h2>Propiedades de la Odds Ratio</h2>
<ol start="3" type="1">
<li>La Odds Ratio es <span class="bold">margins-free</span>: la odds ratio de una tabla de contingencia no se ven alteradas por el “escalamiento” (multiplicación por una constante) de filas o columnas.</li>
</ol>
<div class="fragment">
<div class="pull-top">
<div class="pull-left">
<p><span class="bold">Movilidad educacional 1980</span></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>          Hijos: NU Hijos: U
Padre: NU       160       20
Padres: U        20       20</code></pre>
</div>
</div>
</div>
<div class="pull-right">
<p><span class="bold">Movilidad educacional 2020</span></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>          Hijos: NU Hijos: U
Padre: NU       160       80
Padres: U        20       80</code></pre>
</div>
</div>
</div>
</div>
</div>
<div class="fragment">
<div class="pull-bottom">
<div class="pull-left">
<ul>
<li>El <span class="bold">13%</span> de los hijos padres sin estudios universitarios obtenía un grado universitario</li>
</ul>
</div>
<div class="pull-right">
<ul>
<li>El <span class="bold">33%</span> de los hijos padres sin estudios universitarios obtiene un grado universitario</li>
</ul>
</div>
</div>
</div>
<div class="fragment">
<ul>
<li><span class="bold">Diferencia de proporciones</span>: 0.33 - 0.13 = 0.2</li>
</ul>
</div>
<div class="fragment">
<div class="full-width">
<p><span class="bold">Ejemplo de interpretación apresurada:</span> <em>“La movilidad educacional casi se triplicó y, por tanto, la desigualdad de oportunidades dejó de ser un problema.”</em></p>
</div>
</div>
<div class="fragment">
<p><span class="bold">Correcto?</span></p>
<div class="cell">
<style type="text/css">
.pull-right ~ * { clear: unset; }
.pull-right + * { clear: both; }
</style>
</div>
</div>
</section>
<section id="propiedades-de-la-odds-ratio-3" class="slide level2">
<h2>Propiedades de la Odds Ratio</h2>
<p><span class="bold">una verdad parcial:</span> el resultado refleja un <span class="bold">cambio en la distribución marginal</span> de educación de los hijos, no un cambio en la asociación de las variables.</p>
<div class="fragment">
<p>Concretamente, se cuaduplicó la cantidad de gente que termina la universidad, independiente de su origen.</p>
<div class="pull-top">
<div class="pull-left">
<p><span class="bold">Movilidad educacional 1980</span></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>          Hijos: NU Hijos: U
Padre: NU       160       20
Padres: U        20       20</code></pre>
</div>
</div>
</div>
<div class="pull-right">
<p><span class="bold">Movilidad educacional 2020</span></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>          Hijos: NU Hijos: U
Padre: NU       160       80
Padres: U        20       80</code></pre>
</div>
</div>
</div>
<div class="fragment">
<div class="pull-bottom">
<div class="full-width">
<p>La odds ratio es “inmune a cambios” en la distribución marginal de las variables, capturando sólo la asociación neta entre ellas (“margin-free association”)</p>
</div>
<div class="pull-left">
<p><span class="math inline">\hat{\theta}_{1980} =  \frac{160 \times 20}{20 \times 20} = 8</span></p>
</div>
<div class="pull-right">
<p><span class="math inline">\hat{\theta}_{2020} =  \frac{160 \times 80}{20 \times 80} = \frac{160 \times (4 \times 20)}{20 \times (4 \times 20)} = 8</span></p>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="log-odds-ratio" class="slide level2">
<h2>Log Odds Ratio</h2>
<p>Como sabemos, <span class="math inline">\theta \in [0,\infty+)</span>. Esto crea un problema tanto para la <span class="bold">interpretación</span> como para la <span class="bold">inferencia estadística</span>. Por ejemplo:</p>
<ul>
<li>Supongamos que la odds ratio (día hábil a no hábil) de alta demanda es <span class="math inline">\theta = 20</span>.</li>
<li>Por ende, la odds ratio (no hábil a día hábil) de alta demanda es <span class="math inline">\theta^{*} = 1/ \theta = 0.05</span>.</li>
<li>Ambos resultados indican el <span class="bold">mismo nivel de asociación</span>, pero uno parece mucho más grande que el otro.</li>
</ul>
<div class="fragment">
<p>Transformando <span class="math inline">\theta</span> a escala logarítmica permite mapear <span class="math inline">[0,\infty+) \to (-\infty,\infty+)</span>, creando una medida de asociación simétrica.</p>
<p><span class="math display">\begin{align}
  \theta &amp;=  1/\theta^{*}  \quad \text{entonces} \\ \\
  \log(\theta) &amp;= -1 \times \log(\theta^{*})
\end{align}</span></p>
</div>
<div class="fragment">
<p>En nuestro ejemplo:</p>
<div class="pull-left">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.996</code></pre>
</div>
</div>
</div>
<div class="pull-right">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] -2.996</code></pre>
</div>
</div>
</div>
</div>
</section>
<section id="log-odds-ratio-1" class="slide level2">
<h2>Log Odds Ratio</h2>
<ul>
<li><span class="math inline">\log(\theta) \in (\infty-,\infty+)</span></li>
<li><span class="math inline">\theta=0</span> indica igualdad de odds y, por lo tanto, independencia</li>
<li><span class="math inline">\log(\theta) &gt; 0</span> indica que el éxito es más probable para el grupo en el numerador</li>
<li><span class="math inline">\log(\theta) &lt; 0</span> indica que el éxito es más probable para el grupo en el denominador</li>
<li><span class="math inline">\lvert \log(\theta) \rvert</span> indica la fuerza de la asociación entre las variables</li>
<li>Valores lejos de 0, en cualquier dirección, representan fuerte evidencia contra independencia</li>
</ul>
</section>
<section id="inferencia-para-medidas-de-asociación" class="slide level2 inverse center middle" data-background-color="#063672">
<h2>Inferencia para Medidas de Asociación</h2>
</section>
<section id="inferencia-para-medidas-de-asociación-1" class="slide level2">
<h2>Inferencia para medidas de Asociación</h2>
<p>O, sobre como podemos saber si nuestros resultados no son, o no, producidos por el mero azar.</p>
<div class="fragment">
<ul>
<li>Para responder esta pregunta debemos conocer la <span class="bold">sampling distribution</span> de nuestro estimador, especialmente su <em>variabilidad</em>.</li>
<li>Los parámetros que “generan” los datos no varían pero nuestra estimaciones si: de muestra en muestra.</li>
</ul>
</div>
<div class="fragment">
<p><span class="bold">Caso canónico</span> es el <em>promedio muestral</em>, para el cual sabemos que: <span class="math inline">\bar{X} \sim \text{Normal}(\mu,\frac{\sigma}{\sqrt{n}})</span> - La desviación estándar del <span class="bold">estimador</span> (en este caso, <span class="math inline">\frac{\sigma}{\sqrt{n}}</span> ) es lo que denominamos <span class="bold">error estándar (SE)</span>.</p>
</div>
<div class="fragment">
<ul>
<li>Por qué? Si <span class="math inline">x_1, \dots, x_n</span> son <em>iid</em>, entonces:</li>
</ul>
<p><span class="math display">\begin{align}
\operatorname{Var}\big(\bar{X}\big) &amp;= \operatorname{Var}\Big(\frac{x_{i} + ... + x_{n}}{n}\Big) = \frac{1}{n^2} \Big(\operatorname{Var}(x_{i}) + ... + \operatorname{Var}(x_{n})\Big) \\
&amp;= \frac{1}{n^2}( \sigma^2 + ... + \sigma^2 ) = \frac{n\sigma^2}{n^2} = \frac{\sigma^2}{n}
\end{align}</span></p>
</div>
</section>
<section id="inferencia-para-diferencia-de-proporciones" class="slide level2">
<h2>Inferencia para Diferencia de proporciones</h2>
<p>Como recordarán de clases anteriores, asintóticamente, la “sampling distribution” de una proporción es: <span class="math display">\hat{p} \sim \text{Normal}(\mu,\sigma) \quad \quad \text{ donde }\mu = p \quad \text{ y }\quad \sigma^2 = p(1-p)/n</span></p>
<div class="fragment">
<p>Por tanto, la “sampling distribution” de la diferencia entre dos proporciones <em>independientes</em>, <span class="math inline">\hat{\delta} = \hat{p}_{1} - \hat{p}_{2}</span>, es: <span class="math display">\text{Normal}\Big(\mu_{1} = p_{1}, \sigma_{1} = \sqrt{p_{1}(1-p_{1})/n_{1}}\Big) - \text{Normal}\Big(\mu_{2} = p_{2},  \sigma_{2} = \sqrt{p_{2}(1-p_{2})/n_{2}}\Big)</span></p>
</div>
<div class="fragment">
<p>dado que para variables independiente X e Y: - <span class="math inline">\mathbb{E}(X - Y)  = E(X) -  E(Y)</span> y <span class="math inline">\operatorname{Var}(X - Y)  = \operatorname{Var}(X) + \operatorname{Var}(Y)</span></p>
</div>
<div class="fragment">
<ul>
<li><span class="math inline">\text{Normal}() \pm \text{Normal}() \sim \text{Normal}()</span>, entonces:</li>
</ul>
</div>
<div class="fragment">
<div class="content-box-secondary">
<p><span class="math display">\hat{p}_{1} - \hat{p}_{2} \sim \text{Normal}\Big(\mu_{\delta} = p_{1} - p_{2}, \sigma_{\delta} = \sqrt{p_{1}(1-p_{1})/n_{1} + p_{2}(1-p_{2})/n_{2}}\Big)</span></p>
</div>
</div>
</section>
<section id="inferencia-para-diferencia-de-proporciones-1" class="slide level2">
<h2>Inferencia para Diferencia de proporciones</h2>
<p><span class="bold">Intervalo de confianza</span> Podemos usar este resultado para construir un intervalo de confianza para <span class="math inline">\hat{\delta} = \hat{p_{1}} - \hat{p_{2}}</span>, al (1 - <span class="math inline">\alpha</span>)% de confianza. Para un nivel de significación estadística de <span class="math inline">\alpha=0.05</span>,</p>
<p><span class="math display">\begin{align}
  95\% \text{ CI}_{\hat{\delta}} &amp;= \hat{\delta} \pm 2 \times SE \\ \\
          &amp;= (\hat{p_{1}} - \hat{p_{2}}) \pm 2  \sqrt{p_{1}(1-p_{1})/n_{1} + p_{2}(1-p_{2})/n_{2}}
\end{align}</span></p>
<p><span class="bold">Nota importante</span>: cuando no conocemos los <em>verdaderos</em> parámetros reemplazamos por sus valores estimados (en este caso, <span class="math inline">\hat{p_{1}}</span> y <span class="math inline">\hat{p_{2}}</span> en vez de <span class="math inline">p_{1}</span> y <span class="math inline">p_{2}</span>).</p>
</section>
<section id="inferencia-para-diferencia-de-proporciones-2" class="slide level2">
<h2>Inferencia para Diferencia de proporciones</h2>
<p><span class="math display">95\% \text{ CI}_{\hat{\delta}} = (\hat{p_{1}} - \hat{p_{2}}) \pm 2  \sqrt{p_{1}(1-p_{1})/n_{1} + p_{2}(1-p_{2})/n_{2}}</span> En nuestro ejemplo,</p>
<div class="pull-left">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>          demanda
dia        alta baja
  hábil    1397 4514
  no hábil  759 1975</code></pre>
</div>
</div>
</div>
<div class="pull-right">

</div>
<div class="fragment">
<div class="pull-left">
<p>Nuestro 95% CI:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>     ll      ul 
0.021 0.062 </code></pre>
</div>
</div>
</div>
<div class="pull-right">
<p>Versión automática con <code>prop.test()</code> en <code>R</code>:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.021 0.061</code></pre>
</div>
</div>
</div>
<div class="cell">
<style type="text/css">
.pull-right ~ * { clear: unset; }
.pull-right + * { clear: both; }
</style>
</div>
</div>
</section>
<section id="inferencia-para-la-odds-ratio" class="slide level2">
<h2>Inferencia para la Odds Ratio</h2>
<ul>
<li>Cual es la <span class="bold">sampling distribucion</span> de <span class="math inline">\hat{\theta}</span>?</li>
</ul>
<div class="fragment">
<ul>
<li>Si para un proporción sabemos que <span class="math inline">\hat{p} \sim \text{Normal}(\mu,\sigma) \quad \quad \text{ donde }\mu = p \quad \text{ y }\quad \sigma^2 = p(1-p)/n</span></li>
</ul>
<p>La sampling distribution de <span class="math inline">\hat{\theta}</span> debe ser …</p>
</div>
<div class="fragment">
<div class="pull-left">
<p><span class="math display">\hat{\theta} = \frac{\hat{p}_{1}/(1 - \hat{p}_{1})}{\hat{p}_{2}/(1 - \hat{p}_{2})}  \sim \frac{\frac{\text{Normal}(\mu_{1},\sigma_{1})}{1 - \text{Normal}(\mu_{1},\sigma_{1})}}{\frac{\text{Normal}(\mu_{2},\sigma_{2})}{1 - \text{Normal}(\mu_{2},\sigma_{2})}}</span></p>
</div>
</div>
<div class="fragment">
<div class="pull-right">
<p><img data-src="meme.png" alt="meme"> Complicado …</p>
</div>
</div>
</section>
<section id="inferencia-para-la-odds-ratio-1" class="slide level2">
<h2>Inferencia para la Odds Ratio</h2>
<ul>
<li>Más conveniente hacer inferencia sobre <span class="math inline">\log \hat{\theta}</span></li>
<li>Usando la definición de <span class="math inline">\hat{\theta}</span> como cross-product, obtenemos: <span class="math display">\log \hat{\theta} = \log \frac{n_{11}n_{22}}{n_{12}n_{21}} = \log n_{11} + \log n_{22} - \log n_{12} - \log n_{21}</span></li>
</ul>
<div class="fragment">
<p>Importante resultado teórico: la sampling distribution de <span class="math inline">\log \hat{\theta}</span> es <em>asintóticamente</em> normal: <span class="math display">\log(\hat{\theta}) \sim \text{Normal}(\mu,\sigma)</span> con parámetros <em>estimados</em> por: - <span class="math inline">\hat{\mu} = \log \hat{\theta}</span> - <span class="math inline">\hat{\sigma} = \sqrt{ \frac{1}{n_{11}} + \frac{1}{n_{12}} + \frac{1}{n_{21}} + \frac{1}{n_{22}}}</span></p>
</div>
</section>
<section id="inferencia-para-la-odds-ratio-2" class="slide level2">
<h2>Inferencia para la Odds Ratio</h2>
<p><span class="bold">Intervalo de confianza para log Odds ratio</span></p>
<div class="fragment">
<p>Podemos usar este resultado para construir un intervalo de confianza para el log Odds ratio, al (1 - <span class="math inline">\alpha</span>) de confianza. Para un nivel de significación estadística de <span class="math inline">\alpha=0.05</span>,</p>
<p><span class="math display">\begin{align}
  95\% \text{ CI}_{\log \hat{\theta}} &amp;= \log \hat{\theta} \pm 2 \times SE \\ \\
          &amp;= \log \hat{\theta} \pm 2 \times \sqrt{ \frac{1}{n_{11}} + \frac{1}{n_{12}} + \frac{1}{n_{21}} + \frac{1}{n_{22}} }
\end{align}</span></p>
</div>
<div class="fragment">
<p><span class="bold">Intervalo de confianza para Odds ratio</span> Podemos obtener un intervalo de confianza estándar para la Odds ratio, al (1 - <span class="math inline">\alpha</span>) de confianza tomando el exponencial del intervalo obtenido para <span class="math inline">\log \hat{\theta}</span>.</p>
<p><span class="math display">\begin{align}
  95\% \text{ CI}_{\hat{\theta}} &amp;= e^{\log \hat{\theta} \pm 2 \times \sqrt{ \frac{1}{n_{11}} + \frac{1}{n_{12}} + \frac{1}{n_{21}} + \frac{1}{n_{22}}} }
\end{align}</span></p>
</div>
</section>
<section id="intervalo-de-confianza-para-odds-ratio" class="slide level2">
<h2>Intervalo de confianza para Odds ratio</h2>
<p><span class="math display">\begin{align}
  95\% \text{ CI}_{\log \hat{\theta}} = \log \hat{\theta} \pm 2 \times \sqrt{ \frac{1}{n_{11}} + \frac{1}{n_{12}} + \frac{1}{n_{21}} + \frac{1}{n_{22}} }
\end{align}</span></p>
<div class="fragment">
<p>En nuestro ejemplo,</p>
<div class="pull-left">
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>          demanda
dia        alta baja
  hábil    1397 4514
  no hábil  759 1975</code></pre>
</div>
</div>
</div>
<div class="pull-right">

</div>
<p><span class="bold">Intervalos de confianza:</span></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>     ll      ul 
-0.322 -0.111 </code></pre>
</div>
</div>
</div>
</section>
<section id="gracias" class="slide level2 inverse center middle closing" data-background-color="#D71920">
<h2>Gracias</h2>
<p><strong>Hasta la próxima clase</strong></p>
<p>Mauricio Bucca</p>

</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="bonus_tablas_contingencia_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="bonus_tablas_contingencia_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="bonus_tablas_contingencia_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="bonus_tablas_contingencia_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="bonus_tablas_contingencia_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="bonus_tablas_contingencia_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="bonus_tablas_contingencia_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="bonus_tablas_contingencia_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="bonus_tablas_contingencia_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: false,

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1600,

        height: 900,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>